### ISSUE TITLE
"Buy" trade shops

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#348]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/347

**Originally posted by nhawdge (Oct 20, 2015):** 

What is the enhancement in mind? How should it look and feel?Please provide any additional information below.HI firstly, my players and I absolutely love this plugin. It is exactly what we want. We use it without currency so trade only villagers and it is perfect.With a trade villager, I would like to see being able to setup more purchase orders. For example. I stock my chest with diamonds. I can only set my diamonds to "buy" iron. I would like to set my diamonds to buy iron, lapis, gold, etc. I imagine the feel could be the same way you set the price with a trade villager.Thank you for your amazing efforts!

**Comment by blablubbabcDEV** [comment]
**Originally commented by Zegiond (Mar 7, 2016):** 

I have also a Citizen plugin and everytime i put trades ./trait shopkeeper to an NPC after some time he lost all of his trait.. why?

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Mar 7, 2016):** 

[at]Zegiond:
Please create a separate ticket for your issues in the future.
Anyways: Citizens has a save command which seems to be required in newer versions. I assume your trade might go lost, because you are not saving your npcs.

**Comment by blablubbabc** [comment]
Duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/6
