### ISSUE TITLE
Fail export purchases when Shift + Clic

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#360]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/359

**Originally posted by Almathy (Dec 22, 2015):** 

What steps will reproduce the problem?

1. Have 64 iron igots

2. Open a shopkeeper which sell 1 diamond against 8 iron igots

3. Shift + Clic to buy directly 8 diamonds
What is the expected output? What do you see instead?
In the purchases file, it's like if I've buy 1 diamond against 8 iron ingots. All isn't counted when I use Shift + Clic
What version of the product are you using?

v1.68 
Do you have an error log of what happened?
[18:52:06 INFO]: [Shopkeepers] Player Almathy clicked: raw slot id=2, slot id=2, slot type=RESULT, shift=true, left or right=left, action=MOVE_TO_OTHER_INVENTORY

**Comment by blablubbabc** [comment]
This might be fixed by bbd437388748da60ebf6ba14f5c93871a4c30081

**Comment by blablubbabc** [comment]
Should be fixed in v1.87. Please let me know of any issues.
