### ISSUE TITLE
Add a way to move/reposition a shopkeeper

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#361]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/360

**Originally posted by blablubbabc (Dec 28, 2015):** 

Add a way to move/reposition a shopkeeper

Possible solutions might be:
* Via command (ex. `/shopkeeper move <shopkeeperId>`): Easy to add, but preferably not requiring a command for this but doing it via editor inventory action instead.
* Via editor menu action, select action and then clicking a block to move the shopkeeper there): Might only be practicable for short distances, relatively easy to implement, requires extending the editor menu
* Via editor menu action, ability to pickup a shopkeeper with all its data to a shop creation item, and then place the shopkeeper via that item somehwere else: Easy to use, difficulty to implement (requires storing lots of custom data in the item.. unsupported by bukkit, prone to issues, ..), requires extending the editor menu
  * One problem with this is that the amount of data stored inside an item / data send to and from clients is limited.
  * Another alternative could be to create an item that stores the uuid of the shopkeeper. The item can then be used to move the shopkeeper. However, creating an item and keeping the shopkeeper could be abused to spawn unlimited amounts of the move item.

Related questions:
* How to handle player shop chests? Only allow re-location in certain radius around the chest? -> Yes
* Some servers manage markets by using pre-setup player shopkeepers. These servers may not want players to move their 'temporarily owned' shops. Ideally, this will be replaced by a proper shopkeeper renting system in the future, but for now a setting might be required to disable the moving of shopkeepers.

**Comment by blablubbabcDEV** [comment]
**Originally commented by bingoberraz (Dec 30, 2015):** 

This is very much needed!

**Comment by blablubbabcDEV** [comment]
**Originally commented by Ritricity (Mar 15, 2016):** 

This is very needed.

**Comment by blablubbabc** [comment]
Possibly related, if this were to be implemented the complicated-but-nice way by picking up the shopkeeper with all its data inside an item and being able to use that to place the shopkeeper somewhere else: https://github.com/Shopkeepers/Shopkeepers/issues/480

**Comment by blablubbabc** [comment]
v2.16.0 has added a new editor option that allows the shopkeeper to be moved.
