### ISSUE TITLE
Remove shop if it isn't used by the owner for X days

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#367]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/366

**Originally posted by Dutch_Boy (Mar 5, 2016):** 

What is the enhancement in mind? How should it look and feel?Please provide any additional information below.Can you add 2 more options?1. Shops will be deleted after x amount of time/min/days if a shop owner doesn't do anything with his/her shop.2. The plugin sends a message x amount of times a min/day/week to the player that one of his/her shops is empty. Or every time he/she comes online on the server.i didnt check the config/plugin if this option is already there :) Eating and thinking about things i like to have :)Copied from the plugin chat.

**Comment by blablubbabc** [comment]
There already exists a setting to remove shops for players which are inactive (didn't visit the server for x days). It's slightly different than this suggestion though, as this would only check if the shopkeeper was abandoned by the player.

Closing this though, as this looks like being a duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/359
