### ISSUE TITLE
Allow setup of more than 8 trades

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#446]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/445

**Originally posted by blablubbabc (Nov 17, 2016):** 

This could be achieved by added buttons to the editor window which allow scrolling through different pages of setup trades.

**Comment by blablubbabcDEV** [comment]
**Originally commented by Roadhog380 (Feb 12, 2017):** 

I second this. Please let this be added.
            Edited Feb 12, 2017

**Comment by blablubbabcDEV** [comment]
**Originally commented by CloudeLecaw (Mar 6, 2017):** 

its just some little magic, from an other developer that helped me out with this a bit,Â toÂ have the size from current 8 item up to 17 Items ;)
(a modified version 1.81) maybe Version 1.82 will have this doublechest GUI too *g* to enlange from max. 8 to 17 trades :)
To have more then 17 items, i think it needs a bit more changing of the code.
Maybe blablubbabc create the Doublechest as first step in the next version so u have 17 item too ;)
Â 
            EditedEdited Mar 6, 2017

**Comment by mikroskeem** [comment]
Any update on this?

**Comment by blablubbabc** [comment]
This will be part of the next update.
If anyone wants to try this out and report any issues, a snapshot build is available here: http://nexus3.cube-nation.de/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.5.1-SNAPSHOT/Shopkeepers-2.5.1-20190302.033007-3.jar

**Comment by blablubbabc** [comment]
Check out v2.6.0
