### ISSUE TITLE
Annoying issue

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#476]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/536

**Originally posted by onlytrikop (Oct 7, 2017):** 

When i added the permissions for the players THEY could not trade with them, it just came a message that told you that you didnt have permission to trade with this shopkeeper. This comes to all of my shopkeepers

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Oct 8, 2017):** 

Debug your permissions setup. Usually permissions plugins have a command to check if a player has a certain permission node.
Â 
By the way, which permission plugin are you using?

**Comment by blablubbabc** [comment]
I am closing this ticket as no further information was provided. The issue is very likely related to the permissions setup or the permissions plugin.
