### ISSUE TITLE
/shopkeeper give 1 [player]

### ISSUE THREAD

**Issue by downspath** [Shopkeepers/Shopkeepers#479]
Please add this command, it is Realy hard to create a shopkeeper "coin/spawnegg" that is givable with a command.
and if possible: add a glowing option in the config.

**Comment by DTS-MC** [comment]
I have been looking at the code for this and I cannot even find an insertion point to give the item 
let alone where the egg is created

**Comment by blablubbabc** [comment]
The shopkeeper creation items only use display name, lore, and optionally, for spawn eggs, the mob type.
There should be plenty of plugins being able to create and give the item (ex. essentials). And even with vanilla minecraft commands it is possible create and give those items. Maybe it would be easier to just add an explanation for the vanilla command for creating those items to the documentation?

/minecraft:give player spawn_egg 1 0 {display:{Name:Shopkeeper,Lore:[Creates,Shops]},EntityTag:{id:villager}}

Creates a spawn egg with display name 'Shopkeeper', lore [Creates, Shops] and spawn-egg mob type 'villager'.

**Comment by blablubbabc** [comment]
The next version will include a give command.

**Comment by blablubbabc** [comment]
Check out v2.6.0
