### ISSUE TITLE
Players Permission

### ISSUE THREAD

**Issue by sjwSteven** [Shopkeepers/Shopkeepers#482]
As an op, I created a shop but normal player cannot trade/buy/sell stuffs with me. If I deop myself, I also don't have the permission to use the command of creating shopkeeper. How can I let other players have the permission to trade with me? Do I need to install other plugins?

**Comment by sjwSteven** [comment]
Bukkit v1.12.2

**Comment by blablubbabc** [comment]
Your players should have the trade permissions, as well as the permission to create player shops, by default. If you need finer control over permissions, you can use a permissions plugin. But trading and player shop creation should work by default already, without any permission plugin.

Is this a spigot 1.12.2 server? Are you using any plugins which might interfere (permissions plugin, plugin manager plugins, ..)? Would you mind setting up a fresh spigot server with only shopkeepers running (no other plugins) and try to reproduce your issue there?

**Comment by blablubbabc** [comment]
Just checked to be sure, and permissions work for me by default. So it has to be something related to your setup.
