### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by madtomic** [Shopkeepers/Shopkeepers#486]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SK Parent Pom ...................................... SUCCESS [  1.051 s]
[INFO] SK-API ............................................. SUCCESS [02:53 min]
[INFO] SK for v1_8_R1 ..................................... SUCCESS [ 25.359 s]
[INFO] SK for v1_8_R2 ..................................... SUCCESS [  2.764 s]
[INFO] SK for v1_8_R3 ..................................... FAILURE [  8.192 s]
[INFO] SK for v1_9_R1 ..................................... SKIPPED
[INFO] SK for v1_9_R2 ..................................... SKIPPED
[INFO] SK for v1_10_R1 .................................... SKIPPED
[INFO] SK for v1_11_R1 .................................... SKIPPED
[INFO] SK for v1_12_R1 .................................... SKIPPED
[INFO] Shopkeepers ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:31 min
[INFO] Finished at: 2017-12-25T09:12:14-05:00
[INFO] Final Memory: 28M/392M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sk-v1_8_R3: Could not resolve dependencies for project com.nisovin.shopkeepers:sk-v1_8_R3:jar:v1_8_R3: Could not find artifact org.bukkit:craftbukkit:jar:1.8.4-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sk-v1_8_R3

**Comment by blablubbabc** [comment]
You need to have all craftbukkit versions required by shopkeepers installed in your local maven repository.
Run the spigot BuildTools with the argument --rev 1.8.4 to let it build and install craftbukkit 1.8.4 on your pc, and then try to build shopkeepers again.
Repeat the same for any other craftbukkit versions you are missing.
