### ISSUE TITLE
how to disable Shopkeepers Create when i use villager spwen_egg.....

### ISSUE THREAD

**Issue by yuyuecraft** [Shopkeepers/Shopkeepers#487]
i cannot found any feature in config.myl.....

i just wanna make server owner shopkeepers
i didnot need player shopkeepers

how to fix it

thanks!

**Comment by blablubbabc** [comment]
You need to remove the player-shopkeeper related permissions (shopkeeper.player, etc.) by using a permissions plugin and configuring it accordingly. See the wiki for the permission nodes that are granted to everyone by default.
