### ISSUE TITLE
Players Can Delete "Fore Hire" Shops?

### ISSUE THREAD

**Issue by doitliketyler** [Shopkeepers/Shopkeepers#494]
Hello. So I set up some "For Hire" shopkeepers and players can just delete them even though they don't belong to them which shouldn't be happening. I've revoked all the permissions except to hire and to trade with shopkeepers but no change. Thoughts?

I'm on the latest version of  PaperSpigot 1.12.2 and using Shopkeepers v1.86

**Comment by blablubbabc** [comment]
This is intended behavior: The 'shop hiring'-feature actually is a 'shop buying'-feature. The name 'hiring' might cause you this confusion. So the shop actually changes owners when being 'hired'.

There is currently no feature which would allow you to rent shops to your players. There is an open ticket for this though: https://github.com/Shopkeepers/Shopkeepers/issues/3

This looks like a duplicate to me to this ticket: https://github.com/Shopkeepers/Shopkeepers/issues/491
