### ISSUE TITLE
Entity Spawn Eggs Not Keeping "Tags" Upon Shopkeeper Restart.

### ISSUE THREAD

**Issue by rikulaxion1993** [Shopkeepers/Shopkeepers#497]
Server Version Spigot 1.12 (git-Spigot-596221b-9a1fc1e)
Shopkeepers v1.86

Spawn Eggs don't keep NBT "Tags" for when Shopkeeper restarts. (Server Restarts) But function As intended if the shop is bought from after being made before a restart.

Replication:
Create a Spawn egg with Desired tags.
/give @p spawn_egg 1 0 {EntityTag:{id:"minecraft:polar_bear",Tags:["Small"]}}
You can test to see if the spawned Entity correctly has its tags by teleporting it around.
/tp @e[tag=Small] ~ ~10 ~
The Above will teleport Correct entities up 10 blocks.
When the Spawn Egg is then put into a shop it keeps **Tags:["Small"]** and can be purchases for use of desired effects. (Teleporting these will still work.)
Upon a server restart the Enitity loses the tags and is no longer effects by commands that target enitities with the desired tag. (Teleporting No longer works.)

**Comment by blablubbabc** [comment]
I cannot reproduce this on the latest version of spigot. Try updating your server, they fixed this in spigot october last year (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/9ab758c7b608854ec658450227c2a17e51845de5)

**Comment by rikulaxion1993** [comment]
Thanks for the quick response, I have update my server respectively and everything is in working order!
