### ISSUE TITLE
Villager spawns when shopkeepers chest is too far away

### ISSUE THREAD

**Issue by R0bstar** [Shopkeepers/Shopkeepers#498]
I'm running version 1.86 and have the default setting "max-chest-distance: 15". I tested what would happen when you try to use the villager spawning egg more than 15 blocks away, and what happens is that it just spawns a villager. Not a shopkeeper, but a villager.

Now that would be a very easy source of villagers (cause I'm selling the eggs for a reasonable price) so I had hoped that instead nothing would happen and you'd keep the egg in your hand.

Is that possible?

**Comment by blablubbabc** [comment]
Yes, there is a configuration option 'prevent-shop-creation-item-regular-usage', see here: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration
