### ISSUE TITLE
How can I use symbol & and russian letters in Shopkeeper's name?

### ISSUE THREAD

**Issue by TheAnonim** [Shopkeepers/Shopkeepers#501]
How can I use symbol & and russian letters in Shopkeeper's name?
Can I change option in config?

Spigot 1.10

**Comment by blablubbabc** [comment]
You can edit the regular expression in the config, which is used to check if a given name is valid. The setting is called 'name-regex' and there is some explanation to it in the wiki: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration

There is an example given which enables the '&' character (and by that the color codes).

To get russian (cyrillic) letters working you can try adding '\p{IsCyrillic}' inside the regex.
