### ISSUE TITLE
Setting Name?

### ISSUE THREAD

**Issue by thewholepie** [Shopkeepers/Shopkeepers#503]
The names that I add (Kit, Starter Kit, Welcome) are all invalid. Help!

**Comment by blablubbabc** [comment]
Are you talking about shopkeeper names?
What do you have configured in the config for the setting 'name-regex'?

If you cannot get to to work with the default config:
* Try whether you also have this issue without any other plugins (maybe one is interferring with the chat handling of shopkeepers)
* What server version are you using? Try using the latest version of spigot.
* Make sure that you don't use any client mods while testing this issue.
