### ISSUE TITLE
Restore Expired Hired Shops to "For Hire" State

### ISSUE THREAD

**Issue by yurisuika** [Shopkeepers/Shopkeepers#504]
This is a request to modify an existing feature of Shopkeepers.

I am using the Set For Hire feature to place around 35 player shops in my server's spawn, charging a certain amount of our physical currency to hire.  I have the shops set to expire after a certain amount of time of inactivity.  The problem I face with this is that, after a shop expires, I have to both find out about it and then add back in the shop.

The feature that I would like would be an option to have these expired shops restore to their original For Hire state instead of being deleted.

Thank you.

Minecraft 1.12.2
PaperSpigot-1.12.2-b1462.jar
Shopkeepers v2.1.0-beta

**Comment by blablubbabc** [comment]
The current 'for hire' feature really means 'for sale', permanently changing the shop's owner.
By 'expiration' you probably mean the current 'remove shopkeeper after x days of inactivity'-feature.

Anyways, this seems to be a duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/3
