### ISSUE TITLE
Shopkeepers configuration bug

### ISSUE THREAD

**Issue by Noob1917** [Shopkeepers/Shopkeepers#507]
Configuration node prevent-shop-creation-item-regular-usage: true doesn't working!
I want to protect shop creation from players, but they anyway can create shops using spawn egg!

**Comment by blablubbabc** [comment]
This setting is for preventing 'regular usage'. For spawn egg that means that it doesn't spawn mobs anymore.
There is currently no option to disable the creation of shops via item, however you can achieve that by simply changing the shop creation item to something that players will never be able to get (for example an item with very specific lore).
If you want to prevent players from creating shops at all, you can also use a permissions plugin and remove the corresponding permissions (see here for all permissions: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Permissions).

**Comment by Noob1917** [comment]
can I ban this through plugins PermissionsEx by setting - -shopkeeper.hire

**Comment by blablubbabc** [comment]
That will remove the hiring permission. To prevent players from creating shops, you will have to remove `shopkeeper.player`

**Comment by Noob1917** [comment]
- -shopkeeper.player ?

**Comment by blablubbabc** [comment]
Yes.

**Comment by Noob1917** [comment]
is it possible to make merchant shopcepers of plugins Citizens ? and if can be the as ?

**Comment by blablubbabc** [comment]
See the wiki on that: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Citizen-Shopkeepers
