### ISSUE TITLE
Wont show up in plugins folder

### ISSUE THREAD

**Issue by 73v3nDr4g0n5** [Shopkeepers/Shopkeepers#510]
It decides to not create a folder for itself in the plugins folder, we have the latest spigot and latest shopkeeper, it was working a couple days ago.

**Comment by blablubbabc** [comment]
I cannot reproduce the issue: I tested with both v2.2.1 on Spigot 1.12.2, and with 2.3.0 on Spigot 1.13-pre7, and in both cases it would generate a 'Shopkeepers' folder with the default config.yml if none existed yet.

Maybe something prevented Bukkit from creating the folder and the default config.yml (I'm no expert in that, but this might be the case if your OS holds any kinds of locks required for that, or if the server process doesn't have the required write permissions for the plugins folder, etc.). Check your log if it contains any errors in that case, any make sure that you don't have any other processes active that might currently be accessing/locking the plugins folder (backup programs, file explorer, etc.).
