### ISSUE TITLE
Players are unable to purchase anything from selling shopkeepers

### ISSUE THREAD

**Issue by Hundr** [Shopkeepers/Shopkeepers#511]
* Spigot 1.13 (latest build) and Shopkeepers 2.3.0.

Players are unable to purchase anything from selling shopkeepers. I have the option set to purchase from own shopkeepers turned off for testing: (Same result when set to true.)
> prevent-trading-with-own-shop: false

The tool-tip for the currency types shows a blank where the item name would be displayed.
Other shopkeeper types are working.

**Comment by blablubbabc** [comment]
I assume this to be caused by some change in behavior inside Spigot. I created a Spigot ticket here: https://hub.spigotmc.org/jira/browse/SPIGOT-4177

**Comment by blablubbabc** [comment]
Please try again on the latest build of Spigot.

**Comment by Hundr** [comment]
Yes working now. Thank you for your fast response and helping get this resolved.
