### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by JTGgamer** [Shopkeepers/Shopkeepers#514]
## When reporting an issue:
* Provide the versions you are using of Minecraft, Spigot and Shopkeepers.
Minecraft: 1.13
Spigot: The Latest Version Available on GetBukkit (I don't know exactly).
* Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.
The villagers are just normal villagers and you cannot edit their trades.
Error in pastebin:
https://pastebin.com/FkJE68jp
* If possible, include **step-by-step instructions** on how to reproduce the issue on a fresh Spigot server.
I just installed it and it happened.

**Comment by blablubbabc** [comment]
Update your Spigot server to the latest version.
