### ISSUE TITLE
Idea: time between 2 trades with same villager

### ISSUE THREAD

**Issue by JohOply** [Shopkeepers/Shopkeepers#516]
Hi guys,

Like the title explain, i have an idea which is to add an option to set time on some villager. This will be use to limit frequency of trades for avantageous trades for instance.

Cheers

**Comment by JohOply** [comment]
I am not sure if it was understanding in my message, I speaked about "villager" from ShopKeepers and not vanilla villager

**Comment by blablubbabc** [comment]
Yes, I understand. Your request seems to be similar to https://github.com/Shopkeepers/Shopkeepers/issues/403.
