### ISSUE TITLE
lastest jar build doesn't work on 1.13 

### ISSUE THREAD

**Issue by jordanwilliams1** [Shopkeepers/Shopkeepers#518]
Latest jar build doesn't work on 1.13 server (latest build of paperspigot)

**Comment by blablubbabc** [comment]
Can you describe your issue and attach your server log (containing the startup of Shopkeepers)?

Anyways, it works on the latest build of Spigot. So maybe Paper isn't up-to-date yet with Spigot, or they introduced some incompatible difference.. (both things they would have to fix).
