### ISSUE TITLE
React showing Shopkeepers is causing a spike

### ISSUE THREAD

**Issue by lukeeexd** [Shopkeepers/Shopkeepers#519]
Paper 1.13.1 latest Shopkeepers version. React shows Shopkeepers is causing a spike. here is timings report

https://timings.aikar.co/?id=c1b203b0fa364c6ba0168286193266f1

**Comment by blablubbabc** [comment]
There has been some change inside Spigot to call a few **less** BlockPhysicsEvents in some situations, requiring Shopkeepers to check neighboring blocks for all physics events now. I don't know how big of an impact that it, but overall the checks should still be quite lightweight individually. The biggest issue is still that physics updates can happen quite frequently, especially if you have contraptions involving lots of  or constantly running pistons, redstone, flowing water, ..

**Comment by blablubbabc** [comment]
Closing this as no further information has been provided that might point to a specific issue in Shopkeepers. If you happen to have timings with sign shopkeepers disabled as as comparison, then let me know (out of interest).
