### ISSUE TITLE
I am unable to access the Maven Repository

### ISSUE THREAD

**Issue by frost-byte** [Shopkeepers/Shopkeepers#524]
## When reporting an issue:
Spigot: 1.13.1
ShopKeepers: Latest Version

Whenever I try to build my project, which uses ShopKeepers as a dependency, maven continues to spit out
errors for the repositories at http://nexus3.cube-nation.de

It seems like they're no longer accessible?

**Comment by blablubbabc** [comment]
Seems like its accessible again currently. Can you check if everything works again for your as well?
The repositories are not hosted by me, so if they are down at some point they might be doing updates or similar currently.
