### ISSUE TITLE
Chest bug 1.13.1

### ISSUE THREAD

**Issue by oxycclock** [Shopkeepers/Shopkeepers#525]
## Preliminaries:

* **Shopkeepers version:** 2.4.1
* **Spigot version:** This server is running Paper version git-Paper-262 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`git-Paper-262`**) with the latest version of Shopkeepers (currently **`2.4.1`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Well, when I place 2 simple chest next from each other, the shopkeeper uses both chests. 

Include:

The Shopkeeper uses 2 chest
1 - Place 2 chests next from each other
2 - Assign 1 chest to a Shopkeeper
3 - You can't assign the other chest to another shopkeeper.
https://ibb.co/b2fbZz

**Comment by blablubbabc** [comment]
I am aware of this, but hadn't yet the time to look into changing this.

There is already another ticket open for this, so I will close this as 'duplicate': https://github.com/Shopkeepers/Shopkeepers/issues/383 (I adjusted the title of that ticket to incorporate the situation of non-connected chests that was added with MC 1.13)

**Comment by blablubbabc** [comment]
I made some changes which should 'fix' / improve this. See my comment over at the other ticket: https://github.com/Shopkeepers/Shopkeepers/issues/383#issuecomment-422563826

Please try this snapshot and let me know if can find any issues with it.
