### ISSUE TITLE
Monster shopkeeper counts as mob if you try sleep

### ISSUE THREAD

**Issue by lukeeexd** [Shopkeepers/Shopkeepers#527]
If you try sleep in a bed with an evoker shopkeeper close by it wont let you because it counts it as a mob

**Comment by blablubbabc** [comment]
Seems to affect all monster shopkeepers (edited the title accordingly).

Unfortunely I don't think there is currently a way for me to change this. Minecraft simply checks whether there are monsters nearby. There is no way for me to tell it to ignore specific entities there.

**Comment by blablubbabc** [comment]
I have created a feature request ticket over at Spigot for this: https://hub.spigotmc.org/jira/browse/SPIGOT-4395

**Comment by blablubbabc** [comment]
Fixed in v2.5.0
