### ISSUE TITLE
I'm using a team /Shopkeepers And an error occurs. Is it possible to fix this?

### ISSUE THREAD

**Issue by FrukTik** [Shopkeepers/Shopkeepers#528]
* **Shopkeepers version:** `<Shopkeepers v2.2.2>`
* **Spigot version:** `<patched_1.13.1.jar:git-Paper-304>`
---
I'm using a team /Shopkeepers
And an error occurs. Is it possible to fix this?
https://pastebin.com/raw/HihTqh5p

**Comment by blablubbabc** [comment]
You are using Shopkeepers v2.2.2. This version does not support MC 1.13+ and has therefore disabled itself (it should mention that in your server log during startup.
Use Shopkeepers version 2.4.1 instead, see https://dev.bukkit.org/projects/shopkeepers/files

**Comment by FrukTik** [comment]
спасибо


пт, 28 сент. 2018 г. в 14:00, blablubbabc <notifications@github.com>:
