### ISSUE TITLE
MMOItems Incompatibility

### ISSUE THREAD

**Issue by Flirtey** [Shopkeepers/Shopkeepers#529]
## Preliminaries:

* **Shopkeepers version:** `V2.2.2
* **Spigot version:** `<The final most updated spigot for 1.12.2>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was able to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`Latest 1.12.2 release`**) with the latest version of Shopkeepers (currently **`V2.2.2`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* When creating the items that are to be traded in the shop, custom items from MMOitems work, except for playerheads. Gyazos show this:
WORKS WITH CUSTOM SWORDS ETC: https://gyazo.com/5a7ab01eba4eedcd40b7058f198763b0
DOES NOT WORK WITH CUSTOM PLAYER HEADS: https://gyazo.com/98fcd0e62aa02a7634f68ebfa955586e
* Step-by-step instructions on how to reproduce the issue: If using MMOitems just simply place them into the gui.
* Observed behavior: Trade does not work.
* Expected behavior: Trade would work?
* If items with special attributes are involved: Include instructions on how to create those items: Using MMOItems you create a material that is a SKULL_ITEM with a Data value of 3 and set the custom skin texture. Also has several NBT tags from MMOItems but the same nbttags and crazy custom items work with swords/armor.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output: Not Relevant, no logs or errors are thrown.
* If modified from default: Plugin configurations: Has not been touched. Fresh startup,
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by Flirtey** [comment]
There is literally a setting I skipped. Forget this :D

**Comment by blablubbabc** [comment]
What setting exactly are you refering to?

Anyways, head items might not properly work, especially if custom nbt data (like custom texture data) is involved. I do not know the details right now and if this might actually be an issue, but if I remember correctly, Spigot might be doing some kind of (async/delayed) 'normalization' or 'profile updating' at some point for head items (maybe this: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0081-Convert-player-skulls-async.patch), which causes its internal nbt data to change. And by that the head items might no longer match the items required for the trading.
If you are having issues with head items, it _might_ be useful to try if vanilla villagers (created via custom summon command to contain a trade for those head items) have the same issue.
But in any case this, if there are issues related to skull items then this would probably be something for Spigot to look into.
