### ISSUE TITLE
Shopkeepers Trade exit

### ISSUE THREAD

**Issue by NotchSummer** [Shopkeepers/Shopkeepers#531]
## Preliminaries:

Shopkeepers version : 1.7.10 all version, tried latest one too
Cauldron version : cauldron-1.7.10-1.1388.1.0-server`
---

## Shopkeeper not working:

The shopkeeper setup works good and behaves great until I need to trade with it. The trade never happens and the menu exits as soon as I click an item in my inventory. Some other non-op players says that it crashes their Minecraft.

When the trade doesn't happen, when the exit of menu appears. There are no console logs. 
I have attached a gif regarding this issue.
https://gifyu.com/image/TkkP

Thanks in advance!!

**Comment by blablubbabc** [comment]
Shopkeepers is not compatible with cauldron. Cauldron seems to have behavioral differences compared to craftbukkit/spigot, that cause Shopkeepers to not be able to identify the open inventory (not able to make sure that the correct inventory is open when you click something), and therefore closing it.
