### ISSUE TITLE
Shops stopped working randomly

### ISSUE THREAD

**Issue by lukeeexd** [Shopkeepers/Shopkeepers#532]
latest Paper version, latest shopkeepers version. Everyones shops not working https://www.youtube.com/watch?v=kEAgP3cRCoc

also quote from a player:

"I have a shop glitch where my villagers price for items goes back to a barrier block. I'm not sure what makes it return to a barrier block, i.e. players buying something, or time. All three villagers had this problem but now only the last two which are shown. I've resetted the villager, swapped through what their actions are and what they look like, still have the prob. My guess is they're too close with their chest paths crossing one another. Also guessed that I had them selling items beyond the 9th slot which might of caused prob and it seemed to work temp. but reverted back to the problem."

**Comment by blablubbabc** [comment]
I need something more specific that helps tracking down the issue.

* Can you please try to reproduce your issue with the latest version of Spigot?
* Did you perform any updates your server or plugin(s) / configurations? If yes, what did you update?
* Can you provide reproduction instructions? How can I reproduce this on a fresh spigot or paper server? (ie. save data for a shopkeeper that is affected, instructions on how to create the items involved in case they are non-default items)
* Can you check your console log for useful information?
  * Any errors? Especially on startup.
  * If you enable debug mode and try the trade, what does it print to the console?
* Do you run any plugins that might affect items? Either directly, or for example 'hidden' (ie. protocol hacks).

Regarding the issue of that player:
Can you provide the save data for the affected shopkeepers and instructions on how to reproduce the issue (ie. which trade is affected, which items are tried to be traded)?

**Comment by lukeeexd** [comment]
Just tested myself and its working. I'm going to get the player to try with debug set to true

**Comment by blablubbabc** [comment]
I also just tested the latest paper version and had no issues.

**Comment by lukeeexd** [comment]
You can close
