### ISSUE TITLE
Shopkeepers error (cant load plugin)

### ISSUE THREAD

**Issue by AntoLuMeju99** [Shopkeepers/Shopkeepers#534]
## Preliminaries:

* **Shopkeepers version:** `2.4.1` 
* **Spigot version:** `TacoSpigot 1.8.8`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

When i start the server, i got this error: https://pastebin.com/iDN2qUjQ

**Comment by blablubbabc** [comment]
v2.4.1 of Shopkeepers only supports Spigot 1.13.x upwards.
You may try some older version of shopkeepers (ie. v2.2.1). However, only Spigot is tested and supported by me, so this might not work with "TacoSpigot" either.
