### ISSUE TITLE
Shops spawn floating and one derectional

### ISSUE THREAD

**Issue by Tolken5** [Shopkeepers/Shopkeepers#537]
So this is my first time ever reporting any kind of problem for a plugin, I hope I do this right, my problem is when I create a shop (right click chest then right click block) it pops up, works and is good, OTHER than the fact that they are floating half a block in the air and are stuck facing south .... everything functions properly, just that one ... or two things are wrong ....

**Comment by blablubbabc** [comment]
Which plugin version are you using? Try using the latest version of the plugin.
Which server version (and brand) are you using? Try using the latest version of spigot.
Which type of mob are you using for the shopkeeper? Try using villagers.
Have you changed any settings from the default configuration? Make sure you don't have 'use-legacy-behavior' enabled, or altered any other mob behavior or gravity related settings. Try with the default config.
Have you checked your server log for errors? If there are errors, those are very likely resolvable by updating your server to the latest version of spigot.

There are several combinations to the above answers that can result in the described behavior. But this is most likely either solvable by updating your server, or it's 'intended behavior' (fallback mode for certain mob types that have issues, especially when using 'legacy-behavior').

**Comment by Tolken5** [comment]
So yeah id like to apologize for bothering you when the solution was so
simple ... normally use my head more and solve things myself but for
whatever reason, I didn't think at all. I changed the version a couple
times and found one that worked. Thank you for your quick reply and again I
am sorry for wasting your time.

**Comment by blablubbabc** [comment]
So, what was the issue? An incompatible server/plugin version?

**Comment by Tolken5** [comment]
yeah, I'm guessing so. I had your newest version and had the problem, I
tried your first 1.13 version and it is working now.

**Comment by blablubbabc** [comment]
Okay. Since you are are using MC 1.13 anyways already, you could also simply update to the most recent Spigot build and get all the bug fixes and improvements the new server and plugin versions offer.
