### ISSUE TITLE
Had TPS drop, shopkeepers was mentioned in timings but I don't even have that plugin anymore just the folder?

### ISSUE THREAD

**Issue by axemwa** [Shopkeepers/Shopkeepers#541]
Had TPS drop, shopkeepers was mentioned in timings but I don't even have that plugin anymore just the folder? Is it possible there's still some residual files somewhere?
https://timings.aikar.co/?id=9da780a0d2564f51a3c89a313c9b24b3
![image](https://user-images.githubusercontent.com/37608633/51768221-a19b4d80-212f-11e9-9493-0dbd457afe3c.png)

**Comment by blablubbabc** [comment]
According to the timings, the plugin was active at that time. Make sure you restart the server after removing the plugin file.
If the plugin stays active, then maybe you have renamed the plugin file to something else in the past, mybe by accident.. In that case you will have to go over your plugins one-by-one, unzip them and investigate their contents to verify whether or not a particular jar file is actually the Shopkeepers plugin.

Regarding the lag: Not sure what's going on there: The code that is causing lags according to that timings report isn't doing anything heavy at all..(it only schedules a task). I also can't reproduce this on spigot. If you want help with that, then please try with an up-to-date Spigot server and let the timings run for some time. Ideally also provide some minimal setup instructions for how to reproduce this (minimal number of required other plugins).

**Comment by axemwa** [comment]
Deleting the Shopkeepers folder seems to have fixed it, hmm strange

**Comment by blablubbabc** [comment]
> if the shopkeepers jar was there and re-named it would have made a new folder but it didn't

It uses the plugin's internal name for creating the folder. The name of the jar file has no influence.

Maybe only a restart was required.

**Comment by axemwa** [comment]
thats wat i thought and nah ive restarted my server many times, it was only on the last restart thjat I noticed shopkeepers was there. But deleting the folder seems to have stopped it from appearing in timings for now so thanx for ur help anyway, it'z fixed :)

**Comment by axemwa** [comment]
thats wat i thought and nah ive restarted my server many times, it was only on the last restart thjat I noticed shopkeepers was there. But deleting the folder seems to have stopped it from appearing in timings for now so thanx for ur help anyway, it'z fixed :)
