### ISSUE TITLE
Add a command to edit a shop, without having to sneak/click

### ISSUE THREAD

**Issue by frost-byte** [Shopkeepers/Shopkeepers#542]
I use the sneak + click functionality for something else, I was wondering if it would be possible to add a command that would let me edit the trades.

**Comment by blablubbabc** [comment]
Out of interest: Why exactly isn't sneak+right-click not working for you, what is it conflicting with?

Regarding the command: I could probably add a "/shopkeeper edit [shop-id]" command.

**Comment by blablubbabc** [comment]
> I'm not edit item on shop npc

Please create a separate ticket if you have issues with editing shops. And provide step-by-step instructions on how to reproduce your issue.

**Comment by bomman20real** [comment]
How to do at
I don’t know code

**Comment by frost-byte** [comment]
My own plugin uses the same interaction for another Trait for my Citizen NPCs.  I figured that with the existing command to remotely open a shop inventory that it would be possible to also edit one via a command

**Comment by blablubbabc** [comment]
This will be part of the next update: https://github.com/Shopkeepers/Shopkeepers/commit/8cd544b6c7eeccf7eed5e94f5214d67d7233a62b
Until then a snapshot is available here for testing: http://nexus3.cube-nation.de/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.5.1-SNAPSHOT/Shopkeepers-2.5.1-20190217.002042-1.jar

**Comment by blablubbabc** [comment]
Check out v2.6.0
