### ISSUE TITLE
Feature request: more than trading emeralds

### ISSUE THREAD

**Issue by LadyHaley** [Shopkeepers/Shopkeepers#546]
Hey, I was wondering if you could add some functionality that would allow players to trade more than Just emeralds for items. None of my players want to trade in emeralds, since they are such a huge pain to get. If that functionality already exists for players, how do they get it?

**Comment by LadyHaley** [comment]
Or make it that when a player Shift Clicks a spot, it toggles the material type through a list thats editable through a config file

**Comment by blablubbabc** [comment]
You can already change the currency item to something else in the config. Maybe change it to something more common (like gold ingots?), and then provide an admin shopkeeper at the spawn that allows exchanging between emeralds, gold, etc. On the other hand: You can of course do it the other way around as well of course, providing your players the means to exchanging other items for emeralds at a common spawn/market area.

If you or your players want to setup trades with arbitrary items: It is possible to setup 'trading' shopkeepers. Though, they are a bit more comlicated (see the wiki for how to do that).

Regarding toggling through different currency items: There is already a ticket open with some thoughts on this, so I will close this as duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/502

**Comment by LadyHaley** [comment]
I checked the wiki and it worked once for me, then any further trade signs I tried to make I just got a "You have to select an admin shop type" msg

**Comment by LadyHaley** [comment]
I have create-player-shop-with-command set to true in my config

**Comment by LadyHaley** [comment]
I found what caused the issue, It only does it when I have a chest in a corner

![image](https://user-images.githubusercontent.com/3754909/52459446-45b5d780-2bb9-11e9-9017-1e2a1d65442a.png)

![image](https://user-images.githubusercontent.com/3754909/52459454-4ea6a900-2bb9-11e9-9df2-512c20e4eb1e.png)

**Comment by blablubbabc** [comment]
I just tried and placing the chest in the corner is not the issue (works fine for me).
I assume that you might be targeting some other block and not the chest itself. In that case it will attempt to create an admin shopkeeper.

**Comment by LadyHaley** [comment]
They are not taking up space where the sign would go.
In any case, I also found another issue, the plugin doesnt seem to handle the new way chests work properly

![image](https://user-images.githubusercontent.com/3754909/52459903-e60cfb80-2bbb-11e9-903c-310cec376b04.png)

**Comment by LadyHaley** [comment]
I also cannot put any symbols in shop names

**Comment by blablubbabc** [comment]
Which version of shopkeepers are you using? Make sure that you are using the latest, since there have been some changes in the past regarding some of the behavior you describe.
