### ISSUE TITLE
Cant edit keeper inventory

### ISSUE THREAD

**Issue by Ehwone** [Shopkeepers/Shopkeepers#547]
Hey, i'm trying to build a litle rp server, but i need some NPC to help when people are not here, i've tried Citizen but fo no reason it just dont work at all, so i try to use ShopKepper, but i have a big problem, i can make them spawn, rename them, delete them, but i cant edit the inventory of the keeper, when i try to pick up an item or shift click, it just go back to my inventory.

I've checked the plugin and nothing seem wrong in it, could it be another plugin who block the permission ?

**Comment by Ehwone** [comment]
Step by step:

-/shopkeeper (a villager appear)
-sneak+clic to access the edit menu
-click on the name tag
-type a name
-change the outfit of the npc

and now or even before i try to put things in his inventory but things continu to come back in my hand.

I've found another way but still got a problem,
i've used the /adminshop create Farmer
all the buy/sell is setup, but after a restart server, some of the npc lost all the setup.


I have a lot of issues with my plugins, i'll need to make a lot a request on this site :/

**Comment by blablubbabc** [comment]
* What type of block did you target when creating the shopkeeper with the command (make sure you have **not** targetted a chest, in order to create an admin shopkeeper and not a player shopkeeper).
* The console mentions that you are trying to use shift-click inventory actions. Try regular clicks.
* /adminshop create Framer is not a command of this plugin.
* "all the buy/sell is setup, but after a restart server, some of the npc lost all the setup." So, the setup of player shopkeepers work?
* Make sure that you are testing with the latest version of Spigot. If nothing helps, also try reproducing the issue without other plugins.

**Comment by Ehwone** [comment]
Oh the video link is not clickable :/
In the video whe can see that i was pointing at a regular grass block, i try to put item in his inventory buy it didnt work, i use normal click and shift clicks to show that nothing work.
Ill need to try to create one when looking at  a chest, player shop would be usefull too.

Im in 1.13 under bukkit, i've tried 1.13 spigot to see if citizen would work, but its still broken

I dont know from which plugin rhe adminshop came from, but it work like shopkeeper, but you can just buy/sell and the npc can ger killed and mooved by zombies, that what happened when i tought one of the npc disapeared, its was just a adminshop, bad plugin, my bad.

Ive tried without some other plugins that use npc, but stoll broken

**Comment by blablubbabc** [comment]
"The video is not available".

Regarding clicking not working: Can you try to reproduce it without other plugins on a fresh and up-to-date Spigot server?

**Comment by Ehwone** [comment]
My bad, it was a private video, should be working now
I'll try to save all my files and restart with just this one, just for information on the server i use those plugins:
world edit
lightchatbubbles
serialkey
permissionsex
ultimate_economy
vault
thirst
worldguard
brewery
citizens
shopkeepers
areshop
essentials
coloredgroups
jobs
commandnpc
dtltraders

**Comment by blablubbabc** [comment]
Also make sure you are testing with the latest Spigot server, just to rule out this to be the issue.

**Comment by Ehwone** [comment]
Ok so i just restart the reserv with just Shopkeeper, it works
So i put all the plugins one by one and restart it and try it every time
Took some time, the last one was the problem x)
Ultimate_economy was the problem, so i need to find another economy plugin, the adminshop was pretty usefull, it would be good to be able to spawna  npc who can give you money when you sell something.

Btw my citizen is still not working, stay red in the plugins list.

Do you know how to setup the player shop keeper with a chest ? he show me the inventory of the chest but when i open the trade menu nothing appear :/

**Comment by blablubbabc** [comment]
Glad you were able to track it down. I will look into what is causing this incompatibility inside Ultimate_economy, once I have some time available. But I assume thay are interpreting shopkeepers' editor inventory window as one of theirs, and therefore enforce their no-item-movement rules there.

Regarding player shop trades setup: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Player-Shop-Setup

**Comment by blablubbabc** [comment]
I have informed the auhtor of the incompatibility: https://www.spigotmc.org/threads/ultimate_economy.331584/page-5#post-3311837
