### ISSUE TITLE
Ticket for suggestion to be able to have more characters/color codes for the Shopkeepers/shops name

### ISSUE THREAD

**Issue by axemwa** [Shopkeepers/Shopkeepers#549]
Feature request/suggestion:
Ticket for suggestion to be able to have more characters/color codes for the Shopkeepers/shops name

**Comment by mibby** [comment]
Would also love to see the ability to set color & formatting codes in the name! When trying to set the name ```&b&kTest```, it outputs the name as not valid.

**Comment by blablubbabc** [comment]
@mibby This is already possible and not what this ticket is about. See the wiki: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration (setting 'name-regex').
Whether the default values for this could be changed is a different question of course.

This ticket is about increasing the built-in max name limit from 32 to 64 or even further, depending on what minecraft allows.

**Comment by blablubbabc** [comment]
The limit will be increases to 128 in the next update.
Shopkeeper objects that are not able to display these long names will dynamically trim them to the maximum they can display (eg. citizens npcs will trim them to 64 for mobs and 48 for player npcs, and for sign shopkeepers the displayed name will get trimmed by minecraft itself depending on how many letters it can fit on the sign).

**Comment by blablubbabc** [comment]
Fixed in v2.5.0

**Comment by axemwa** [comment]
Nice, .jar nearly ready for release soon?

**Comment by blablubbabc** [comment]
I have uploaded it. Once it got approaved it will be available for download.
