### ISSUE TITLE
Failed to spawn shopkeeper.

### ISSUE THREAD

**Issue by mibby** [Shopkeepers/Shopkeepers#551]
Paper dev 525 (Spigot 1.13.2)
ShopKeeper compiled as of commit https://github.com/Shopkeepers/Shopkeepers/commit/40cd9165cf6e0906409d845f9718c328a6d78ba9

Is there any way to find out why shopkeeper villagers fail to spawn? I have a few villager shops setup in my MobArena region. WorldGuard region is _not_ flagged with mob-spawning deny and passive/aggressive mobs are turned on in the world configuration.

```
[21:00:53] [Server thread/WARN]: [Shopkeepers] Failed to spawn shopkeeper at void,951,79,1442
[21:00:53] [Server thread/WARN]: [Shopkeepers] Failed to spawn shopkeeper at void,953,79,1442
[21:00:53] [Server thread/WARN]: [Shopkeepers] Failed to spawn shopkeeper at void,955,79,1442
[21:00:53] [Server thread/WARN]: [Shopkeepers] Failed to spawn shopkeeper at void,949,79,1442
[21:00:53] [Server thread/WARN]: [Shopkeepers] Failed to spawn shopkeeper at void,959,79,1442
```

```
# Whether the plugin shall periodically verify that all shopkeepers that should
# currently be spawned are actually present. This should only be enabled if you
# have problems with shopkeepers disappearing.
enable-spawn-verifier: false
# If enabled, Shopkeepers tries to bypass other plugins which deny mob spawning
# (ex. land protection plugins).
bypass-spawn-blocking: true
# If enabled, Shopkeepers tries to bypass other plugins which deny interaction
# with the shopkeepers.
bypass-shop-interaction-blocking: true
```

**Comment by mibby** [comment]
I also tried enabling the spawn verifier but the shop npcs did not spawn. They only seem to respawn if I reload ShopKeeper _after_ server initialization.

**Comment by blablubbabc** [comment]
Yeah I reported this a few years ago: https://github.com/garbagemule/MobArena/issues/222

**Comment by blablubbabc** [comment]
I guess this is something for garbagemule to fix, but the last time I asked for this he showed no intent to make this possible. Maybe nag him again about this ;-)
