### ISSUE TITLE
Shopkeepers for 1.13

### ISSUE THREAD

**Issue by Ardno123** [Shopkeepers/Shopkeepers#555]
When will minecraft plugin shopkeepers come out for 1.13?
becase I need it 👍

**Comment by blablubbabc** [comment]
Shopkeepers is alreadz available for 1.13 since July of last year..

See https://dev.bukkit.org/projects/shopkeepers/files

**Comment by Ardno123** [comment]
Oh, sorry. No for 1.13, but 1.13.1, because my server is on 1.13.1, but plugin shopkeepers is not avabile for this game version

**Comment by blablubbabc** [comment]
dev.bukkit.org does not support different version tags for 1.13. and 1.13.1 currently, so I simply mark all version for 1.13.x as '1.13-compatible'. Shopkeepers is working on the latest version of Spigot. If you are running a spigot 1.13.1 server and the plugin does not work, then you might actually be running an outdated server version. If that is the case, running the command /version should tell you how many versions you are behind.
