### ISSUE TITLE
ShopKeepers TPS DROPS

### ISSUE THREAD

**Issue by AntoLuMeju99** [Shopkeepers/Shopkeepers#557]
Shopkeepers version: 2.2.1
Spigot version: PaperSpigot 1.8.8 - R.0.1
Shopkeepers it doing a lot of Scheduler and causing TPS Drops. How i can solve?

https://i.imgur.com/gxhkHJa.png

**Comment by AntoLuMeju99** [comment]
Soo?

**Comment by blablubbabc** [comment]
Duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/552

This looks like an issue with the server to me. I cannot explain or reproduce those timings. Please try other server versions, without other plugins, ..
