### ISSUE TITLE
Alias commands

### ISSUE THREAD

**Issue by ReshiStar** [Shopkeepers/Shopkeepers#558]
im having issues creating aliases for the shopkeeper.remote command, how do i set it up to allow the shop names?
what im trying to do is create an alias called Blacksmith, for the shopkeeper.remote, but it wont accept it at all.

**Comment by blablubbabc** [comment]
What do you mean by 'alias'? Are you editing the Shopkeepers plugin directly to add this command alias, or is this 'alias' part of a seprate plugin? I am not fully sure what you are trying to do.

Maybe you can make an example of what command you want to enter, and what behavior you expect.

**Comment by ReshiStar** [comment]
Im editing my server's commands.yml to Alias shopkeeper.remote into a command for my users, and im trying to find out a way to set them to open specific admin shops, so rather than /shopkeeper remote blacksmith, i wanna alias it into /blacksmith.

**Comment by blablubbabc** [comment]
According to the wiki and my testing, this seems to work:
Inside the commands.yml:
aliases:
  blacksmith:
  - "shopkeeper remote blacksmith"

This assumes that there is an shopkeeper named 'blacksmith'.

**Comment by ReshiStar** [comment]
Oh wow it works! 
My problem was i was doing 

aliases:
  blacksmith:
  - "shopkeeper.remote.blacksmith"

with the dots. Thank you!
