### ISSUE TITLE
Age of mob

### ISSUE THREAD

**Issue by BIgzostir** [Shopkeepers/Shopkeepers#559]
Spigot: 1.12.2
pl :  Shopkeepers-2.2.2

Hello, I can not make sure that my shopkeer type "magma_cube" remains adult. Because with the time it makes a cycle of life of the neck it becomes again child then still adult then still child .

thank you

**Comment by blablubbabc** [comment]
This has been fixed in v2.5.0. Once you update your server to MC 1.13.x you can also update Shopkeepers to make use of the latest fixes and changes.

For severe issues I sometimes backport fixes to older versions. But I don't consider this issue severe enough to justify the additional effort.

**Comment by BIgzostir** [comment]
ok  think you

**Comment by blablubbabc** [comment]
If you want to apply the fix yourself:
* Checkout v2.2.2
* Cherry pick: https://github.com/Shopkeepers/Shopkeepers/commit/b936eb25c420482a6572d4c0a847eb551c79bbab
* Build with maven.
