### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by XnO-Revo** [Shopkeepers/Shopkeepers#560]
I have installed and restarted my server however the plugin won't load.

I'm on 1.8.9 Java 8. Please help!

**Comment by blablubbabc** [comment]
Which version of the plugin are you using? Try v2.2.2: https://dev.bukkit.org/projects/shopkeepers/files/2615597
Check your server log. It might print a message explaining why it couldn't start.

**Comment by XnO-Revo** [comment]
Awesome! Thanks so much, it works now.

**Comment by XnO-Revo** [comment]
<3
