### ISSUE TITLE
[1.14 Shopkeepers] error when interacting with Shopkeepers

### ISSUE THREAD

**Issue by hurrgurl** [Shopkeepers/Shopkeepers#563]
Paper version git-Paper-7 (MC: 1.14) (Implementing API version 1.14-R0.1

What happened here?
https://pastebin.com/59YEdC6b

This happens when I try to interact with Shopkeepers.

Trades and functionality seem to be fine.

**Comment by blablubbabc** [comment]
Can't reproduce this on Spigot 1.14. You might want to report this to Paper. I assume this occurs when a plugin cancels the PlayerInteractEntityEvent.
