### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by jinjav6** [Shopkeepers/Shopkeepers#565]
## Preliminaries:

* **Shopkeepers version:**  2.4.0 and 2.6.0
* **Spigot version:** `bukkit 1.12.2 

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues]  (https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **` 2.6.0`**), with no other plugins and with no kinds of other server or client mods.    (i have bukkit i also canyt delete all mmy plugins becuase that will destry the server)

## The issue:

when i try and use any of the commands not comes up just says (unknown command type "/help" for help.) and i dont know if this is a issue anyone else has i have checked i have seen no one else with this problem i also tried all the commands that the plugin has and said the same thing and i should do the stuff its ment to but just says  (unknown command type "/help" for help.) 
![2019-05-23_15 05 53](https://user-images.githubusercontent.com/50954183/58255011-59520c00-7d6c-11e9-890a-6e85cb328d8b.png)
![2019-05-23_15 05 59](https://user-images.githubusercontent.com/50954183/58255025-5fe08380-7d6c-11e9-9f59-17c93e44265b.png)

**Comment by jinjav6** [comment]
please help

**Comment by blablubbabc** [comment]
v2.6.0 and v2.4.0 are not comaptible with Minecraft 1.12.
Use v2.2.2. See an overview of all versions and their supported minecraft versions: https://dev.bukkit.org/projects/shopkeepers/files

**Comment by jinjav6** [comment]
thank you
