### ISSUE TITLE
Building the repo has a missing dependency of Towny

### ISSUE THREAD

**Issue by Kongolan** [Shopkeepers/Shopkeepers#567]
```
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] The POM for com.palmergames.bukkit.towny:Towny:jar:0.84.0 is missing, no dependency information available
```
Not much more to say, the dependency is missing, so cloning the repo and building ends up in not building...

**Comment by blablubbabc** [comment]
Thanks for letting me know. There has been some changes to the maven repository, but this should work again now.
