### ISSUE TITLE
Schopkeeper freeze up

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#569]
Spigot:CraftBukkit version git-Spigot-01d0f04-455023c (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

Shopkeeper-vers:v2.7.0

With the shopkeepers, the dealers freeze sometime and look only in one direction. Only when you make **/shopkeeper reload** they move again.

**Comment by blablubbabc** [comment]
> "the dealers freeze sometime"

Hm, not sure how to reproduce this. Can you check the coordinates where those shopkeepers are located relative to your spawn location? Can you narrow down the circumstances in which they freeze?

**Comment by Blueeyestar** [comment]
You are welcome to come to my server and take a picture of it. I see it does not concern the normal sellers only the mobs..like the witch e.g.

**Comment by blablubbabc** [comment]
Make sure that you are using the latest version of Spigot (check the output of the `/version` command) and of Shopkeepers. If this does not help, consider creating a new issue ticket, because this issue has already been fixed.

**Comment by brondonychocmans** [comment]
> Make sure that you are using the latest version of Spigot (check the output of the `/version` command) and of Shopkeepers. If this does not help, consider creating a new issue ticket, because this issue has already been fixed.

im! Im using "Server. pro" for my server so, it automática y instala the las test version

**Comment by blablubbabc** [comment]
Some server hosters don't actually install the latest version of the server or plugin, so this might explain the issue.
