### ISSUE TITLE
Incompatibility issue with the SilkSpawners spawners

### ISSUE THREAD

**Issue by Zaino60** [Shopkeepers/Shopkeepers#573]
## Preliminaries:

* **Shopkeepers version:** `2.2.2`
* **Spigot version:** `This server is running Paper version git-Paper-1611 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`
---

## The issue:

When selling a SilkSpawners (https://dev.bukkit.org/projects/silkspawners - Latest Version, 5.0.2) generated spawner on a player-owned shopkeeper, the offer disappears after the server restarts.
Example reproducing the bug: https://gyazo.com/87ef35eb9e7c53fb9f8e864f82c9907b (I paused the gif when stopped the server and resumed it when joined back after restart)

- No derivations from the default config required
- Happening only with the SilkSpawners monster spawners, not happening with the vanilla monster spawners (like the ones given using the command /give <user> minecraft:mob_spawner 1)

**Comment by blablubbabc** [comment]
Reference to my original comment on this issue: https://dev.bukkit.org/projects/shopkeepers#c3137

I will look into it later. My guess is still that this might be a silkspawners or spigot/minecraft issue.

**Comment by blablubbabc** [comment]
SilkSPawners v5.0.2 does not seem to work with 1.14. I can't even get it to enable without errors.

**Comment by blablubbabc** [comment]
Looks like the mob spawner created by SilkSpawners contains some 'irregular'/legacy data which gets normalized/migrated by minecraft / Spigot on various occasions (such as when dragging the item around in the inventory, or when Shopkeepers saves and loads the item using Spigot's item serialization:
* "BlockEntityTag" entry contains an entry "EntityId" which gets migrated to a corresponding "SpawnData" entry.
* The "EntityTag" entry gets removed.

Screenshot of the item data differences between the item created by SilkSpawners and the 'normalized' item created by Spigot/Minecraft after dragging the item around in the inentory: https://prnt.sc/o2yilv

So this is not a Shopkeepers issue, but somehing SilkSpawners has to look into.
