### ISSUE TITLE
set name,delete,change page

### ISSUE THREAD

**Issue by fcvk** [Shopkeepers/Shopkeepers#575]
## Preliminaries:

* **Shopkeepers version:** `2.6.0`
* **Spigot version:** `Spigot 1.14.2`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

In the shopkeeper editor when I try to click on the items to set name,delete,etc. nothing happens. I can take the item and all but nothing happens. I even updated my spigot from 1.14.1  to the latest version and nothing happened.

**Comment by blablubbabc** [comment]
Shopkeepers v2.6.0 is not compatible with Spigot 1.14.x. You have to use Shopkeepers v2.7.x.

**Comment by fcvk** [comment]
> Shopkeepers v2.6.0 is not compatible with Spigot 1.14.x. You have to use Shopkeepers v2.7.x.

Oh, thank you. I thought I got the latest version.
