### ISSUE TITLE
Players can access GUI but can't trade

### ISSUE THREAD

**Issue by runty-1** [Shopkeepers/Shopkeepers#576]
* **Shopkeepers version:** `<2.6.0>`
* **Spigot version:** `git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

The issue:
Some players on my server can access the GUI and put the item they wish to trade, but the item they're trying to buy won't even show up in the bottom box.

[https://imgur.com/a/WYDJ3iw](url)

**Comment by blablubbabc** [comment]
Is this issue resolved?

If not I would need detailed reproduction instructions on how to create the involved items, shopkeeper and trades. And I would also ask to try to reproduce this on an up-to-date Spigot server and to check the server log for errors and info printed by enabling the debug mode.
