### ISSUE TITLE
Shopkeepers do not drop villager spawn egg when deleted

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Shopkeepers/Shopkeepers#577]
## Preliminaries:

* **Shopkeepers version:** `Latest`
* **Spigot version:** `Paper 97`
---

## The issue:

When you delete a player shopkeeper clicking the bone icon, player does not get his spawn egg back. Is it a bug or a missing feature?

**Comment by blablubbabc** [comment]
Have you enabled this feature in the config? 
deleting-player-shop-returns-creation-item

**Comment by Leonardo-Fiori** [comment]
The line was commented. Really strange. Thanks!
