### ISSUE TITLE
legacy-mob-behavior: Since updating to 1.14.3 some Shopkeepers are trying to run away

### ISSUE THREAD

**Issue by J0schlZ** [Shopkeepers/Shopkeepers#581]
* **Shopkeepers version:** `v.2.7.2`
* **Spigot version:** `git-Paper-125 (MC: 1.14.3)`

Video:
https://www.dropbox.com/s/mslmkhn9431nbhy/2019-07-08_09-44-25.mp4?dl=0

save.yml: https://pastebin.com/GnM6Rr2J
config.yml: https://pastebin.com/hz2F6qmX

**Comment by blablubbabc** [comment]
Disable 'use-legacy-mob-behavior' in the config.

**Comment by blablubbabc** [comment]
I will close this once I either fixed or removed this setting.

**Comment by blablubbabc** [comment]
The `legacy-mob-behavior` setting has been removed in v.211.0
