### ISSUE TITLE
[Suggestion] Server OP vanilla permissions

### ISSUE THREAD

**Issue by hurrgurl** [Shopkeepers/Shopkeepers#582]
Hi, sorry if I'm posting in the wrong place.

I do not use permission plugins, which makes it impossible to create shopkeepers as an admin with vanilla Minecraft /op. Also makes it impossible to trade with shopkeepers for regular (non op) players.

If it's not too much trouble could you add support for vanilla admins who have /OP and make it so that normal players have default trade access with existing shopkeepers?

Thank you for being awesome!

**Comment by blablubbabc** [comment]
This should already be the case. See the Permissions page in the wiki for an overview on the default permissions (https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Permissions). All permissions with default 'op' should work for op players, and all with default 'true' should work for regular players.

I also just tested this, and I can created admin shopkeepers as op, and trade with them as non-op player without issues.
