### ISSUE TITLE
Trader levels

### ISSUE THREAD

**Issue by SpaW2145** [Shopkeepers/Shopkeepers#584]
* **Shopkeepers version:** `<2.7.2>`
* **Spigot version:** `<1.14.3>`

Wanted to ask if there is any way to update to the trader levels being used to give new trades with each level or even if it is easier change them? 
Thank you for your plugin it is super useful.

**Comment by blablubbabc** [comment]
Shopkeepers allows you to setup your own shops, with a fixed list of trades. These shops are completely separate from the vanilla villager trading mechanics (Shopkeepers is not modifying the trading recipes of regular villagers) and they therefore don't have any level associated with them (the villagers used for representing these shops are purely cosmetical; they won't 'level up' if you trade with them).

If you want to change what villagers offer depending on their level, you might want to look for a plugin which allows you to reconfigure the vanilla trades instead.
