### ISSUE TITLE
[MC 1.14] Items appear delayed when opening an inventory menu

### ISSUE THREAD

**Issue by blablubbabc** [Shopkeepers/Shopkeepers#585]
Since MC 1.14 the items of inventory menus will appear delayed when the inventory menu is opened for the first time.
This seems to only be the case if the menu contains items with custom data (name, lore, etc.).
Calling Player#updateInventory after opening the inventory seems to prevent this delay.

Edit:
After some more testing, I am no longer able to reproduce this delay.. even after restarting the server and client, I currently no longer experience the delay, even without the additional updateInventory call.

---
Related report:

Server-Version: git-Paper-125 (MC: 1.14.3)
Shopkeepers-Version: v2.7.2
HDD-Type: SSD

Since MC 1.14 i get a slight delay when opening a shopkeeper trading-window.

save.yml: https://pastebin.com/GnM6Rr2J
config.yml: https://pastebin.com/hz2F6qmX

_Originally posted by @J0schlZ in https://github.com/Shopkeepers/Shopkeepers/issues/489#issuecomment-509117155_
---
Related spigot forum thread: https://www.spigotmc.org/threads/gui-not-loading-until-manually-called.381790/

**Comment by KodxQ8** [comment]
I have this bug too.

**Comment by blablubbabc** [comment]
Closing this as I can no longer reproduce this. If more evidence comes up for this again in the future I will look into it again.
