### ISSUE TITLE
Question: permission for normal players to use admin shops

### ISSUE THREAD

**Issue by joeywijts** [Shopkeepers/Shopkeepers#588]
I like this plugin, it's really well made! I'm just trying to figure out how to let normal players (non admins) use admin shops. I don't want them to be able to create admin shops. I don't mind the fact that admin shops have anunlimited supply, since it's a low populated server. 

I can't seem to find the permission for it. I'm using LuckPerms and other permission stuff works fine for me. Can you help me in the right direction?

**Comment by blablubbabc** [comment]
You can find all permissions with their default values in the wiki: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Permissions

Players should be able to trade with admin shopkeepers by default. So maybe check your permissions setup to verify that your players have the 'shopkeeper.trade' permission.
