### ISSUE TITLE
Spawner non-shopkeeper villager through spawner egg

### ISSUE THREAD

**Issue by Crusbyofficial** [Shopkeepers/Shopkeepers#591]
I want to allow players to spawn non-shopkeepers villagers through spawner egg is it possible or it isnt ?

**Comment by blablubbabc** [comment]
It is, in the following ways:
* If the player is in creative-mode, the spawner egg will work like normal.
* If the player is holding the spawner egg in his off-hand, it will work like normal.

You will also have to set prevent-shop-creation-item-regular-usage to false (which it is by default).
