### ISSUE TITLE
Disable to player spawn shopkeeper

### ISSUE THREAD

**Issue by Crusbyofficial** [Shopkeepers/Shopkeepers#593]
Need to prohibit to spawn shopkeepers through egg to normal player.

**Comment by blablubbabc** [comment]
Please stop posting duplicate issues. Your issue has already been answered here: https://github.com/Shopkeepers/Shopkeepers/issues/591
If you have followup questions, please ask them there.

I will keep this ticket open for a bit longer in the hope that you the  notice my messages.
But if you continue asking the same question over and over I will block you from creating further tickets.
