### ISSUE TITLE
Trade notifications, out-of-stock notifications

### ISSUE THREAD

**Issue by lukeeexd** [Shopkeepers/Shopkeepers#598]
So all my players want a message sent to them when someone buys something from their shop. So if they're online it will say x person bought x amount of x item. And then when stock is run out and someone tries to buy if it can notifiy too

**Comment by blablubbabc** [comment]
Also requested: Trade notifications for all shops for moderators (players with a special permission node). There might even be servers which want to post these trade notifications to all online players.

**Comment by CaptainKirk55** [comment]
Also is it possible to add a notification list for when people are purchased from while they are offline? Similar to how [https://dev.bukkit.org/projects/csn](Chest Shop Notifier) works?

**Comment by blablubbabc** [comment]
https://github.com/Shopkeepers/Shopkeepers/issues/693 also asks for notifications to be logged into the console, which fits this as well.

**Comment by blablubbabc** [comment]
Added in v2.13.0:
* Notifications for players with specific permissions.
* Notifications for shop owners.
* Merging of equal trades over a certain duration.
* Shop owners can disable the trade notifications for individual shops.
* Added a command for players to toggle trade notifications in-game.

However, there are still a few remaining things to look into:
* Notifications about the shop being out of stock.
* Notifications about the chest being full.
* Better protection against players causing notification spam.
* Storing notifications while the player is offline.
* Remembering the toggled notification state of players (this is currently reset when the player reconnects the server).
