### ISSUE TITLE
Shopkeeper reusable ?

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#603]
Hello, we love your Shopkeeper plugin.
I sell on the server with Talern the Shopkeeper to the users.  The user questions now, if it would be possible, if you could dismantle the shopkeeper and get the spawn egg again. Is that possible?

**Comment by blablubbabc** [comment]
There is a config option ('deleting-player-shop-returns-creation-item') to return the shop creation item when the shop is deleted.

**Comment by Blueeyestar** [comment]
thank you
