### ISSUE TITLE
Ominous Banners' name not correct in other language

### ISSUE THREAD

**Issue by tamashii** [Shopkeepers/Shopkeepers#604]
## Preliminaries:

* **Shopkeepers version:** `2.7.2`
* **Spigot version:** `git-Spigot-e5b1b5d-1ec1b05`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`git-Spigot-e5b1b5d-1ec1b05`**) with the latest version of Shopkeepers (currently **`2.7.2`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
Ominous Banner's name will be re-named to English name after Spigot restarted.

If using a different game language which is changed Ominous Banner's name, make a shopkeeper that exchange Ominous Banner to other things. Then restart the Spigot, you can see the banner's name set to English name `Ominous Banner` but not specified language one.

**Comment by blablubbabc** [comment]
Looks like an issue with Spigot's item serialization to me. I created an upstream ticket: https://hub.spigotmc.org/jira/browse/SPIGOT-5253

**Comment by blablubbabc** [comment]
With the latest Spigot changes (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/560b65c4f8a15619aaa4a1737c7040f21e725cce) this should be resolved.

I have tested this briefly and it seems that everything works fine. However, if you update your server make sure to create a backup of your save data, just in case something goes wrong.
