### ISSUE TITLE
The shop object type villager is disabled.

### ISSUE THREAD

**Issue by Darkness93** [Shopkeepers/Shopkeepers#606]
## Preliminaries:

* **Shopkeepers version:*v2.7.2* `    `
* **Spigot version:** `1.14.4 R0.1 Snapshot`
---

## Reproduction on a fresh and up-to-date Spigot server:

IDK. It's the latest version

## The issue:
When i try spawn shopkeeper it says The shop object type villager is disabled.
It's only placing sign , please help

**Comment by blablubbabc** [comment]
Can you attach your config file?

**Comment by Darkness93** [comment]
https://pastebin.com/EUEJFMgk

**Comment by blablubbabc** [comment]
You seem to be using an outdated config: I replaced the 'disabled-living-shops' with a new setting 'enabled-living-shops' some time ago.
Your config contains this: "enabled-living-shops: []" (<- empty list)
Add "VILLAGER" there to the list. Or delete the config and let the plugin freshly regenerate it.

**Comment by Darkness93** [comment]
Thanks man , it solved the problem
