### ISSUE TITLE
[Suggestion] Add CustomModelData to currency item

### ISSUE THREAD

**Issue by jeannen** [Shopkeepers/Shopkeepers#607]
Hey !

That would be nice to have a way to add CustomModelData in our currency item, that way we could create custom coins for shopkeepers, etc... ! :)

Regards,

**Comment by blablubbabc** [comment]
This will be part of the next update!
I completely changed how items are getting defined inside the config. This uses Bukkit's item serialization under the hood, so it should support arbitrary item data, while hopefully not requiring much maintenance by myself. To make it slightly more user-friendly I have applied some small changes to it though (meta data is at the same level as the item type and omitting some common entries that can be restored by the plugin), so it's not exactly the same format, but it uses the same attributes.

There is no documentation yet for the new item data format used, but I have documentated Bukkit's item serialization here: https://www.spigotmc.org/wiki/itemstack-serialization/
An example (untested) of specifying the custom model data for the currency item could be:
`
currency-item:
  type: EMERALD
  custom-model-data: 1
`

If you want to try this out and provide me feedback, a snapshot of the update is available here: https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.8.0-SNAPSHOT/Shopkeepers-2.8.0-20190818.072155-8.jar

**Comment by HolographicWings** [comment]
404 Not found.. :/

**Comment by blablubbabc** [comment]
Added in v2.8.0

**Comment by llronaldoll** [comment]
please tone possible to use custom model data in store creation item!

**Comment by blablubbabc** [comment]
@llronaldoll Hm? This is already possible since v2.8.0. See the 'configuration' page inside the wiki.
