### ISSUE TITLE
Confirm button when deleting the shop inside the editor

### ISSUE THREAD

**Issue by blablubbabc** [Shopkeepers/Shopkeepers#613]
Confirm button when deleting the shop inside the editor

**Comment by farum12** [comment]
Any updates on this feature? :) Couple of my players accidentally deleted their shops instead moving to the next page.
Thanks!

**Comment by blablubbabc** [comment]
> Any updates on this feature?

Nope

**Comment by blablubbabc** [comment]
Added in v2.13.0
