### ISSUE TITLE
Can't move normal villagers by boat.

### ISSUE THREAD

**Issue by Geekmakes** [Shopkeepers/Shopkeepers#614]
## Preliminaries:

* **Shopkeepers version:** `<v2.8.1>`
* **Paper version:** `< Paper 1.14.4 176>` (Only on Paper as far as I can tell)
---
## The issue:
Pushing naturally spawned villagers into any boat and having them as a passenger is giving me a message (In the picture below) when trying to enter the boat. This is only happening on this last version of Shopkeepers (v2.8.1).
![2019-08-29_20 54 36](https://user-images.githubusercontent.com/16181272/64052051-21b4e600-cb4b-11e9-89d7-af9d98ed2c55.png)

**Comment by blablubbabc** [comment]
That message is not coming from the Shopkeepers plugin.

**Comment by Geekmakes** [comment]
> That message is not coming from the Shopkeepers plugin.
I don't get the message on older versions of shopkeeper. So something about the villager behavior has changed I'm guessing?

**Comment by blablubbabc** [comment]
It seems like the message is comming from this plugin: https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/

**Comment by Geekmakes** [comment]
Huh, thats gotta be the issue, guess I'll keep Illegalstack disabled for now. Thanks for the help!
