### ISSUE TITLE
Shopkeeper saves item data in a different format, can't trade.

### ISSUE THREAD

**Issue by junsteed** [Shopkeepers/Shopkeepers#615]
Im making an adventure map....so
I use Shopkeeper to trade items which use default minecraft nbt codes like "color":"red".
But after a reload, shopkeeper saves it in §c, and make it unable to trade.

**Comment by blablubbabc** [comment]
Duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/578
Ultimately this is an issue with Spigot not retaining the original item data when serializing items to config files. The workarounds are to either use a plugin to create thise colored items, or use legacy color codes.
