### ISSUE TITLE
Scrolling Black Text Resets colour

### ISSUE THREAD

**Issue by kai769** [Shopkeepers/Shopkeepers#617]
## Preliminaries:

* **Shopkeepers version:** `<2.8.1>`
* **Spigot version:** `<Insert output of /version command>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.

The issue is black scrolling text in the name of an item breaks on update.

* Step-by-step instructions on how to reproduce the issue.

rename an item &0&k111, then put in shopkeeper, then reload plugin.

* Observed behavior.

Previously black scrolling text is no longer black.

* Expected behavior.

Expected to remain as previously was.

* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
Spigot issue: https://hub.spigotmc.org/jira/browse/SPIGOT-4441

**Comment by JustBru00** [comment]
This issue was mentioned in my plugin EpicRename. I am surprised that this hasn't been fixed by spigot upstream. At the very least there should be a notice in the java docs to warn plugin developers.

**Comment by blablubbabc** [comment]
This might have been fixed in Spigot:
* https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/cfeef75cd979c5d2b408645909325a055376c520
* https://hub.spigotmc.org/jira/browse/SPIGOT-5749

Not sure if the same issue applies to the white/dark-purple color code at the front now though.. But at least the usecases for those are less likely to occur since they are the default text colors.
