### ISSUE TITLE
shopkeeper 1.15

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#620]
I have now tested the shopkeeper in 1.15 .. actually they almost seem to work ... only they do not move.

**Comment by Blueeyestar** [comment]
do you already know if it will be difficult to fix the problem?

**Comment by Blueeyestar** [comment]
I do not know if it helps, but if I select a / shopkeeper npc, then it also moves in 1.15.1

**Comment by blablubbabc** [comment]
Regarding the citizens npc issues: I wasn't able to reproduce any disappearing yet. But could you try to place some regular citizens npcs nearby and check if these disappear as well when this issue occurs? In that case this might be a Citizens issues.

**Comment by Blueeyestar** [comment]
runs without problems so far. I'm happy that everything is running normally again. A great job of yours

**Comment by blablubbabc** [comment]
Fixed with v2.9.0
