### ISSUE TITLE
Problems with decoration heads

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#622]
Shopkeeper-version:  v2.8.1

Spigot:CraftBukkit version git-Spigot-56f8471-6567017 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

I have the problem on my server that shopkeeper sells the decoration heads, the content freezes. You can no longer pull out heads. For shopkeepers with normal items, everything is ok so far.

**Comment by blablubbabc** [comment]
Likely a spigot or minecraft issue. If I remember it correctly player heads will fetch their texture information occasionally from tje mojang servers when viewed. Not sure right now if a plugin can avoid this.

How are those decoration heads created exactly (so that I can try to reproduce this)?

**Comment by Blueeyestar** [comment]
I get my heads with the plugin hdb

https://www.spigotmc.org/resources/head-database.14280/

**Comment by Blueeyestar** [comment]
do you want to come to my 1.15 server? that's where the problem is at the moment

**Comment by Blueeyestar** [comment]
This occurs on 1.14.4 as well as on the 1.15 server

**Comment by blablubbabc** [comment]
Do you have the 'use-strict-item-comparison' setting enabled?
Also, could you try this again on the latest version of Spigot. There has been an update 2 days ago that fixes some issue related to skull item comparison: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/82322fe06c1331a4fc0d31b062ed633c99fce004

**Comment by Blueeyestar** [comment]
no I have false. should i activate it?

**Comment by blablubbabc** [comment]
No, but if it had been true this could have explained it.

**Comment by Blueeyestar** [comment]
o.k maybe the update will help :) I will continue testing. but your snapshot is great so far without any problems :)

**Comment by Blueeyestar** [comment]
but with the update something can happen. I can, although I have restarted the server, take deco heads out without them being frozen, where I had problems before

**Comment by blablubbabc** [comment]
So this issues is fixed / resolved?

**Comment by Blueeyestar** [comment]
I will test it for another 1-2 days after a few restarts and then let you know

**Comment by blablubbabc** [comment]
I just looked through the code: There seems to be a check that verifies that the result item from the trading view is the expected result item from the trading recipe the trade got creatred from. This check performs an item comparison using the isSimilar method, which according to the linked commit in Spigot was broken for player head items.
So I am pretty confident that this change in Spigot has fixed this issue.

**Comment by Blueeyestar** [comment]
thank you for the great work
