### ISSUE TITLE
buyer comes and goes

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#623]
we have a problem that buyer comes and goes. it does not remain stable. It's like coming and going permanently. What can that be? the others are normal

Spigot-Version: CraftBukkit version git-Spigot-18e2b9b-2d9db47 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by blablubbabc** [comment]
Maybe something else is (occasionally) preventing this shopkeeper from spawning, or removing it. Were you able to resolve the issue?

**Comment by Blueeyestar** [comment]
after a new start it was stable but then I exchanged something that started to come and go again

**Comment by blablubbabc** [comment]
What did you exchange? Did you consider some other plugin interfering with the spawning of shopkeepers? You could also turn on debug mode and see if something prevents the shopkeeper from spawning. But this will not detect if some other plugin remove its.

**Comment by Blueeyestar** [comment]
I was debugging now. Maybe you see the problem in it

https://pastebin.com/aTMxvQaK

**Comment by Blueeyestar** [comment]
22.12 16:05:58 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,195) missing, triggering respawn now
22.12 16:05:58 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:05:58 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,198) missing, triggering respawn now
22.12 16:05:58 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:05:58 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,186) missing, triggering respawn now
22.12 16:05:58 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:05:58 [Disconnect] User Janis6903 has disconnected, reason: Disconnected
22.12 16:05:58 [Server] Server thread/INFO [Thirst] Saving player Janis6903
22.12 16:05:58 [Server] Server thread/INFO Janis6903 hat Lululand verlassen.
22.12 16:06:18 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,186) missing, triggering respawn now
22.12 16:06:18 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:06:18 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,198) missing, triggering respawn now
22.12 16:06:18 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:06:18 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,195) missing, triggering respawn now
22.12 16:06:18 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:06:20 [Server] Server thread/INFO Ollysan issued server command: /home lager
22.12 16:06:20 [Server] Server thread/WARN Ollysan moved too quickly! -3381.7666386603482,-12.899999999999999,1559.341845727299
22.12 16:06:28 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,198) missing, triggering respawn now
22.12 16:06:28 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:06:28 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,195) missing, triggering respawn now
22.12 16:06:28 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)
22.12 16:06:28 [Server] Server thread/INFO [Shopkeepers] Shopkeeper (world,258,71,186) missing, triggering respawn now
22.12 16:06:28 [Server] Server thread/INFO [Shopkeepers]   Chunk was silently unloaded before! (dead: true, valid: false, chunk loaded: true)

**Comment by blablubbabc** [comment]
Looks like some other plugin might be removing those shopkeepers there.. (indicated by dead: true, but chunk loaded: true).

**Comment by Blueeyestar** [comment]
i think the problem is solved. I use the Mobfarm Manager. I have now set villager in it to -1 now it seems to remain. Funny thing is that only the buyer was affected. the normal sellers all worked

**Comment by blablubbabc** [comment]
Maybe it is coincidence that it only affected the buyer shopkeepers, due to the order in which it counts the nearby villgers.

**Comment by Blueeyestar** [comment]
Unfortunately the problem is back even though the mob farm manager is deactivated .. slowly you despair
