### ISSUE TITLE
can't trade

### ISSUE THREAD

**Issue by CraftWorksMC** [Shopkeepers/Shopkeepers#627]
Shopkeepers version:** `2.9.1`
Spigot version:** `1.15.2 with ProtocolSupport for older versions`
---

## Reproduction on a fresh and up-to-date Spigot server:

I was able to reproduce my issue on a freshly setup and up-to-date Spigot server (currently 1.15.2) with the latest version of Shopkeepers (currently 1.9.2), with no other plugins and with no kinds of other server or client mods.

## The issue:

i have command blocks running on a clock with summoning items (with custom names and lore.) and i added these items to buy a sword (with custom name and enchantments) and i couldn't buy it.
i should be able to pick it up but i can't.

to create the items i used https://www.gamergeeks.nz/apps/minecraft/give-command-generator
and copyed that in a command block. the sword i just had to do /enchant.

i didn't modify anything on the config file.

i don't know what is causing the issue. it happened in the past. same issue

**Comment by blablubbabc** [comment]
Can you post the exact command you are using to create those items?
