### ISSUE TITLE
Suggestion for movable shopkeepers

### ISSUE THREAD

**Issue by Syrkulous** [Shopkeepers/Shopkeepers#629]
Accidently opened this with no comment

I haven't seen anything about being able to move spawners

So if there isn't a way, can there be a command that is similar to /npc tphere
That isn't connected to the citizens plugin

**Comment by Syrkulous** [comment]
*I thought the config option had an option that fixes it but I misread.*

**Comment by blablubbabc** [comment]
There is already an open ticket for this, see: https://github.com/Shopkeepers/Shopkeepers/issues/361
