### ISSUE TITLE
if the chest is broken by other means than a player breaking the chest, shopkeepers don't realize that it has been broken

### ISSUE THREAD

**Issue by espen96** [Shopkeepers/Shopkeepers#631]
If the shopkeepers chest is broken by other means than a player breaking the chest (worldedit, advanced region market resetting the region.) the shopkeeper will stick around/return even if the chest no longer exists

Paper 1.15.2 build 87. 
Latest release of Shopkeepers.

**Comment by blablubbabc** [comment]
Currently the plugin already account that situation by ignoring any actions that require the chest. The proposed change would be to automatically delete the shopkeeper once it is detected that the shop's chest no longer exists.
This could be part of the periodic teleport or spawn verifier checks that happen for every shopkeeper.
This would be bound to the 'delete-shopkeeper-on-break-chest' setting. If the 'deleting-player-shop-returns-creation-item' is enabled, the shop creation item will be dropped.

**Comment by blablubbabc** [comment]
Included with v2.9.2
