### ISSUE TITLE
Change the emerald price to iron 

### ISSUE THREAD

**Issue by UltimateDash** [Shopkeepers/Shopkeepers#638]
## Preliminaries:

* **Shopkeepers version:** `<Latest when i write this>`
* **Spigot version:** `<1.15.2>`
---

I want to know if its possible, in a player shop to set the price to iron. Thank you

**Comment by blablubbabc** [comment]
You can change the currency items inside the config from emeralds and emerald blocks to, for example, iron ingots and iron blocks. See the [Wiki](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration) that.

**Comment by blablubbabc** [comment]
> > You can change the currency items inside the config from emeralds and emerald blocks to, for example, iron ingots and iron blocks. See the [Wiki](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration) that.
> 
> Is it possible to use other prefixes for currency items? like "kubejs:example_item"

Consider opening a new ticket in the future.

Regarding your question: No, only vanilla items are currently supported. Modded server are not supported, and custom items of other plugins are not recognized in the config either.
