### ISSUE TITLE
Worldguard allow-shop -g  not work

### ISSUE THREAD

**Issue by BlackFox3000** [Shopkeepers/Shopkeepers#643]
## Preliminaries:

* **Shopkeepers version:** `2.9.2`
* **Spigot version:** `This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able `** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`Paper version git-Paper-143`**) with the latest version of Shopkeepers (currently **`2.9.2`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
When we create a new area, with wordguard-bukkit-7.0.2.jar, the flag allow-shop work for global but not when we use  the option -g <target>. 
I wish that only members of an area can create in this area. 
 I don't know if the bug come to wordguard or to shopkeeper, or if it's me or if isn't possible.  I test on the clean server. ^^

**Comment by blablubbabc** [comment]
The check for whether the allow-shop flag is set does not take the player into account for whom the flag is being checked currently. So I assume this is not working for that reason.

I changed it to take the player into account. Can you try this snapshot and let me know if this works: https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.9.4-SNAPSHOT/Shopkeepers-2.9.4-20200417.043215-1.jar

**Comment by BlackFox3000** [comment]
For me it's ok, think 

you are the best !

**Comment by blablubbabc** [comment]
Okay. I will close this once I release this in an official update.

**Comment by blablubbabc** [comment]
Fixed in v2.10.0
