### ISSUE TITLE
Storage Solutions?

### ISSUE THREAD

**Issue by Zero-Gravity58** [Shopkeepers/Shopkeepers#648]
Why can I only use chests to store my stock? My shop itself is a giant barrel in the sky, and I've filled it chock full of barrels. Why can't I use barrels instead? Maybe make it so that when you right-click a block, it checks for inventories at that position at least 27 stacks big. Thanks!

**Comment by blablubbabc** [comment]
There is already a request ticket for this: https://github.com/Shopkeepers/Shopkeepers/issues/639
