### ISSUE TITLE
Freezed traders!

### ISSUE THREAD

**Issue by brondonychocmans** [Shopkeepers/Shopkeepers#655]
## Preliminaries:

* **Shopkeepers version:** `1.15.2`
* **Spigot version:** `1.15.2`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

(sorry for the broken english)

Villager or other-entity traders dont move, after summoning them by use the /shopkeepers <entity/admin-shop> command, they just stare at the "Z" chord (south).

i've tried to /tp to a player and /tp to a specific rotation to at least let them looking at the "shop table" but it doesn't  work...

I have a semi/vanilla server and have just 5 pluggins instaled.
* World edit
* World guard
* chunk keeper
* Skin restorer
* Shop keeper

and 1 datapack:

*warp sigils

Ive tried to make traders around the world, mabye the world guard had something to do in that situation but dosent...

No clue whats going on. helppp :(

Include:
* Freezed traders
* summon a trader
* all the pluggin work normaly, the problem is that my traders dont look at near players
* Hopely they look at the players!
* debug mode is activated
* i vavent eaven touched the pluggin configurations
* I jsut know about "inside minecraft commands" so the spawn and shop zone have some "player detection" command blocks but with simple commands like /execcute if entity @a[distance=etc,nbt{[etc]}] but thats all... the trade seems to be working normaly and changing 
 the "skin" of the trader works perfect.

**Comment by blablubbabc** [comment]
What is the output of the `/version` command?

**Comment by brondonychocmans** [comment]
2.8.1 for Shopkeepers
worldedit-bukkit-7.0.1

And for Paper, i executed the /version command, it says this;
[INFO] .... Previous version: git-Paper-353 (MC: 1.15.2)
[INFO] .... You are running the latest version.

**Comment by blablubbabc** [comment]
The latest version of Shopkeepers is v2.9.3. v2.8.1 is not compatible with MC 1.15.x. See https://dev.bukkit.org/projects/shopkeepers/files

You mentioned that you are using a server hoster for installing your plugins, so you should contact them about this.
