### ISSUE TITLE
Piglin shop type attacks player

### ISSUE THREAD

**Issue by JMCY26** [Shopkeepers/Shopkeepers#659]
Creating a piglin shop, the piglin starts shaking and attacks the player, does not setup as a shop. Using the villager egg to create the spawn.

**Comment by blablubbabc** [comment]
Which version of Shopkeepers and Spigot are you using?

I am currently not able to reproduce this. Are you able to reproduce this on the latest version of Spigot with no other plugins running other than the latest version (v2.10.0) of Shopkeepers?
Also, are there and error or debug messages being logged?

**Comment by blablubbabc** [comment]
Are you by any chance using the plugin 'AdvancedSpawners'? Some other users have reported issues which might match what you are describing. If that is the case, consider reporting this issue to the author of AdvancedSpawners so that he can have a look at this.

**Comment by blablubbabc** [comment]
@JMCY26 So, what was the issue? How did you resolve it? Knowing this will help me to point other users with similar issues in the right direction.
