### ISSUE TITLE
Cannot create player shop while operator/admin

### ISSUE THREAD

**Issue by GradedThrower97** [Shopkeepers/Shopkeepers#660]
## Preliminaries:

* **Shopkeepers version:** `2.10.0`
* **Spigot version:** `git-spigot-6f4ff1b-4d92db6
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`not able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`git-spigot-6f4ff1b-4d92db6`**) with the latest version of Shopkeepers (currently **`2.10.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
I cant seem to figure out how to make a trading shopkeeper, while i am operator, and when i do /deop and try it, the command doesnt even work. Also when i went into the config file all i changed was that players can use the command to make shopkeepers, and that doesnt work either, unless i am doing something very wrong, i really want to know how to make a regular player shop, while admin, instead of making an infinitely restocked shop

**Comment by blablubbabc** [comment]
I assume this to be resolved with the information I provided above. If not, let me know.
