### ISSUE TITLE
Items revert to itallic on traders

### ISSUE THREAD

**Issue by detoxv** [Shopkeepers/Shopkeepers#661]
Using playerheads they revert to itallic text on 1.16.1 latest paper spigot and latest shopkeepers update. It causes trades to be incompatible after restart as the initial input was a normal plain text and after restart the trades have itallic formatting.

**Comment by blablubbabc** [comment]
I assume this is related to: https://github.com/Shopkeepers/Shopkeepers/issues/578
Relevant Spigot issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5063

I assume you are using some Minecraft mechanism for creating the items (eg. command or loot table)?
I don't have a real solution to that issue yet. Ultimately this is something that needs to be fixed inside of Spigot at some point. The only other 'solution' right now is to use a plugin for creating the item.
