### ISSUE TITLE
Question about trading custom items

### ISSUE THREAD

**Issue by Exvinem** [Shopkeepers/Shopkeepers#667]
Excuse me...
i want to ask about trading custom items..
i want to trade a custom items (RPG items) but after i put it inside my shopkeeper editors... i can trade it
i mean, when i want to trade an customitems1 + customitems2 = customitemsresult, the customitems1 cannot be detected...
is there any way to solve this thing, or am i missing something??
i hope you can guide me, thank you very muchh...

**Comment by blablubbabc** [comment]
Maybe you can clarify exactly what makes these items 'custom' (eg. by posting their internal nbt data, `/data get entity @s`) and how you create these items (command, plugin, config, etc.) so that I can create the same items on my test server.

If your custom item has a custom display name or lore, you might be running into this issue:
* https://github.com/Shopkeepers/Shopkeepers/issues/578
* https://hub.spigotmc.org/jira/browse/SPIGOT-5063
* https://hub.spigotmc.org/jira/browse/SPIGOT-5964

**Comment by Exvinem** [comment]
![image](https://user-images.githubusercontent.com/67906424/87982821-909f8280-cb01-11ea-8bef-d5c5289b440a.png)
![2020-07-21_03 24 53](https://user-images.githubusercontent.com/67906424/87982941-c9d7f280-cb01-11ea-8b28-7c419b509399.png)

**Comment by blablubbabc** [comment]
Two potential issues:
* Once you setup a trade with this item in a shopkeeper and then reload the plugin, retrieve the item from the shopkeeper, check its internal data as seen above and compare it with the data of your original item. If any of the data has changed during this procedure, this might explain your issue. Whether there is a solution or how to resolve this issue depends on which data has changed exactly.
* You didn't show the complete data of the item, but it seems like it might be storing some kind of uuid and other kinds of unique numbers. If someone tries to use the trade, the provided item has to perfectly match the requested item. If any of these internal numbers or uuids don't match, the shopkeeper won't accept the item.

**Comment by Exvinem** [comment]
Count: 1b}], Air: 300s, foodLevel: 19, XpSeed: -235530301, XpLevel: 72, XpP: 0.6129081f, Inventory: [{Slot: 0b, id: "minecraft:wooden_sword", tag: {MMOITEMS_ATTACK_DAMAGE: 6.326363431405336d, MMOITEMS_ATTACK_SPEED: 1.6903753340043983d, MMOITEMS_ABILITIES: '[{"Id":"STUN","CastMode":"ON_HIT","Modifiers":{"duration":1.0,"cooldown":9.0}}]', Damage: 0, MMOITEMS_GEM_STONES: '{"EmptySlots":["Blue"],"Gemstones":[]}', MMOITEMS_DISABLE_ENCHANTING: 1b, MMOITEMS_DISABLE_CRAFTING: 1b, AttributeModifiers: [{Name: "mmoitemsDecoy", AttributeName: "generic.attackSpeed", Operation: 0, UUIDMost: -8681499546602028042L, UUIDLeast: -8534666352103010068L, Amount: 0.0d}], MMOITEMS_PERM_EFFECTS: '{"SPEED":1}', MMOITEMS_DISABLE_REPAIRING: 1b, MMOITEMS_ITEM_TYPE: "SWORD", MMOITEMS_DISABLE_SMELTING: 1b, Unbreakable: 1b, HideFlags: 6, MMOITEMS_CRITICAL_STRIKE_CHANCE: 19.78468266197998d, display: {Name: '{"text":"Militia Sword"}', Lore: ['{"text":"Sword"}', '{"text":""}', '{"text":"➸ Attack Damage: 6.33"}', '{"text":"➸ Attack Speed: 1.69"}', '{"text":"■ Crit Strike Chance: +19.78%"}', '{"text":""}', '{"text":"On Hit: Stun"}', '{"text":"Duration: 1"}', '{"text":"Cooldown: 9"}', '{"text":""}', '{"text":"◆ Empty Blue Gem Socket"}', '{"text":""}', '{"text":"Standard sword used in militia"}', '{"text":"Tier : F-"}']}, MMOITEMS_ITEM_ID: "MILITIA_SWORD", MMOITEMS_LORE: '["Standard sword used in militia","Tier : F-"]'}, Count: 1b}

**Comment by Exvinem** [comment]
thats the data of the item

**Comment by Exvinem** [comment]
item1:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: WOODEN_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §a§f§f§lMilitia Sword
          lore:
          - §cSword
          - ''
          - '§7➸ Attack Damage: §f7.16'
          - '§7➸ Attack Speed: §f1.77'
          - '§7■ Crit Strike Chance: §f+13.7%'
          - ''
          - '§2On Hit: Stun'
          - '§2Duration: 1'
          - '§2Cooldown: 9'
          - ''
          - §a◆ Empty Blue Gem Socket
          - ''
          - §7§lStandard sword used in militia
          - '§7§lTier : §f§lF-'
          attribute-modifiers:
            GENERIC_ATTACK_SPEED:
            - ==: org.bukkit.attribute.AttributeModifier
              amount: 0.0
              name: mmoitemsDecoy
              uuid: 87851e28-af12-43f6-898e-c62bde6bd0ec
              operation: 0
          ItemFlags:
          - HIDE_ATTRIBUTES
          - HIDE_UNBREAKABLE
          Unbreakable: true
          internal: H4sIAAAAAAAAAGWRTUvDQBCGpwdLUARRFPwAwx68WIteFHvQbpNpuzQfJbsiUkoIJkIgbaRJKVL6F3rWqx4K/oz+LhG3KZZqLwsz7+zMM++sA+RhzzRtJtDkLhWCag1XpyatYfnoI3n/HB8psL0omL2ueGgirPF729GXNVphBhMMOditIWE+KREu7ixSIJqXpGbsBzJjW26dCZmTcfgUBr2ElIbE7/e8NIy7pHRRPC+QxziO/Hggw+vi+WjUVmBnMaUmAbiwLTnmZEiw85y+8ChOZZsWqUT9gLQLpBZ0kjTuBrNke5SD/cVvnXFaMdDlJhqCWbVcDg5XRLS0OrUyOQ+7/83hTUT99utm/P1ar+TheKFrjtxeo4bEc1gD3VkTDcun/ttl+jxVYOuvi0yHTTNzjLqZlzk4WEFxsEmZMwdd3UJzaDXDVJYwm+iYLlarqAkOG0OS8UpjR4qc91tk2A5CuUWmk6vpJOKp1/W9nq8mg1i+/STw1bCrdsIoTENPHmteJuS51JI6nTzJoHpG2vADEqVaqD8CAAA=

**Comment by Exvinem** [comment]
this one is from the save.yml

**Comment by Exvinem** [comment]
Excuse me...
The problem is solved, im sorry to take ur time...
the problem is just, i made the items get random stats so its a different item.......
i just realized it.. thank you for responding..
it really helps hehe

**Comment by blablubbabc** [comment]
Okay, thanks for letting me know!
