### ISSUE TITLE
MC 1.16: Player head not recognize after restart or reload

### ISSUE THREAD

**Issue by Thefirstalpha** [Shopkeepers/Shopkeepers#670]
## Preliminaries:

* **Shopkeepers version:** `2.10.0`
* **Spigot version:** `git-Spigot-0509002-7c03d25 (MC: 1.16.1)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`git-Spigot-0509002-7c03d25 (MC: 1.16.1)`**) with the latest version of Shopkeepers (currently **`2.10.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

When I add a custom player head inside the shopkeeper at a cost position, the head is recognized and trade is ok. After a restart or reload, the trade not work, it doesn't recognize the head, it seems that the head is different because when I recover it from the shopkeeper editor inventory, it doesn't stack with the original head item.

I've tried this head, give with a command block
`/minecraft:give @p minecraft:player_head{display:{Name:"{\"text\":\"test\"}"},SkullOwner:{Id:[I;-712970790,-871675898,-1736663990,662846831],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzI1ZTNmZTgxOWQ4M2JmZTA3YzE3YjZhZmZlOGI3ZTY5ODdkZGEwNjUzMjlhNzVhZWMyZDhhYjc0MzVkNmJkZSJ9fX0="}]}}} 1`

**Comment by blablubbabc** [comment]
The issue might be the custom display name. This text has to match the format that is used by Spigot when plugins create the item. After you have reloaded Shopkeepers, take the item out of the shopkeeper and use `/data get entity @s` to view its NBT data and check for differences with your original item. You will then have to alter your original item accordingly.
See also: https://github.com/Shopkeepers/Shopkeepers/issues/578
