### ISSUE TITLE
If you set an item with Lore in the Admin-shop and reboot server, you will not be able to trade.

### ISSUE THREAD

**Issue by rnlin430** [Shopkeepers/Shopkeepers#671]
## Preliminaries:

* **Shopkeepers version:** `2.10.0`
* **Spigot version:** `git-Spigot-9639cf7-0458f60 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was able to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`MC: 1.16.1`**) with the latest version of Shopkeepers (currently **`2.10.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.
I usually use Admin-Shop.
If you set an item with Lore in the shop, you will not be able to trade after reboot server.
Apecifically, If you register an item with a custom name or Lore on the cost side of the shop, you will not be able to trade after reboot.
## How to reproduce:
1. Create a Admin-Shop(/shopkeeper Admin-shop)

2. Create a custom item with lore and custom display name.
e.g.```/minecraft:give @p baked_potato{display:{Name:'{"text":"Iteme Name"}',Lore:['{"text":"Item Lore"}']}} 1)```

3. Set the created item(Ex. baked_potato) on the cost side, and set an appropriate item on the result side.(Ex. Diamond)
<img width="254" alt="2" src="https://user-images.githubusercontent.com/43895616/88629846-bf61be00-d0ea-11ea-8f0a-72f015641983.png">

4. Check you can trade.

5. Reboot the server or reload the plugin.
e.g.```/restart```
6. When you login server and trade again, you can no longer trade.

## Anything else that might be useful to reproduce and identify the issue:
I compared the between these item's raw Minecraft NBT data.
(/data get entity @p SelectedItem)

NBT of item taken out by setting in Admin-Shop
```{id: "minecraft:baked_potato", Count: 1b, tag: {display: {Lore: ['{"text":"Item Lore"}'], Name: '{"text":"Iteme Name"}'}}}```

NBT of item before setting in Admin-Shop
```{id: "minecraft:baked_potato", Count: 1b, tag: {display: {Lore: ['{"extra":[{"text":"Item Lore"}],"text":""}'], Name: '{"extra":[{"text":"Iteme Name"}],"text":""}'}}}```

The NBT data was changing.

**Comment by blablubbabc** [comment]
See
* https://github.com/Shopkeepers/Shopkeepers/issues/578
* https://hub.spigotmc.org/jira/browse/SPIGOT-5063
