### ISSUE TITLE
Shopkeeper Trade showing no stock

### ISSUE THREAD

**Issue by Pilkojr** [Shopkeepers/Shopkeepers#674]
## Preliminaries:

* **Shopkeepers version:** `<2.10.0>`
* **Spigot version:** `<git-Paper-110>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server: Not able to use a fresh Spigot server

I was **`<not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<2.10.0>`**) with the latest version of Shopkeepers (currently **`<git-Paper-110>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

Hi, I have a bunch of shopkeepers/chests used to sell enchantment books. My shopkeeper is showing the trade is out of stock even though there is stock in the shopkeeper chest. The editor screen shows 2 enchanted books even though I only setup one. 
I have completely removed the stock in the chest, broken the shopkeeper sign, broken the chest, then replaced and setup the shop again, but the same issue keeps arising. It's happening on a number of shopkeepers in the same area.
![image](https://user-images.githubusercontent.com/68989976/88927536-eb339e00-d2ba-11ea-94b0-5a92867bc11a.png)
![image](https://user-images.githubusercontent.com/68989976/88927580-f5ee3300-d2ba-11ea-9978-85e54e55afb6.png)
![image](https://user-images.githubusercontent.com/68989976/88927604-fdadd780-d2ba-11ea-8b3f-db60dfc5bba3.png)
![image](https://user-images.githubusercontent.com/68989976/88927621-08686c80-d2bb-11ea-8d0c-2f9da3c8b722.png)

Any help is apprecitated.

Thanks,
Pilkojr

**Comment by blablubbabc** [comment]
Please try to reproduce the issue on Spigot and without other plugins, to make sure that none of these interfere here.

* Does this issue occur right away, or does it take some time / a plugin reloads for this to occur?
* Since it shows two different variants of the apparently same book inside the editor my guess is that these books have some internal nbt data which does not get properly persisted.
  * Can post the raw nbt data of these items. Eg. create a schematic with WorldEdit of a chest containing this book item. And/or the NBT shown by the `/data get entity @s` command.
  * How do you create these enchanted book items? Do you retrieve them from the creative menu or do you create them somehow else?
* Did this issue only come up during the update to MC 1.16 / Did the same shopkeeper with the same trades work wothout issues before that?
* I assume this is trading player shop?

**Comment by Pilkojr** [comment]
Hi and thank you for the reply. Unfortunately I don't have a server available that I can try to reproduce without other plugins.

- Does this issue occur right away, or does it take some time / a plugin reloads for this to occur?
: the issue takes some time to occur. I've not seen it happen in front of my eyes, but players have reported that my shop was out of stock. When I check the stock, there's heaps of books in the chest, and I notice that the Editor UI now has 2 books available to 
price.
- Since it shows two different variants of the apparently same book inside the editor my guess is that these books have some internal nbt data which does not get properly persisted.
Can post the raw nbt data of these items. Eg. create a schematic with WorldEdit of a chest containing this book item. And/or the NBT shown by the /data get entity @s command.
: I'm not familiar with either of these commands sorry. How do I get the 'nbt' data you require?
- How do you create these enchanted book items? Do you retrieve them from the creative menu or do you create them somehow else?
: the book items are from a villager trader
- Did this issue only come up during the update to MC 1.16 / Did the same shopkeeper with the same trades work wothout issues before that?
: I have only placed these shopkeepers after upgrading to 1.16.
- I assume this is trading player shop?
: Yes, it is a trading player shop

Thank you

**Comment by blablubbabc** [comment]
>Unfortunately I don't have a server available that I can try to reproduce without other plugins.
A locally setup server should suffice for this.

> I'm not familiar with either of these commands sorry. How do I get the 'nbt' data you require?
You can see the nbt data by holding the item in hand and then using `/data get entity @s`.
You can send me those items by creating a schematic file with WorldEdit and sending me that file somehow: Create a chest, insert the item, left and right click it with a wooden axe to select it, `//copy`, `//schematic save filename`. Inside the plugins folder of WorldEdit you will then find a file `filename.schematic` or similar which you can send me.

**Comment by blablubbabc** [comment]
If you have further information on this issue and how to reproduce it, let me know.
