### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by Kyrobi** [Shopkeepers/Shopkeepers#676]
I'm tryinng to build the plugin frmo source and it seems like the dependencies could not be found from the repo.

![image](https://user-images.githubusercontent.com/20980266/89131887-c49d7f00-d4d5-11ea-8860-f3270afdce31.png)

This goes for 1.14, 1.15, and 1.16

**Comment by blablubbabc** [comment]
You first have to build Spigot 1.14, 1.15 and 1.16 using Spigot's BuildTools program: https://www.spigotmc.org/wiki/buildtools/
