### ISSUE TITLE
Remove delete button

### ISSUE THREAD

**Issue by Ansandr** [Shopkeepers/Shopkeepers#677]
I suggest adding in the config the features of disabling the delete button of the the gui menu shoopkeper

**Comment by D1N60** [comment]
+1 for this ...ish. Agreed, it's far too close to the "Page 2" button. A couple times I lost multiple pages of work. Or maybe have it send an option to the server chat of "Would you like to delete %Shopkeeper Name%? (y/n)"

**Comment by blablubbabc** [comment]
There is already a ticket for adding a confirmation to shop deletion: https://github.com/Shopkeepers/Shopkeepers/issues/613

The only other reason why people sometimes ask for a way to disable the delete button is for some kind of market with pre-setup shops. But this is not supported and disabling the delete button is not the proper solution to that. Instead the delete button should probably only reset the shop to its 'rentable' state. See https://github.com/Shopkeepers/Shopkeepers/issues/3
