### ISSUE TITLE
Problems with NBT stuff on paper 1.16

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Shopkeepers/Shopkeepers#680]
## Preliminaries:

* **Shopkeepers version:** `Shopkeepers version 2.10.0`
* **Spigot version:** `Paper version git-Paper-133 (MC: 1.16.1)`
---

Looks like that 1.16 update, at least on paper, raised a lot of problems with nbt tags in general. Old custom items (with custom nbt, lore, title) are not stackable anymore with the same items (generated by an essentials /kit command), and shopkeepers do not "see" them as correct when inserted in the GUI slot. Is this thing fixable on your side? Or is it a paper/1.16 problem?

**Comment by blablubbabc** [comment]
Spigot issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5964
I don't know if there is a good solution to this considering that Spigot might do further changes to their text-to-component translation in the future. And automatically converting all items on the server to Spigot's internaö format might be problematic as well for compatibility reasons with vanilla Minecraft.

In the latest snapshot version of Shopkeepers I added a command to convert items to Spigot's current data format. It is also able to automatically convert the items of players whenever they interact with a shopkeeper. You can find the snapshot here: https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.11.0-SNAPSHOT/Shopkeepers-2.11.0-20200801.230352-3.jar
See the full changelog in the repository regarding this command and the other changes included in this updates. Also make a backup of your shopkeeper data and config.
