### ISSUE TITLE
[1.16.2] Mob animation not working

### ISSUE THREAD

**Issue by JohnnyLin-a** [Shopkeepers/Shopkeepers#681]
Game Version 1.16.2
Spigot: Latest build
Plugin: Latest build & Latest snapshot

Mobs don't rotate around, they just stand still.

Shops still accessible tho, so it's just the mob. Not sure of other bugs in 1.16.

Steps to reproduce:
Make a shop with any mob.

Bug happens even in a blank server with Shopkeepers as the only plugin.

**Comment by blablubbabc** [comment]
A update (v2.11.0) for MC 1.16.2 is on the way (the 'latest snapshot', i.e. v2.11.0-SNAPSHOT does not work on MC 1.16.2 yet). The update has already been uploaded and is currently waiting for approval by resource staff.
