### ISSUE TITLE
All shopkeepers facing south

### ISSUE THREAD

**Issue by Sulack** [Shopkeepers/Shopkeepers#682]
Preliminaries:

* **Shopkeepers version:** `Shopkeepers-2.11.0-20200801.230352-3.jar`
* **Spigot version:** `1.16.2-R0.1 SNAPSHOT
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:
No Time :/

## The issue:

Updated server to 1.16.2
All shopkeepers stuck facing south. 
Citizen NPCs stopped working too. (conflict?)

No Idea what else to do. Waiting on smart people. 

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.
[latest.log](https://github.com/Shopkeepers/Shopkeepers/files/5066954/latest.log)

![2020-08-12_20 07 03](https://user-images.githubusercontent.com/15989388/90090153-2b8e1580-dcd8-11ea-897a-5edfa6e6c5f0.png)

**Comment by blablubbabc** [comment]
A update (v2.11.0) for MC 1.16.2 is on the way (the latest snapshot, i.e. v2.11.0-SNAPSHOT does not work on MC 1.16.2 yet). The update has already been uploaded and is currently waiting for approval by resource staff.

Citizens also requires an update to keep working on MC 1.16.2. But that is unrelated to shopkeepers. According to their issue tracker there might already be a working version in their development builds.
