### ISSUE TITLE
Update Readme on how to setup and compile this project.

### ISSUE THREAD

**Issue by ryantheleach** [Shopkeepers/Shopkeepers#685]
The readme currently appears to be out of date in regards to how to checkout and update this project.

The various craftbukkit dependencies are failing resolution, presumably due to them needing to be built to my local maven repository using build tools.

Some basic instructions on how to do this / automate this for all supported versions that Shopkeepers currently supports would be a welcome addition to the readme.

**Comment by blablubbabc** [comment]
It would probably make sense to add a script which combines all of these and also checks if they are already available in the local repo before building the individual versions. Similar to the travis script, which could then refer to that new script instead.

I am not sure of chmod +x is required / even works under windows. But it probably makes sense to chmod +x those bash scripts inside the repo if that is not the case currently, for anyone not using windows.

**Comment by ryantheleach** [comment]
It was required. I couldn't run the script until I did.

**Comment by blablubbabc** [comment]
I added an installSpigotDependencies.sh script and updated the readme accordingly. The scripts are already marked as executable inside the repo. And I am also able to execute them right away under windows, without the additional chmod+x. The scripts work in both git bash and regular Windows cmd for me.
