### ISSUE TITLE
How To Rotate Shopkeepers?

### ISSUE THREAD

**Issue by xxxeeexxx** [Shopkeepers/Shopkeepers#687]
I am currently using the most recent version of the plugin

I was wondering if there is a way to rotate the shopkeeper, as all of mine are facing southwards

Help would be appreciated

**Comment by blablubbabc** [comment]
> I am currently using the most recent version of the plugin

My guess is that you are not using the most recent version of shopkeepers. This is a known issue when running an outdated version of shopkeepers. The current version is v2.11.0.

Some server hosters don't provide the latest version of shopkeepers. You will have to check there documentation for how to manually install the latest version of Shopkeepers.
