### ISSUE TITLE
1.16 Spigot: Can't use the shopkeepers create item at all

### ISSUE THREAD

**Issue by atultw** [Shopkeepers/Shopkeepers#688]
## Preliminaries:

* **Shopkeepers version:** `v2.11.0`
* **Spigot version:** `This server is running CraftBukkit version git-Spigot-b5a13e6-b8ee6a8 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`This server is running CraftBukkit version git-Spigot-b5a13e6-b8ee6a8 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`**) with the latest version of Shopkeepers (currently **`v2.11.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

* I installed the plugin as per the official instructions, and started my server. There were no changes to the config, just a fresh install of the plugin. I host on my linux machine (ubuntu 20.04 desktop), so I put the jar into the plugins folder. These are the instructions I am following to create the shop: [https://youtu.be/_AzQf6iaSyg?t=286](https://youtu.be/_AzQf6iaSyg?t=286). I made sure I was in survival mode. This is where the issues start. First, when I switch to the villager egg in my hand, I don't see anything in chat. When I right click the air I do not see anything in chat, either. I can't do anything with the villager egg. 

I _can_, however, use the /shopkeeper command to create an admin shop. Since I want to create a player shop, I used /shopkeeper trading_shop. The response was that I need to select an admin shop type. I tried this command in both survival and creative, both didn't work. 

The issues are exactly the same in the brand new server I created (no plugins other than shopkeepers, all default settings). 

I know the plugin is up and running and I could not find any errors in the logs, which is why I am really confused as to why nothing appears when using the villager spawn egg.

* To try and reproduce the issue, just follow the spigot install instructions, start the server, stop the server, put shopkeepers in the plugins, and start the server again. Then try creating a player shop with the villager egg.

* This is the server log from the first start after I put in the shopkeepers jar (main server, not the one I used to reproduce): [https://pastebin.com/hKbtmEhF](https://pastebin.com/hKbtmEhF)

I have the following plugins installed:
WorldEdit, TNTTag, PlaceholderAPI, ScoreboardStats, HolographicDisplays, Multiverse-Core, Citizens, Shopkeepers, DiscordSRV, Multiverse-Inventories, CommandNPC, Multiverse-Portals, GriefPrevention, Multiverse-NetherPortals

**Comment by blablubbabc** [comment]
Since many users wanted regular villager eggs to work like regular, in newer versions of the plugin, I change the default shop-creation item from a regular villager egg to a villager egg with custom display name (see the `shop-creation-item` setting inside the config). So you will need to hold a villager egg with matching display name in order for the shop creation to work. You can give yourself such custom villager egg via the command `/shopkeeper give`.

Regarding player shop creation via command, see the wiki: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Creating-Shops#player-shops
* There is a config setting you need to enable first for this to work.
* You need to look at a chest when executing the command, otherwise the plugin assumes that you want to create an admin shop.

**Comment by blablubbabc** [comment]
I slightly updated the wiki to clarify this.

**Comment by atultw** [comment]
Thanks so much for the quick and helpful reply! So to make it work,

- If I am looking at a chest while using the command /shopkeeper Trading_shop, it will let me create a non-admin shop. (after enabling the option in config)

- For players to create shops without the command, they need to use /shopkeeper give to obtain the right villager egg and then do what was done in the video tutorial.

**Comment by blablubbabc** [comment]
> For players to create shops without the command, they need to use /shopkeeper give to obtain the right villager egg

Player usually have no access to the `/shopkeeper give` command (just like they have no access to regular villager eggs in vanilla Minecraft). You will typically have to setup some way for them to get access to this item, eg. buy setting up an admin shopkeeper which sells it.
