### ISSUE TITLE
[Feature Request] Restock time & per player limit

### ISSUE THREAD

**Issue by Uboaaaaa** [Shopkeepers/Shopkeepers#692]
Hello! I've been using shopkeepers for quite long and I have a few ideas to suggest.

For player shops:
- A cap on the total amount of purchases per player can make.

For admin shops:
- A cooldown mechanism much similar to how vanilla villager restock their trades. If x amount of purchase is made, player have to wait for y minute before the trade is made available again.

I ran a SMP server and sell some special items to my players using player shopkeepers. With admin shops it basically creates an infinite supply of an item which I don't wish to have too much on my server. With player shops however, the inventory is usually emptied by one particular group of rich players, leaving none for the rest of the community. So I'd like to have some sort of limit on the amount of purchases one can make, or at least on the frequency of their purchases. So that everyone will have the chance to get a piece.

**Comment by blablubbabc** [comment]
Sounds like a duplicate to https://github.com/Shopkeepers/Shopkeepers/issues/650 to me.
