### ISSUE TITLE
Glitch by trading items

### ISSUE THREAD

**Issue by Mast3rrr** [Shopkeepers/Shopkeepers#695]
## Preliminaries:

* **Shopkeepers version:** `2.2.1`
* **Spigot version:** `1.12.2`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`1.12.2`**) with the latest version of Shopkeepers (currently **`2.2.1`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
I have created a villager that need 64+32 diamonds to give the player an enchanted book (mending 1). There are 2 slots to put items. If the player put 64 diamonds at slot 1 and 32 diamonds at slot 2, the trade will work without issue but if the player put 32 diamonds at slot 1 and 64 diamonds at slot 2, diamonds of slot 1 are used for the trade but only 32/64 diamonds of slot 2 are used for thet trade (so when the player have done the trade, he have now the enchanted book AND 32 diamonds, a bit cheated)

* Step-by-step instructions on how to reproduce the issue.
I was in creative mode, I took from the inventory 2 stacks of diamond, that I placed like described above. And I did what I described above.

* Observed behavior.
A sort of "duplication" glitch

* Expected behavior.
The trade would work normally

* If items with special attributes are involved: Include instructions on how to create those items.
No

* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.

* If modified from default: Plugin configurations.
[config.txt](https://github.com/Shopkeepers/Shopkeepers/files/5312925/config.txt)

* .. Anything else that might be useful to reproduce and identify the issue.
It seems that this glitch only work if the items needed to trade are both the same:
I tried reproduce that glitch with 64 carrots and 32 potatoes for 5 emeralds, switching carrots and potatoes, the trade worked normally

**Comment by blablubbabc** [comment]
I assume this has already been fixed in v2.2.4: https://dev.bukkit.org/projects/shopkeepers/files/2928253

**Comment by Mast3rrr** [comment]
Oh I see, thank you =)
