### ISSUE TITLE
Shopkeeper rotation

### ISSUE THREAD

**Issue by Chestnut-Mum** [Shopkeepers/Shopkeepers#701]
## Preliminaries:

* **Shopkeepers version:** `2.8.1
* **Spigot version:** `<Insert output of /version command>`
---

I was able to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

So when I create a shop, the keepers only face in one direction and I cannot rotate them. I have seen it when the villagers move around freely and look around so that they are interactable from all sides.

**Comment by blablubbabc** [comment]
Update the shopkeepers plugin. This issue occurs if you run a version of Shopkeepers that is not compatible with your server version.
