### ISSUE TITLE
Shopkeepers aren't looking at you

### ISSUE THREAD

**Issue by Stanpaii** [Shopkeepers/Shopkeepers#703]
So.. I installed Shopkeepers and it was very easy to use even for somebody like me that has zero to none expierence using plugins, anyway there was a tiny problem that was actually quite annoying, the Shopkeeper doesn't track a nearby player. Im using it on 1.15.2 and idk if it was just a bug or a genuine error that needs ajusting anyway thats the problem

**Comment by blablubbabc** [comment]
Update the plugin to the latest version. This is a know issues if you are running an outdated version.
