### ISSUE TITLE
Shopkeeper v2.12.0 does not work on Paper-271

### ISSUE THREAD

**Issue by aaquino3** [Shopkeepers/Shopkeepers#708]
Hi,

I upgraded from Paper-268 (1.16.4) to Paper-271 and Shopkeepers no longer works due to the following errors:

https://pastebin.com/zjXkzcPs

I downgraded back to Paper-268 and Shopkeepers started working again

**Comment by aaquino3** [comment]
If I'm to guess what happened. It looks like they added ignore discounts API. Which is the first thing that Shopkeepers complained on line 2. I may be mistaken.

**Comment by blablubbabc** [comment]
Paper issue: https://github.com/PaperMC/Paper/issues/4753
