### ISSUE TITLE
Shopkeeper spawn eggs spawn Villagers named "Shopkeeper"

### ISSUE THREAD

**Issue by RalphORama** [Shopkeepers/Shopkeepers#709]
## Preliminaries:

* **Shopkeepers version:** `2.11.0`
* **Spigot version:** `Paper version git-Paper-253 (MC: 1.16.3)`
---

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`Paper version git-Paper-253 (MC: 1.16.3)`**) with the latest version of Shopkeepers (currently **`2.11.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

I'm running into an intermittent problem with the Shopkeepers plugin. Players on my server can buy shopkeeper eggs to spawn shopkeepers with, but, intermittently, the spawn egg functionality will stop working. This problem appears to start happening after the server restarts, but not *every* time the server restarts -- only occasionally.

I'm not sure what causes this intermittent failure, but the spawn egg functionality stops working entirely. When selecting the egg in the hotbar, no message about right clicking a chest appears, and using the egg in any capacity spawns a normal villager named "Shopkeeper."

The last time this became an issue, I deleted and re-generated my Shopkeepers config file, which fixed the problem temporarily. Now it's back, and I'm not sure what's causing it. I don't see any errors in console, and I haven't found any way to make the problem start or stop happening.

Despite eggs breaking, previously spawned shopkeepers continue functioning.

## More details

Here is an example of the issue: https://i.imgur.com/CrC4k8t.gifv

Server log: https://pastebin.com/CMFVk6xK

Shopkeepers `config.yml`: https://pastebin.com/Fzu9PY63

Plugin list: 

```
AngelChest, BlockLocker, BuycraftX, Chunkmaster, CommandPanels, ConsoleSpamFix, CoreProtect, DeathMessagesPrime, 
DiscordSRV, DragonDeathDrops*, DriveBackupV2*, EmojiChat, EmotePlugin3*, Essentials, EssentialsAntiBuild, EssentialsChat, 
EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExtraContexts, FastLeafDecay, GameModeInventories, GSit, HiddenLorax, 
HoneyPot, IllegalStack, LimitPillagers, LuckPerms, MarriageMaster, Matrix, mcMMO, MessageAnnouncer, MoreMeat, 
Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, OpenInv, Plan, PlayerHeads, ProtocolLib, PvPManager, SAML, 
SelectionVisualizer, ServerListPlus*, Shopkeepers, ShowItem, spark, StackMob, TimeControl, Vault, ViaBackwards, ViaVersion, 
VillagerModifications, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldResourcepacks
```

**Comment by blablubbabc** [comment]
The egg does not work if you are in creative mode. Can you check if this is the issue? At least in your video you seem to be in creative mode.

Regarding why this might have broken in the past, this might have been a different issue. For instance, Spigot made some changes to their internal item representation in 1.16 which might have affected these items. And I changed the default shopkeeper creation item at some point, which might have been affected you as well.

**Comment by blablubbabc** [comment]
Closing this. The issue has probably either been the creative mode, or that during the 1.16 update Spigot changed how it represents items internally, so that pre-existing items no longer matched what is setup in the config.

**Comment by TheKrafter** [comment]
Strange, I'm now experiencing this exact same issue, except on 1.20.4, shopkeepers 2.19.0.

(Not tryna necro this thread, just thought it was worth noting, just ignore me lol)

**Comment by blablubbabc** [comment]
> Strange, I'm now experiencing this exact same issue, except on 1.20.4, shopkeepers 2.19.0.
> 
> (Not tryna necro this thread, just thought it was worth noting, just ignore me lol)

Tracked by https://github.com/Shopkeepers/Shopkeepers/issues/866
