### ISSUE TITLE
Shopkeepers plugin doeesen't save nbt data correctly of an item after restart.

### ISSUE THREAD

**Issue by technomaniak** [Shopkeepers/Shopkeepers#712]
## Preliminaries:

* **Shopkeepers version:** `2.12.0`
* **Spigot version:** `git-paper-261`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

On my server, i created a generator for custom lore items.
I added it to a shopkeeper.
Server restarted and i couldnt trade with the item, even tho the lore and name mached.

i put this command: /summon item 989.40 27.50 1042.43 {Item:{id:light_gray_dye,Count:1,tag:{display:{Name:'{"text":"Moon Shard"}',Lore:["{\"text\":\"No one knows why it exists\"}"]}}}}
inside a commandblock that is powered each 6 ticks,

plugin config is not modified
latest log:
[latest.txt](https://github.com/Shopkeepers/Shopkeepers/files/5687158/latest.txt)

**Comment by blablubbabc** [comment]
This is a current limitation of the Spigot API (used by this plugin to save and load items).
See:
* https://github.com/Shopkeepers/Shopkeepers/issues/578
* https://hub.spigotmc.org/jira/browse/SPIGOT-5063

I have submitted a possible fix to Spigot, but that is still pending to be added. In the meantime a possible workaround is to stick to the data format that is produced by Spigot (i.e that you get after the plugin saved and reloads the item). You can also convert a held item to this format via the command `/shopkeeper convertitem`, or you adapt your summon command accordingly.

**Comment by technomaniak** [comment]
> This is a current limitation of the Spigot API (used by this plugin to save and load items).
> See:
> 
> * #578
> * https://hub.spigotmc.org/jira/browse/SPIGOT-5063
> 
> I have submitted a possible fix to Spigot, but that is still pending to be added. In the meantime a possible workaround is to stick to the data format that is produced by Spigot (i.e that you get after the plugin saved and reloads the item). You can also convert a held item to this format via the command `/shopkeeper convertitem`, or you adapt your summon command accordingly.

thanks!
