### ISSUE TITLE
Itemdata wrongly created

### ISSUE THREAD

**Issue by OmikronOverload** [Shopkeepers/Shopkeepers#713]
## Preliminaries:

* **Shopkeepers version:** `<Shopkeepers-2.12.0>`
* **Spigot version:** `<This server is running Paper version git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.

* .. Anything else that might be useful to reproduce and identify the issue.

On Putting Items with enchantments and text in the Shopkeepers Inventory its working fine, after a reload / restart the items are not saved correctly.
Putting Item in Shopkeepers Inventory reloading, giving me the same item, Item does not get accepted by the shopkeeper because of wrong data.
Saves the Item wrong on reload/restart.
Should still accept the item after reload/restart.
mythic mobs item config, reload MythicMobs then /mm give GefalleneSeele
 GefalleneSeele:
  Id: LIGHT_GRAY_DYE
[config.txt](https://github.com/Shopkeepers/Shopkeepers/files/5721323/config.txt)  This is what you need for the items in MythicMobs 
[latest.log](https://github.com/Shopkeepers/Shopkeepers/files/5721311/latest.log) My logfile
[config.txt](https://github.com/Shopkeepers/Shopkeepers/files/5721316/config.txt) my Shopkeepers config

**Comment by blablubbabc** [comment]
This is a current limitation of the Spigot API (used by this plugin to save and load items).
See:

    #578
    https://hub.spigotmc.org/jira/browse/SPIGOT-5063

I have submitted a possible fix to Spigot, but that is still pending to be added. In the meantime a possible workaround is to stick to the data format that is produced by Spigot (i.e that you get after the plugin saved and reloads the item). You can also convert a held item to this format via the command /shopkeeper convertitem, or you adapt your summon command accordingly.
