### ISSUE TITLE
[Feature request] A few small but important improvements for an adventure/RPG server - hiring shopkeepers

### ISSUE THREAD

**Issue by Vrath** [Shopkeepers/Shopkeepers#717]
Hello, I'm running a RPG server and it seems to be a great plugin, but I have a few issues:
1. I can set up shopkeepers for sale in the market, but then players will get to keep them forever unless I the mode to delete shopkeepers after they'll be inactive for some time, but first they must not login for that amount of time, and then I'll have to replace the shopkeeper manually. This doesn't really seem to be a good solution for me. **What if we could set shopkeepers to become available for sale again after a certain amount of time, ie. a week?**
2. It would also be nice if we could set up a hiring price for each shopkeeper individually. So the better spots in a village would be more expensive than those farther from the center.

**Comment by blablubbabc** [comment]
Yeah, the current 'set for hire' feature is not suitable for what you want to do with it. It permanently sells the shop. There is currently no feature to set shops 'for rent' (i.e. for use in pre-defined market areas). So this duplicates https://github.com/Shopkeepers/Shopkeepers/issues/3

Regarding 2: If I remember correctly, you can setup different hiring costs by holding different items in your hand when you use the item to set this up.

**Comment by Vrath** [comment]
So there's no chance for that simple implementation?

**Comment by blablubbabc** [comment]
Not any time soon now since I want to work on a few other things before that.
I also still have to think about whether I should completely remove the current 'set for hire' feature and replace it with that new 'for rent' feature, since I don't see much use for it either.
