### ISSUE TITLE
[Feature Request] A simple command to access Admin Shopkeepers GUI by id: this is usefull to make a GUI of stores with a third party plugin e.g.

### ISSUE THREAD

**Issue by rolley-network** [Shopkeepers/Shopkeepers#719]
## Preliminaries:

* **Shopkeepers version:** `2.12.0`
* **Paper version:** `git-PAPER-434`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
I think this is already available. See
* https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Commands#shopkeepers-remote-shopname-player
* https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Commands#shopkeepers-edit-shopname

If I remember correctly, the commands accept the shop's unique id, session id (smaller, but not necessarily the same across sesions), name (not necessarily unique or available), or you can specify the shop by looking at it.
