### ISSUE TITLE
Is it possible to use economy for shopkeeper? 

### ISSUE THREAD

**Issue by Chris1887x** [Shopkeepers/Shopkeepers#721]
Is it possible to use economy for shopkeeper?

**Comment by Chris1887x** [comment]
instead of items to buy stuff

**Comment by blablubbabc** [comment]
Nope. See also https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions#will-you-add-support-for-currency-plugins-integrate-with-vault
