### ISSUE TITLE
Infinite Money bug

### ISSUE THREAD

**Issue by FilthyCasualOfficial** [Shopkeepers/Shopkeepers#723]
When players sell with Item in left hand it doesnt take item but sells infinitely.

**Comment by blablubbabc** [comment]
> When players sell with Item in left hand

I don't understand what you mean by that. Players have to insert their sold items into one of the two villager input slots to trade. So can you please clarify what exactly are you doing, step by step, what you observe, and what you expect to happen instead? Maybe also attach a screenshort or short video.

**Comment by blablubbabc** [comment]
I was not able to reproduce selling items from the offhand slot. In my testing, only the items from the input slots were involved and accepted in the trade.
If you have further information that could help to reproduce the issue you trying to describe, let me know.
