### ISSUE TITLE
PlotSquared support

### ISSUE THREAD

**Issue by maedakatoo** [Shopkeepers/Shopkeepers#724]
For example on plot clear/delete shopkeeper will deleted; on plot unmerge shopkeeper will deleted;

**Comment by blablubbabc** [comment]
If you enable `delete-shopkeeper-on-break-container` inside the config, player shopkeepers can already be automatically removed when their shop chest is broken by another plugin (such as when the plot is cleared). Does this suffice your needs?

**Comment by maedakatoo** [comment]
> If you enable `delete-shopkeeper-on-break-container` inside the config, player shopkeepers can already be automatically removed when their shop chest is broken by another plugin (such as when the plot is cleared). Does this suffice your needs?

i've tries this, the shopkeeper respawns at that plot if another player claimed this plot
