### ISSUE TITLE
Player Shops not working

### ISSUE THREAD

**Issue by plqsticflower** [Shopkeepers/Shopkeepers#725]
## Preliminaries:

* **Shopkeepers version:** 2.12.1`
* **Spigot version:** `<versioInsert output of /version command>`
---
I'm not sure about Spigot when i put the command in it says the server is running Paper version git-paper-"b89788a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue: I've been trying to allow players to create shops. No matter what i do that permission never works. I've tried luckperms and permissionsex doing shopkeeper.player and shopkeeper.player.sell i've set it to true and looked in my folder to see if it was showing up and it is. the player shop command doesn't show up when you do the help command unless you're op. 
Also I'm on a Minehut server. The admin shops works perfectly though. I can't even create a selling shop, it will tell me it has to be an admin shop for non ops it just says they don't have permission even though its been set to true. I've tried adding some of the other permissions but the player shop permissions just aren't working. 

my other plugins are
ClearLag
Essentials
EssentialsChat
EnssetialSpawn
HolographicDesplays
Images
PermissionsEx or LuckPerms
vault
Villages
WorldEdit
WorldGuard

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
Have you read and followed the instructions from the wiki: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Creating-Shops#player-shops

Regarding permissions: You usually don't have to change anything on the permissions. Players will have access to player shops by default.
Regarding creating player shops via command: You have to first enable that inside the config with the setting `create-player-shop-with-command`.
Regarding `it will tell me it has to be an admin shop`: You are probably not targeting a chest when you execute the command. If you look at a regular block, the command will assume that you are trying to create an admin shop. To create a player shop you will have to look at a chest when you execute the command.

**Comment by blablubbabc** [comment]
I assume that this issue is resolved. If this is not the case, or you have further questions/difficulties, let me know.
