### ISSUE TITLE
Support for GeyserMC?

### ISSUE THREAD

**Issue by Matthew-MBG** [Shopkeepers/Shopkeepers#730]
Lots of servers use GeyserMC so bedrock players can join, but apparently they can't open shopkeepers. (Tested on an Xbox One WITH op and perms). I would love to see support for this plugin, and it would really help my server!

**Comment by blablubbabc** [comment]
I am not familiar with GeyserMC or the Bedrock Minecraft client, so if there is an issue with this combination, consider asking the GeyserMC developers, or someone else that is familiar with it, for help. If someone can provide a clear description of any particular issue, its cause, and instructions on how to resolve it, I am willing to look into making the required changes. However, I won't be debugging issues with GeyserMC myself.

**Comment by Matthew-MBG** [comment]
woops accidentally posted it twice
