### ISSUE TITLE
how can i sell things by diamond 

### ISSUE THREAD

**Issue by MiranSamurai** [Shopkeepers/Shopkeepers#734]
i want to sell things by emerald but i want to sell things by diamond

**Comment by blablubbabc** [comment]
Either use a trading shopkeeper (https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Player-Shop-Setup#trading-shop), which allows you to trade arbitrary items, or change the `currency-item` and `high-currency-item` inside the config (https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration).
