### ISSUE TITLE
[Feature Request] Blacklisted currency items.

### ISSUE THREAD

**Issue by EvilPandaMan** [Shopkeepers/Shopkeepers#737]
Could you please add an option in config that allows you to blacklist an item to be used as currency? Also not to be allowed to be used as trade?

**Comment by blablubbabc** [comment]
This sounds like this to me: https://github.com/Shopkeepers/Shopkeepers/issues/417

However, you will have to clarify what exactly you mean (is there a difference between 'blacklist an item to be used as currency' and 'not to be allowed to be used as trade'), and why this is needed / what problem this is supposed to solve.
Consider posting your description of this in the linked ticket.
