### ISSUE TITLE
Mohist: Trading inventory immediately closes when trying to trade

### ISSUE THREAD

**Issue by VixterGarcia** [Shopkeepers/Shopkeepers#738]
When trying to trade with an Admin type shopkeeper the trade will fail and in the console will appear this message: 

"Closing inventory of type CHEST with title '§2Villager' for VixterGarcia, because a different open inventory was expected for 'trading'"

The server is also modded with Mohist in the 1.16.5 version and the currency is from a mod. (But even when trying to trade for an emerald it won't work)
Could anyone help?

(The version of the plugin is the 2.12.0)

**Comment by blablubbabc** [comment]
I do not provide support for modded server types other than Spigot: I am not familiar with those and don't want to spend to much effort and time looking into all their internal differences.

However, in case of this particular issue:  
Mohist seems to report an incorrect inventory type ('CHEST') when the trading menu is opened. Shopkeepers checks the inventory type to make sure that everything is going as expected (eg. that no other plugin is interferring by opening another inventory). Once Shopkeepers encounters this unexpected inventory type it assumes that something went wrong and aborts the trading.

The next version will include a new config setting `disable-inventory-verification` with which you can disable this check.

If you don't want to wait for this version to be released, you can also use the latest snapshot version (https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.13.0-SNAPSHOT/Shopkeepers-2.13.0-20210501.171744-2.jar). However, this snapshot also contains several other changes that are still prone to change until the final release of 2.13.0. Depending on the changes that are yet to come, upgrading from this snapshot to the actual v2.13.0 version later might not be supported. See the full changelog and migration notes so far here: https://github.com/Shopkeepers/Shopkeepers/blob/master/CHANGELOG.md.
