### ISSUE TITLE
Disabling a command

### ISSUE THREAD

**Issue by ZarameJake** [Shopkeepers/Shopkeepers#741]
Hello I'm wondering if there is a way to disable the /shopkeeper give command?

I want to have a limited number of player shops on my server. I have already limited how many shops there are per player, but was wondering if there is a way to prevent players from personally spawning in the egg. 

I tried to post a comment on the curseforge page, but it wouldn't let me.

v2. 12. 0 for 1.16.5 bukkit minecraft

**Comment by blablubbabc** [comment]
The command is only accessible by players with operator permission level by default. So either your players are operators, or you are using a permissions plugin and have given them access to the command. So you have to adjust your permissions setup to remove their permission from using the command.
