### ISSUE TITLE
Fail close the server!

### ISSUE THREAD

**Issue by Carlosdc05** [Shopkeepers/Shopkeepers#751]
When i try to Shift + right click the server just get close [
[2021-06-17-1.log.gz](https://github.com/Shopkeepers/Shopkeepers/files/6701056/2021-06-17-1.log.gz)
](url)

**Comment by blablubbabc** [comment]
This looks like a server bug to me. Also, there is no mention of Shopkeepers inside this log.

Please try to reproduce your issue on the latest version of Spigot. You need to build Spigot via their BuildTools for this: https://www.spigotmc.org/wiki/buildtools/
