### ISSUE TITLE
[1.16.5 / Mohist 674 / Shopkeepers v2.13.0 ]  bug exchange interface

### ISSUE THREAD

**Issue by RealWeZz** [Shopkeepers/Shopkeepers#752]
When I try to make an exchange with a shopkeeper the interface opens and when I click on a block it closes automatically could you please help me

**Comment by blablubbabc** [comment]
See https://github.com/Shopkeepers/Shopkeepers/issues/738
On Shopkeepers v2.13.0 there is a new setting `disable-inventory-verification` with which you can resolve this.
