### ISSUE TITLE
How can I set wandering traders so that they can randomly brush around players?

### ISSUE THREAD

**Issue by RsatoL** [Shopkeepers/Shopkeepers#753]
I want to have some wandering traders with random custom transactions refresh around the players randomly

**Comment by blablubbabc** [comment]
You cannot configure the trades that wandering traders randomly spawn with with this plugin. There is an [editor](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Editor-for-regular-villagers) with which you can modify the trades to some extent of a specific wandering trader that has already spawned, but anything else is out of scope of this plugin. This plugin's purpose is primarily to set up stationary shops.
You will have to look for another plugin that provides this functionality. Though I am not aware of such a plugin currently.
