### ISSUE TITLE
How to use Chinese name for the villager

### ISSUE THREAD

**Issue by maque-zzh** [Shopkeepers/Shopkeepers#760]
Hi,when i use Chinese name for the villagers in this plugen it said “That name is not valid！”
I want know how to fix it.

Thank you.

## Preliminaries:

* **Shopkeepers version:** `<Insert Shopkeepers version>`
* **Spigot version:** `<Insert output of /version command>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
Try setting `name-regex: "[\p{L}0-9 ]{3,25}"` inside the config. The `\p{L}` portion should allow you to use any 'letters' within shopkeeper names. If you want to limit it to chinse letters specifically, you will need to check if there is a 'Unicode script' / section that specifically contains these chinese characters. Maybe `name-regex: "[\p{IsHan}0-9 ]{3,25}"` works.
