### ISSUE TITLE
MC support for 1.17.1

### ISSUE THREAD

**Issue by michaldemjancuk** [Shopkeepers/Shopkeepers#766]
## Preliminaries:

* **Shopkeepers version:** `2.12.0`
* **Spigot version:** `1.17.1`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)`**) with the latest version of Shopkeepers (currently **`2.12.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

_Plugin as is is not supporting version 1.17.1_

[03:50:49 INFO]: [Shopkeepers] Enabling Shopkeepers v2.12.0
[03:50:49 ERROR]: [Shopkeepers] Incompatible server version: Shopkeepers cannot be enabled.

**Comment by blablubbabc** [comment]
The latest version of Shopkeepers is v2.13.3, which has support for MC 1.17.1. See the compatible MC versions listed for each file at https://dev.bukkit.org/projects/shopkeepers/files
