### ISSUE TITLE
1.18 compatibility

### ISSUE THREAD

**Issue by celophys** [Shopkeepers/Shopkeepers#767]
The plugin is not compatible with 1.18, using the last version, it shows an error in chat, will it be updated?

**Comment by LilianLem** [comment]
The last dev build is compatible with 1.18, but you need to download it in GitHub Actions : https://github.com/Shopkeepers/Shopkeepers/actions/runs/1529147056
Click on "artifact" at the bottom of the page, you will get a zip file with the jar you need in it.

**Comment by celophys** [comment]
Oh ok thanks!

**Comment by blablubbabc** [comment]
v2.14.0 with support for MC 1.18 and 1.18.1 is now available on dev.bukkit.org and spigotmc.org, so this should be resolved.
