### ISSUE TITLE
Trade limit for admin shops

### ISSUE THREAD

**Issue by SignorPollito** [Shopkeepers/Shopkeepers#768]
Feature request:

The possibility to add a limit to a trade in admin shops.
It will restrict the amount of times that the trade can be used by all players.

For example:
An admin shop has a trade with a maximum of 10 uses.
After it has been used 10 times, it will be blocked and no one would be able to use that trade anymore.

Another feature would be to add a command or a GUI to reset and modify those limits.

**Comment by blablubbabc** [comment]
Do you have example scenarios in which this features would be useful? I.e. why would you want to setup an admin shop (the definition of which is 'a shop with infinite supplies) and then limit how often a trade can be used?

Also, you can already create player shops (and hide the chest somewhere if you want) to create shops with limited supply: If you only add 10 items to sell into the chest, a trade to buy one of those items can only be used 10 times. And you can easily 'reconfigure' the trade limit by changing how many items you add or remove from the chest.

I think this is far easier to setup in-game, compared to cluttering the editor or commands with more options to edit the limits of individual trades. And it doesn't require any further changes.

**Comment by blablubbabc** [comment]
This might be a duplicate.
* There is already an older ticket mentioning trade/stock limits for admin shops, with the focus on automating the task of periodically refill the stock. https://github.com/Shopkeepers/Shopkeepers/issues/403
* For per-player trading limits, there is some discussion on this in this ticket: https://github.com/Shopkeepers/Shopkeepers/issues/650
