### ISSUE TITLE
Option to choose how to select shop types.

### ISSUE THREAD

**Issue by ryantheleach** [Shopkeepers/Shopkeepers#771]
I've previously maintained a fork for my own use, that changes how shops are created.

Our server only ever uses Trading shops, so the ability to select shop type is unused.

Newer players were confused by the interface of having to sneak, since there was only 1 shop type, and remarked they wished they didn't have to sneak.

So my fork would simply remap the change avatar function to left and right click, and the sneaking to changing the shop type (as only admins and mods ever changed the shop types).

I would appreciate it if this became a configuration option I could choose, instead of updating that fork.

**Comment by blablubbabc** [comment]
https://github.com/Shopkeepers/Shopkeepers/commit/24bc538bc4c34ccf84be3ecc9ca805b03f4da3c9

**Comment by ryantheleach** [comment]
Thanks for the speedy response! <3

**Comment by blablubbabc** [comment]
Added in v1.15.1
