### ISSUE TITLE
Add ability to teleport shopkeepers

### ISSUE THREAD

**Issue by d1rty-pixel** [Shopkeepers/Shopkeepers#772]
Hello,

we would like to request a feature to the plugin to enable users to teleport shopkeepers from their current location to another (either with coordinates, pitch and yaw, or maybe "here" - or something like that).

Thank you & all the best
on behalt of Cube-Nation staff

**Comment by blablubbabc** [comment]
Duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/361

There is currently some work being done that fixes some remaining issues related to implementing this, which also fixes a few currently present issues with moving Citizens shopkeepers (those can already be moved, but moving them does not correctly work in some situations currently).
