### ISSUE TITLE
Is supported on geyser?

### ISSUE THREAD

**Issue by AskingSamagra** [Shopkeepers/Shopkeepers#775]
Is this plugin supported on geyser? I didn't find anything anywhere. Geyser as the plugin version for paper 1.18.1 and if it is please let me know how you can reproduce the left clicking and right clicking in inventories on mobile.

**Comment by blablubbabc** [comment]
I don't provide support for issues related to geyser or bedrock clients. You can try if Shopkeepers works with geyser, but if you run into any issues you will have to ask the geyser devs about it.
