### ISSUE TITLE
[Feature Request] Allowed shop types

### ISSUE THREAD

**Issue by RedSparr0w** [Shopkeepers/Shopkeepers#777]
- [x] I have checked that my issue/question does not get answered by:
  - [x] The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  - [x] The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  - [x] The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
- [x] I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

### Description of the feature.
Allow enabling/disabling of specific shop types through the config files, similarly to how the allowed mob types are handled.

```yml
enabled-shop-types:
- ADMIN
- BUYING
- SELLING
- TRADING
- BOOKS
```

Although I assume admins/ops would still be able to create any shop type, so `ADMIN` may not need to be included.

**Comment by blablubbabc** [comment]
The proper way to limit the access to certain shop types is to use a permissions plugin and configure which shop types your players have access to. If you don't want to use a full-fledged permission plugin, you can also configure simple default permissions via Bukkit's built-in `permissions.yml` file. I currently don't see the need for a setting to completely disable certain shop types.

The reason there are settings for the enabled shop object types inside the config is not for access control (i.e. controlling which shop objects types players can use), but:
* Test out new mob types (e.g. after minecraft updates) to see if they are even suitable to be used as shopkeepers.
* Disable shop object types that cause some problems, such as incompatibilities with other plugins, performance issues, etc.

As far as I am currently aware, the enabled shop types are not affected by any such problems.

**Comment by RedSparr0w** [comment]
Sorry, not sure how I missed that!

Thanks for the quick response 👍
