### ISSUE TITLE
when i'm trying to place a villager out it gives me the message an internal error occurred while attempting to perform this command 

### ISSUE THREAD

**Issue by Assuredyard** [Shopkeepers/Shopkeepers#778]
## Preliminaries:

* **Shopkeepers version:** `newest`
* **Spigot version:** `im using paper in minehut`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help to reproduce the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* ... Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
Without further information (exact server and plugin versions / build numbers, and a complete server log that includes the server startup and the mentioned error), I am not able to help.

**Comment by blablubbabc** [comment]
Closing this as no information has been provided that would allow me to reproduce or investigate the issue.
