### ISSUE TITLE
Add an option to disabled raids from spawning because of shopkeepers

### ISSUE THREAD

**Issue by PapiCapi** [Shopkeepers/Shopkeepers#779]
## Preliminaries:

* **Shopkeepers version:** `2.14.0`
* **Spigot version:** `This server is running Paper version git-Paper-130 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: eb98398)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`git-Paper-130 (MC: 1.18.1)`**) with the latest version of Shopkeepers (currently **`1.14.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
It would be cool to add a config option to prevent raids from spawning where there are only shopkeepers ( of type villager ).

**Comment by blablubbabc** [comment]
I remember to have looked into this in the past to confirm that shopkeeper villagers already do not cause raids to start: They have their AI disabled (Minecraft's `NoAI` flag), which prevents them from searching for / creating villages / occupying beds and work station blocks (which Minecraft uses to identify villages), which is what starts raids.
To confirm this: Temporarily remove the Shopkeepers plugin and see if you can still reproduce the raid starting.

**Comment by PapiCapi** [comment]
Thanks for the quick reply ! 
As you've said, the issue is not related to shopkeepers, sorry for the false issue. I'll try to remove all work stations blocks and see if this is still happening.
