### ISSUE TITLE
Name Invalid

### ISSUE THREAD

**Issue by shraviscool** [Shopkeepers/Shopkeepers#781]
## Preliminaries:

* **Shopkeepers version:** `Newest`
Newest Paper Version
---

I was not able to reproduce my issue on a freshly set up and up-to-date Spigot server  with the latest version of Shopkeepers with no other plugins and with no kinds of other server or client mods.

## The issue:

Whenever I try to change the name of a shopkeeper it says "name invalid". There is nothing wrong with console and the names of the old shopkeepers are fine but they wont change if i try to change them. There are no warnings or issues with console.

https://user-images.githubusercontent.com/76776247/153775799-5cac601a-3887-4335-bda4-6a9f0fdd31b2.mp4

**Comment by shraviscool** [comment]
Hope it gets fixed!

**Comment by blablubbabc** [comment]
There has been a known issue in combination with the plugin [ChatColor](https://dev.bukkit.org/projects/chatcolor-s) (see https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues), but this may also apply to other plugins on your server: This plugin automatically insert color codes (possibly the white color code, so this may not be immediately apparent in chat) into the chat messages of players. By default (unless enabled inside the config), shopkeeper names cannot contain color codes, so the name is rejected.
If you are not using this mentioned plugin, other plugins on your server (especially chat plugins) can cause similar issues if they modify the chat messages of players.

> Shopkeepers version: Newest

There has been a change in Shopkeepers v2.14.0 to resolve this kind of plugin incompatibility.  
Additionally, if you are using the default language file, the "name is invalid" message has been changed in v2.14.0 to mention the apparently invalid name. This should also make it clearer if some other plugin inserts color codes into the entered name.

So make sure that you are actually using the latest version of the Shopkeepers plugin.

**Comment by blablubbabc** [comment]
Closing this as no further information was provided. I think the latest version of Shopkeepers should already have resolved this particular issue. If not, I need further information on which other plugin is responsible for this incompatibility to see if it can be resolved.
