### ISSUE TITLE
internal errors? 

### ISSUE THREAD

**Issue by Wypman1** [Shopkeepers/Shopkeepers#785]
i am on a fresh server (started about an hour worth of basic worldedit setups and want to do shopkeepers, but typing the command /shopkeeper just says "an internal error occurred while attempting to perform this command" so i really have no idea whats going wrong or why it isnt working, and i wouldnt be confused if the problem lies in minehut the host rather then the plugin itself but im too noob to really know whats going on besides it not working
minehut says the server is spigot version 1.18.2 and the plugin version isnt known to me (or at least i dont know how/where to find it, it just says "shopkeeper" on the plugins list (which is the plugins name)) 

sorry if this error/report is done wrong, i wish it would work so i didnt have to give the report but it is what it is unfortunately 
thanks a lot for the help already, it does mean a lot to me
![error](https://user-images.githubusercontent.com/101055642/156929794-b8f2013a-0db3-427c-91cc-190d0f42682b.png)

**Comment by blablubbabc** [comment]
Regarding the error: Without the server log containing the error there is nothing I can do.

Regarding Minehut: I have no idea if or how you can access the server log there. However, other users have reported issues with running the plugin on Minehut before. The last time someone mentioned that Minehut only offered an outdated version of the Shopkeepers plugin. But I am not familiar with the interface, so youwill need to check for yourself if you can figure out which version of Shopkeepers they offer. If that is still the case, this would be something for them to update.

Regarding 1.18.2: This Minecraft version is not yet properly supported by Shopkeepers. According to reports by other users, the latest version of Shopkeepers (v2.14.0) appears to work for the most part, but shopkeeper mobs do not turn their head towards nearby players.

**Comment by Wypman1** [comment]
Thanks for the help, but im not fully sure myself checking it on minehut
either, but i think with some time things could improve when minehut
updates it all?


Op zo 6 mrt. 2022 17:26 schreef blablubbabc ***@***.***>:

**Comment by blablubbabc** [comment]
Without a full server log I have no idea what is going wrong. Could be an outdated plugin version, or could be something else.
