### ISSUE TITLE
Question: Is it possible to edit the trades of all villagers that spawn?

### ISSUE THREAD

**Issue by jmancox330** [Shopkeepers/Shopkeepers#787]
## Preliminaries:

Shopkeepers Version: 2.14.0
Spigot Version: 1.16.5

Is it possible to make it so villagers that spawn can automatically have custom trades based off of their profession?

**Comment by blablubbabc** [comment]
Nope. There are also no plans to add such features. See: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions#can-you-instead-just-rebalance-or-let-admins-configure-the-trade-options-of-regular-villagers
