### ISSUE TITLE
Option to block putting in items direcly.

### ISSUE THREAD

**Issue by CloudeLecaw** [Shopkeepers/Shopkeepers#793]
We are using the shopkeeper addon for economy support.
We run into the issue that if players put in the item direcly into a slot then choosing the offers from the left site
that they have issues there when u have a shop that sells items for economy.

Since the site itself cant offer so much updates anymore because thair staff is reduced to one man now it would be nice
to have a a secound solution to block
insering the blocks direclty

![image](https://user-images.githubusercontent.com/12080017/165475687-9e82bb58-4250-4bf2-a580-df6bcedfc7ad.png)

Note: with normal Item for Item shops (normal shopkeepers) this does not happen.

Well here is a little video that shows the issues with the addon:
https://streamable.com/9wnbom

So if we could block direct insering of blocks we could "fix" the issues for this.

So could it be added as optional setting?

**Comment by blablubbabc** [comment]
This is something for the add-on developers to look into.

**Comment by CloudeLecaw** [comment]
Well thats why i asked for it as optional setting for shopkeepers to disable this direct input.

1. It would be like a secound solution if its still not possible to drag items in the slot.
2. Im accutally not sure if the dev can handle it, but i see more and more people that asks for economy with shopkeepers. So the addon is/was like a charming dream of many :)

**Comment by blablubbabc** [comment]
I have economy integration on my todo list, but you will have to wait until I find the time to look into this myself. But I won't add settings/features to the Shopkeepers plugin whose sole purpose it is to fix/workaround bugs that are clearly the responsibility of an other plugin.

**Comment by blablubbabc** [comment]
By the way, preventing players from entering items directly into the trade input slots is not necessarily specific to the Shopkeepers plugin. Any third-party plugin developer with some time available should be able to put together a minimal plugin to achieve this. If something doesn't serve a purpose within the Shopkeepers plugin itself, or is independent enough to be achieved via a separate plugin, or is specific to a particular server or setup, I won't add it to the Shopkeepers plugin itself.

Usually I don't have the time or motivation to work on requests that are quite specific to a particular server or setup. My time is rather limited, and there are enough other things that I would rather spend it on. That being said, here is a little plugin that might do what you ask for: https://github.com/blablubbabc/EnforceVillagerTradeSelection/releases/tag/v1.0.0
It has only been tested briefly.

**Comment by CloudeLecaw** [comment]
So Admins have soe kind of bypass? just asking because with the allperms rank i can insert the items. but as player its great!

So it looks like there is a permission or something in it? :)

**Comment by blablubbabc** [comment]
The readme mentions a permission for a bypass.

**Comment by CloudeLecaw** [comment]
I found it. 
Thank you for this little charm <3
It does exacly whatbwe needed to have a current fix for the addon.

May the dev can fix the addon fom his site soon too :)
