### ISSUE TITLE
Incompatibility issue with mohist

### ISSUE THREAD

**Issue by YassevZriona** [Shopkeepers/Shopkeepers#797]
Shopkeepers Version: 2.15.1
Server Software: Mohist version 1.16.5-1012 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)

Issue: I find shopkeepers incompatible with mohist. can support for mohist be added please?

**Comment by blablubbabc** [comment]
I do not intend to provide support for Mohist or other kinds of modded servers other than Spigot (and Paper to some degree).
