### ISSUE TITLE
Players kicked when entering 1.18.2 server on 1.19 through ViaVersion and opening certain shops

### ISSUE THREAD

**Issue by MithrandirCraft** [Shopkeepers/Shopkeepers#799]
## Preliminaries:

* **Shopkeepers version:** `2.15.1`
* **Spigot version:** `git-Paper-379 (MC: 1.18.2)`
---
## The issue:

Players kicked when entering 1.18.2 server on 1.19 through ViaVersion and opening certain shops.

1. Install blank 1.18.2 paper server.
2. Install Shopkeepers on it + dependencies.
3. Install ViaVersion.
4. Add the following shop to Shopkeepers/data/save.yml: https://www.toptal.com/developers/hastebin/lazetafati.yaml
4. Enter the server using 1.18.2: notice the shop functions perfectly.
5. Enter the server using 1.19.X: notice your client crashes with the following client error message:
![imagen](https://user-images.githubusercontent.com/6623704/174484513-6473155f-474b-421e-9b1f-a2f6043d03a1.png)

No errors show up on console. This seems to be 100% client related. Maybe even irrelated to Shopkeepers, and more related to ViaVersion.

**Comment by blablubbabc** [comment]
This is something for the ViaVersion devs to look into.

**Comment by MithrandirCraft** [comment]
This is fixed when updating ViaVersion to 4.3.2-SNAPSHOT

**Comment by Saanjuk** [comment]
Spmetimes error has diferent content:
![image](https://user-images.githubusercontent.com/72826340/178157416-b3b22fe0-de77-4586-939a-a3e568853bd3.png)
