### ISSUE TITLE
Shopkeepers holding items

### ISSUE THREAD

**Issue by WalmartAdine** [Shopkeepers/Shopkeepers#801]
I do not know how difficult/possible this would be but it would be cool if shopkeepers could hold/wear a item such as giving a zombie shopkeeper armor and like a sword for example

**Comment by WalmartAdine** [comment]
im sorry i dont got the feature tag thing i dont really understand how github works so i cant figure out how to get it on my post

**Comment by blablubbabc** [comment]
There is already another ticket keeping track of this feature idea: https://github.com/Shopkeepers/Shopkeepers/issues/596
