### ISSUE TITLE
Shopkeepers NBT issue when requiring multiple custom items 

### ISSUE THREAD

**Issue by tiarnia** [Shopkeepers/Shopkeepers#802]
* **Shopkeepers version:** `2.16.0`
* **Spigot version:** `paper 1,19-39`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

When using 2 custom items or 1 custom item and another normal item in trades Client gets disconnected when clicking the npc and gets an Internal Exception io.netty.handeler.codec.DecoderExeption: z: Loading NBT data 

![image](https://user-images.githubusercontent.com/16805000/175838293-4dbbd7af-e5f6-4b4d-be81-850d148fed45.png)

![image](https://user-images.githubusercontent.com/16805000/175838309-18d9d2b0-4261-4339-8cd5-a932452bd714.png)

**Comment by tiarnia** [comment]
it was happening on the 1.18.2 server for anyone using the 1.19 client before (1.18 clients didn't have the issue)

**Comment by tiarnia** [comment]
![image](https://user-images.githubusercontent.com/16805000/175838604-3ba61253-7e18-4cb3-a569-bc39f2d92afd.png)

also gets this depending on what items i put in for cost  if i use just use 1 item its fine

**Comment by blablubbabc** [comment]
Another issue ran into the same issue and it turned out that this was caused by ViaVersion. So try reproducing this issue without ViaVersion.
If you can confirm ViaVersion to be the issue, I think to remember that some newer version of it resolved the issue for this other user.
