### ISSUE TITLE
the normal villagers doesnt take dropped items like carrots or potatoes

### ISSUE THREAD

**Issue by Gregoryxnmasd** [Shopkeepers/Shopkeepers#812]
* **Shopkeepers version:** `2.15.1`
* **Spigot version:** `1.19.2 R0.1`
---

**the normal villagers doesnt take dropped items like carrots or potatoes**

**Comment by blablubbabc** [comment]
Can you provide more specific reproduction steps?

What do you mean by "normal" villagers? Villager shopkeepers, or non-shopkeeper villagers?
In case of normal villagers: Have you modified the trades of the villager, for example via the editor?

**Comment by blablubbabc** [comment]
Closing this as no further information was provided.
