### ISSUE TITLE
Buying for nothing

### ISSUE THREAD

**Issue by Tobik-k** [Shopkeepers/Shopkeepers#814]
Hi, could you please add feature that shopkeeper will buy something from player, but not giving anything back? It would be super useful. It seems like a dumb idea, but it would be great for triggering redstone contraptions.

**Comment by Tobik-k** [comment]
For example, you could use it in casino. Player will buy nothing for diamond, diamond is then placed in chest. System can find out if there is a diamond and trigger slot machine. Diamond is then being sent through hoppers to another chest, so you can do it again. But you need to have something for exchange in the chest, which is not problem if you are using only diamonds (if u use filter under the chest). But, problem arises when you try to use any non-stackable items or more than 2 stackable. If you could give the player nothing for exchange, it solves a lot of problems. And you can use more ways of paying (netherrite, gold, iron, etc.).

**Comment by blablubbabc** [comment]
> For example, you could use it in casino. Player will buy nothing for diamond, diamond is then placed in chest. System can find out if there is a diamond and trigger slot machine. Diamond is then being sent through hoppers to another chest, so you can do it again. But you need to have something for exchange in the chest, which is not problem if you are using only diamonds (if u use filter under the chest). But, problem arises when you try to use any non-stackable items or more than 2 stackable. If you could give the player nothing for exchange, it solves a lot of problems. And you can use more ways of paying (netherrite, gold, iron, etc.).

If you only want to transfer the items from the player into a chest, why not let them drop the items directly into a hopper that moves them into the chest? You could still place a NPC next to that for the ambience.

**Comment by Tobik-k** [comment]
> > For example, you could use it in casino. Player will buy nothing for diamond, diamond is then placed in chest. System can find out if there is a diamond and trigger slot machine. Diamond is then being sent through hoppers to another chest, so you can do it again. But you need to have something for exchange in the chest, which is not problem if you are using only diamonds (if u use filter under the chest). But, problem arises when you try to use any non-stackable items or more than 2 stackable. If you could give the player nothing for exchange, it solves a lot of problems. And you can use more ways of paying (netherrite, gold, iron, etc.).
> 
> If you only want to transfer the items from the player into a chest, why not let them drop the items directly into a hopper that moves them into the chest? You could still place a NPC next to that for the ambience.

Yes, I could. But players like to glitch these filters. Shopkeeper is the best, unglitchable filter. And it works with non-stackable items too. Please add this feature, it will open whole new world to redstoners like me :)

**Comment by blablubbabc** [comment]
This will be possible with Shopkeeper v2.19.0 (release date pending) by using the new `/shopkeeper setTradedCommand <command>` command to set up an item that will execute some command when traded, instead of being given to the player or shopkeeper. One could for example assign the item some dummy command such as `/shopkeeper settradedcommand tellraw {player_name} "Items received. Thank you."`, and this will then execute the command instead of handing out the item.
