### ISSUE TITLE
Feature request Libs Disguises

### ISSUE THREAD

**Issue by xPhantoMTVx** [Shopkeepers/Shopkeepers#816]
Hi

Is is possible for Shopkeepers plugin to support LibsDisguises?
I would like to save any disguise, so villager can be shown as the player.

**Comment by blablubbabc** [comment]
> I would like to save any disguise, so villager can be shown as the player.

Can you clarify what exactly you are trying to do? There is already an integration with the Citizens plugin that allows you (and your players if you enable it) to create 'npc' shopkeepers that look like a player (or like the shop owner in the case of player shops).

**Comment by blablubbabc** [comment]
There are currently no plans to add an integration with LibsDisguises. If you want to display shopkeepers as players, the only supported mechanism currently is to also install the Citizens plugin and spawn a `npc` shopkeeper. See https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Citizens-Shopkeepers
