### ISSUE TITLE
Youtube / Persian Plugin Tutorial

### ISSUE THREAD

**Issue by LastKing2X** [Shopkeepers/Shopkeepers#826]
**Hello There !**
I am a new youtuber and i show toturials of plugins
my first video is about Shopkeeper and i show this to **IRANIAN** viewers !
you can really help me with suggest my video in your spigot and bukkit post as a **Persian** language tutorial !
can you do that ?

Link of video : https://www.youtube.com/watch?v=IV8BVhRI3S8&t=37s

Thanks for reading ❤️

**Comment by blablubbabc** [comment]
Hey, thank you for making the video!
Unfortunately, I can only add very few videos to the project page, otherwise the page becomes messy, and page loading would be affected. But I have added your video for now, replacing one of the others.
