### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by Godwhitelight** [Shopkeepers/Shopkeepers#827]
## Preliminaries:

* **Shopkeepers version:** `2.16.5`
* **Purpur version:** `1632 1.18.2`
---

Some of my players on a server am coding for found this dupe bug.

# How to repreduce
This bug works only on shopkeepers who sells stuff using any money. (you need a villager that sells stuff for money and smth else).
So you need to have alot of lags on the client side (the player). Some players download games in the background to make the lags.
Now that you got some client side lags you simple do the following.
put the item that it needs (and make sure you have the needed money), and than shift click the item on the slot you just placed (on of the two trade slots that is not the money paper), and then quickly shift click on the result item to get it as well.
And now you have duped the item. you now got the Result item and the before item.

**Comment by blablubbabc** [comment]
> This bug works only on shopkeepers who sells stuff using any money

What do you mean by "money"?
Are you maybe using the third-party economy add-on plugin (
https://www.spigotmc.org/resources/shopkeepers-addon-navigation-economy-plotsquared-vault-integration.98400/), or some other kind of modification to the normal shopkeepers?
If this is the case, you may want to report this issue to the authors of that add-on plugin.

In either case, try to reproduce your issue without other plugins, on a fresh and up-to-date Spigot server.

**Comment by blablubbabc** [comment]
Closing this as no further information was provided.
