### ISSUE TITLE
Sugestion: Discounts per permission node

### ISSUE THREAD

**Issue by Thangsss** [Shopkeepers/Shopkeepers#828]
Would it be possible to set discounts of admin shopkeepers, depending on a players permission's

Say, some one has group.admin, so they get a 20% discount at admin shops

**Comment by blablubbabc** [comment]
Not really possible right now to set up any kinds of 'discounts'. You could however create a separate 'admin group' shopkeeper that trades your discounted trades and only allows players with the right permission to access it.

**Comment by blablubbabc** [comment]
For anything else, I am closing this ticket in favor of https://github.com/Shopkeepers/Shopkeepers/issues/763
