### ISSUE TITLE
Can't change the shopkeeper's name to hex colors

### ISSUE THREAD

**Issue by TBAProgramming** [Shopkeepers/Shopkeepers#830]
## Preliminaries:

* **Shopkeepers version:** `<2.16.5>`
* **Spigot version:** `<idk how to get it>`
* **My config of shopkeepers:** `<https://paste.gg/p/anonymous/f8cd1d26f1e94db8ad1ee7d95d79e395>`
* **HEX Colors Generator** `https://www.simplymc.art/Gradients/`
---

## The issue:

when i change shopkeeper name to HEX COLORS he wont change and i checked if i changed regex to `name-regex: "[A-Za-z0-9&§# ]{3,25}" in config`

**video:**  `i will edit it when i clipped a video`

**Comment by blablubbabc** [comment]
Names with hex color can get quite long. Your `name-regex` currently specified a maximum character limit of 25. So try to increase that. There is a built-in limit of 256 characters.

**Comment by TBAProgramming** [comment]
I DID IT

**Comment by TBAProgramming** [comment]
BUT NOT WORKING @blablubbabc

**Comment by TBAProgramming** [comment]
VIDEO : https://imgur.com/HHH0ErS

**Comment by blablubbabc** [comment]
Maybe try with a short name first, with a single hex color. If that works, then your non-working name is too long.

**Comment by TBAProgramming** [comment]
THAT IS SMALL

**Comment by TBAProgramming** [comment]
SEE 
![image](https://user-images.githubusercontent.com/121028379/236700301-f7f50573-4354-4242-8dfe-4712ed4990ca.png)

**Comment by TBAProgramming** [comment]
![image](https://user-images.githubusercontent.com/121028379/236700334-3419e3f0-2d93-4d3a-9108-2ca2dc49f663.png)

**Comment by TBAProgramming** [comment]
if he long it will say
![image](https://user-images.githubusercontent.com/121028379/236700356-0ba34e4c-5799-4bb3-b4f9-67f92a2c5c0f.png)

**Comment by blablubbabc** [comment]
Internally, the server converts hex color to a more verbose representation that takes 2 characters per hex digit. So a single hex color like `&#123456` internall becomes `&x&1&2&3&4&5&6`. The name length limit is applied to this expanded form.

**Comment by TBAProgramming** [comment]
That? &#A65A00&ld

**Comment by TBAProgramming** [comment]
![image](https://user-images.githubusercontent.com/121028379/236700738-8ce1c441-042a-45b6-b44e-e7bd62c7c4bf.png)
