### ISSUE TITLE
Regarding the inquiry about the method of opening the GUI.

### ISSUE THREAD

**Issue by 615303619** [Shopkeepers/Shopkeepers#836]
This is not a bug. I'm using the Citizens plugin, and I just want to ask if it's possible to disable opening the trade GUI by right-clicking on an NPC and instead open it using a command. I want to open the GUI during the conversation with the NPC, rather than directly by right-clicking.Thank you very much!

**Comment by blablubbabc** [comment]
I think the easiest would be to not actually use the NPC as the shopkeeper directly, but have the shopkeeper entity hidden somewhere else, and then remotely access it via commands when you want to access it.

Unfortunately, there are no "virtual" shopkeepers yet. So yu would have to hide a dummy shopkeeper entity or sign somewhere (maybe below the Citizens NPC).

**Comment by 615303619** [comment]
I have tested the second method and it is completely feasible. Thank you so much  : )

**Comment by 615303619** [comment]
I have tested the second method and it is completely feasible. Thank you so much. :)
