### ISSUE TITLE
[Feature] Add more then one container/Chest to a Shopkeeper

### ISSUE THREAD

**Issue by JaHollTV** [Shopkeepers/Shopkeepers#840]
Feature Request: Add more than one Container/Chest to a Shopkeeper.

Have an extra Button in a Shop to open a separate GUI. For each added container, a chest-item is shown on a slot.
With an extra button to add a container, the gui closes and you have X-Seconds to rightclick a chest.

If you want to remove a container you can just click on the chest in the gui. By hovering on a container you see the chest cords.

Should be not that much effort, but would improve shopkeepers alot!

**Comment by blablubbabc** [comment]
Duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/595

Thanks for the additional gui ideas of how the setup and interactions could be implemented in-game. However, I think we would also need a separate button to remove a container, so we can use left-click for the currently already existing'remotely open container' feature.
