### ISSUE TITLE
nbt

### ISSUE THREAD

**Issue by dinobossytnew** [Shopkeepers/Shopkeepers#846]
They should, if possible, add support to itemsadder and stop removing the NBT because removing it is like changing from 1 step to 21.

**Comment by blablubbabc** [comment]
I don't understand this request. Maybe you can clarify. But anyway: All the shopkeepers plugin does is set up vanilla-like villager trades, and some small extra stuff for things like player shop stock, and some additional checks to prevent common kinds of plugin incompatibilities messing up things in unexpected ways. So most kinds of item data / trading issues that you run into, I suppose, would likely also be encountered if you manually setup a custom vanilla villager trade.
