### ISSUE TITLE
No save

### ISSUE THREAD

**Issue by Vlastovka** [Shopkeepers/Shopkeepers#848]
If i edit the shop i and open it without shift it cant be traded and if i reopen with shift there no items

**Comment by blablubbabc** [comment]
Please let me know your exact server and plugin version. If you are using Paper, make sure that you are using the latest version (v2.17.2) of Shopkeepers.

**Comment by NekaouMike** [comment]
Ohhh yes I was about to make a issue about this. In my case here is my "specs"
SK Version: `2.17.1` *Might be patched in v2.17.2 but somehow I didn't get that version
PaperMC ver: `1.20.2`
I'll be back to test 2.17.2

**Comment by NekaouMike** [comment]
also now 2.80.0 is out

**Comment by NekaouMike** [comment]
OH!
1.17.2 + is NOT uploaded on to bukkit!

**Comment by NekaouMike** [comment]
@Vlastovka This is patched in 2.17.2 just so you know I just booted it on my server

**Comment by blablubbabc** [comment]
Closing. I assume that this is a duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/842 and therefore fixed in v2.17.2
