### ISSUE TITLE
[Feature] Villager Name Support Another Language

### ISSUE THREAD

**Issue by mok3103** [Shopkeepers/Shopkeepers#850]
I hope villager name support another language, not only English

**Comment by blablubbabc** [comment]
You can configure the list of allowed characters inside the config. See the comments inside the default config (https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration#default-configuration) for the setting `name-regex`: There are some examples on how to configure this setting to allow non-latin characters to be used in shop names.
