### ISSUE TITLE
plugin doesnt works

### ISSUE THREAD

**Issue by noname12332** [Shopkeepers/Shopkeepers#851]
## Preliminaries:

* **Shopkeepers version:** `2.18`
* **Spigot version:** `This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version>

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`not able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`1.20.1`**) with the latest version of Shopkeepers (currently **`2.18.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

the plugin just doesnt works

**Comment by blablubbabc** [comment]
Please clarify what you mean by "doesn't work". Also check your server log and attach any errors found there that might be relevant.
