### ISSUE TITLE
My citizen/NPC shopkeepers are all turned into normal NPC

### ISSUE THREAD

**Issue by RDiamonds** [Shopkeepers/Shopkeepers#855]
## Preliminaries:

* **Shopkeepers version:** `2.17.1`
* **Spigot version:** `This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`not able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`The server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT).`**) with the latest version of Shopkeepers (currently **`2.17.1`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help to reproduce the issue.

Include:
My shopkeepers which is using the Citizens plugin somehow convert all the traders into normal NPC. I don't know how this happen because last night when I'm working on the server it was all fine and normal, but then I join back in a couple minutes ago all the traders are turned into normal Citizen's NPC. I checked the save.yml file on the shopkeeper folder and everything is there (I'm assuming that's the file where the plugin "save" all the shopkeepers).

When I worked on my server last night I did nothing to the plugin's config or any other files (shopkeeper and citizen) all I did was adding more shopkeeper because I was working on a  new update. So I can't really provide any step-by-step on how I got this glitch. I also don't know if this a glitch from the citizen or the shopkeeper plugin, but hopefully I can get an answer here.

I also checked the `/shopkeeper list admin` command and nothing is there.
![immmage](https://github.com/Shopkeepers/Shopkeepers/assets/100850335/a27febc9-765c-43eb-85ef-3f71f544129e)
![imaaage](https://github.com/Shopkeepers/Shopkeepers/assets/100850335/bc22708d-cf51-41c5-bcb6-cc992a92e2c7)

**Comment by blablubbabc** [comment]
Can you upload and link here your Citizens and Shopkeepers save files?

**Comment by RDiamonds** [comment]
Okay thank you, updating it to 2.18.0 actually fixed it. I was just wondering because a lot of server on the Minehut host facing the same issue at the same time. Thank you for the help and sorry for the false alarm 👍
