### ISSUE TITLE
Data will not load

### ISSUE THREAD

**Issue by boqkzi** [Shopkeepers/Shopkeepers#856]
My minecraft servers been using shopkeepers for a few months now with no problems, but all of the sudden all of our shopkeepers just dissapeared. We have been trying to figure out a fix for a while now, anyone know what to do? The logs say that there was an error loading the data for each one. 

[
[2023-10-27T19_32_23.zip](https://github.com/Shopkeepers/Shopkeepers/files/13192627/2023-10-27T19_32_23.zip)

**Comment by blablubbabc** [comment]
Update the plugin.

See https://github.com/Shopkeepers/Shopkeepers/issues/842
