### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by TheRadishKimchi** [Shopkeepers/Shopkeepers#858]
## Preliminaries:

* **Shopkeepers version:** `<4>`
* **Spigot version:** `<forgotten>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<not able>`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`<git paper 193>`**) with the latest version of Shopkeepers (currently **`<4>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
My Shopkeepers Items are constantly deleted when im trying to edit them

Im not doing anything to the config yet, but somehow when i create a shopkeeper, then im editing the shop, closing and saving it, and then trying to edit the shop, all of the items suddenly deleted

Im expecting the items are remains the same when i leave the editor menu.

Provide a detailed description of your problem and add as much information as possible which could help to reproduce the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* ... Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
You are likely affected by this issue: https://github.com/Shopkeepers/Shopkeepers/issues/842
Updatng the shopkeepers plugin should resolve the issue.
