### ISSUE TITLE
Shopkeepers being able to run commands?

### ISSUE THREAD

**Issue by ArcheryAce** [Shopkeepers/Shopkeepers#859]
## Preliminaries:

* **Shopkeepers version:** `Latest (2.18.0)`
* **Spigot version:** `3763-Spigot-7d7b241-5a5e43e`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The question: In creating a Player shop. I need the output item to be a command that is run for the %player_name% Is that possible?

**Comment by blablubbabc** [comment]
Nope. This is on the todo list, tracked by https://github.com/Shopkeepers/Shopkeepers/issues/505
