### ISSUE TITLE
HideFlags tag exception

### ISSUE THREAD

**Issue by juinwei7** [Shopkeepers/Shopkeepers#863]
## Preliminaries:

* **Shopkeepers version:** `2.18.0`
* **Spigot version:** `1.20.1`
---

HideFlags is originally 255 and will become 127 after being added.

Occurs after reboot

**Comment by blablubbabc** [comment]
Upstream Ticket: https://hub.spigotmc.org/jira/browse/SPIGOT-7555

Pull request to fix it: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/1322/overview

**Comment by blablubbabc** [comment]
A fix has been merged into the Spigot server. So rebuild the latest server version and try again.
