### ISSUE TITLE
Not an issue but a questipn

### ISSUE THREAD

**Issue by KripticYT** [Shopkeepers/Shopkeepers#864]
Ok so my version is 20.1 and I'm using the newest version of the plugin and was wondering if you are or are able to be compatible with znpc's because one of my needed plugins isn't compatible with citizens but znpc's and would like to have npc shopkeeper's is that possible?

**Comment by blablubbabc** [comment]
I currently have no plans to support other NPC plugins. However, if znpcs allows attaching a command to NPC interactions, you could create some shopkeepers , hide them somewhere on your server (e.g. sign shopkeepers, hidden somewhere at your spawn), and then attach the `/shopkeeper remote <shop-name>` command to the znpc.
