### ISSUE TITLE
Does this Work on 1.8.9 too?

### ISSUE THREAD

**Issue by derover01** [Shopkeepers/Shopkeepers#867]
Does the plugin work on 1.8.9 too?

**Comment by blablubbabc** [comment]
You can find past versions here: https://dev.bukkit.org/projects/shopkeepers/files
Pick the last version that still supported 1.8.9.
You will not have all features found in the most recent versions, but the basics should be there.

**Comment by derover01** [comment]
Thank you Bro

blablubbabc ***@***.***> schrieb am Mi. 31. Jan. 2024 um
23:15:
