### ISSUE TITLE
The shop object "citizen" is disabled

### ISSUE THREAD

**Issue by shambii** [Shopkeepers/Shopkeepers#868]
## Preliminaries:

* **Shopkeepers version:** `<2.19.0>`
* **Spigot version:** `<git-Paper-196 (MC: 1.20.1)>`
---

## The issue:

* I'm making a Box PvP modality in my network. 
* I have the plugins: <CataMines, DecentHolograms, ItemEdit, multiverse-core, PlaceholderAPI, SkinRestorer, worldedit and worldguard> appart from <Shopkeepers and Citizens> 
* When I use the command **/shopkeeper npc** a message with <The shop object "citizen" is disabled> appears in the chat.
* No error is reflected in console.
* My config.yml: 
```
# Whether to allow the creation of Citizens NPC shopkeepers. Requires the
# plugin Citizens.
enable-citizen-shops: true
# The entity type of newly created Citizens NPC shopkeepers.
default-citizen-npc-type: PLAYER
```

* I already tried to see if the command worked on a server without any other plugin installed and it still gives the same problem.
* Any idea to fix it?

**Comment by blablubbabc** [comment]
You get this message if the Citizens plugin is not enabled or failed to properly enable due to some error. Can you attach the startup section of your server log that shows how the Citizens and the Shopkeepers plugin are getting enabled?

**Comment by blablubbabc** [comment]
Closed as no further information was provided.
