### ISSUE TITLE
w

### ISSUE THREAD

**Issue by CirrusPreeminent** [Shopkeepers/Shopkeepers#871]

**Comment by blablubbabc** [comment]
There have been various reports of itemsadder not properly working in Shopkeepers. See the respective section in the "Known issues" page: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues

In your case: Try to avoid legacy color codes in text fields (the the plugin is adding that, maybe report this to them). The server can end up modifying the representation of these items in various situations. For example, on Paper servers, the server will convert the internal representation of all items with legacy color codes inside text components whenever a player joins and has such an item in their inventory.
On Spigot, especially on 1.20.4, I think to remember that some user also reported an issue with item text data changing in certain circumstances (such as when copying chest with NBT data in creative mode). But I have to do some more testing to figure out the details of when exactly this occurs.
