### ISSUE TITLE
Statistic Placeholders ISSUE

### ISSUE THREAD

**Issue by GreenedDev** [Shopkeepers/Shopkeepers#872]
## Preliminaries:

* **Shopkeepers version:** `2.19.0`
* **Paper version:** `
![image](https://github.com/Shopkeepers/Shopkeepers/assets/108997309/538bb729-0374-47b4-9b9b-e7e8c1246d9a)
`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

Yes this can be easily reproduced

## The issue:

Provide a detailed description of the issue and information on how to reproduce it.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* ... Anything else that might be useful to reproduce and identify the issue.

%statistic_traded_with_villager% placeholder does not count the custom villager trades.

download placeholderapi and /papi ecloud download Statistic. then do /papi parse me %statistic_traded_with_villager%. remember the value. then again trade with custom shopkeeper villager and check if value is same or not. it is same.

it should count the custom villager trades too.

**Comment by blablubbabc** [comment]
The vanilla villager statistics are not incremented by default when you open or trade with a shopkeeper. After all, shopkeepers are not necessarily villagers, and servers usually don't want custom shop plugins to interfer with vanilla statistics.
However, there is a setting `increment-villager-statistics` with which you can enable that the plugin manually increments the vanilla "talked to villager" and "traded with villager" statistics anyway whenever a player opens a shopkeeper trading window or performs a trade. So try out this setting and let me know if this works for you.

**Comment by GreenedDev** [comment]
Solved, thanks
