### ISSUE TITLE
Editing a Shopkeepers armour and items

### ISSUE THREAD

**Issue by TumbleElf** [Shopkeepers/Shopkeepers#876]
* **Shopkeepers version:** Latest

I have question about these features: https://github.com/Shopkeepers/Shopkeepers/issues/596

Is the ability to change armour etc implemented yet? I want to place a player head on a Drowned shopkeeper I spawned in. Is there anyway to do this?

**Comment by blablubbabc** [comment]
No. As indicated by the linked open ticket, this is not available yet. As an alternative, maybe the Citizen shopkeepers support editing the NPC equipment.
