### ISSUE TITLE
Maven Repository Issue - Not Reachable

### ISSUE THREAD

**Issue by Wolf2323** [Shopkeepers/Shopkeepers#877]
## The issue:

The maven repository seems to have issue: https://nexus.lichtspiele.org/repository/releases/

**Comment by blablubbabc** [comment]
Hey, thanks for the info. I have contacted the party hosting the repository. Apparently, some hardware broke and they are currently investigating what can be restored from backup and what needs or makes sense to be set up freshly. I will update this ticket once I have more information.

For the time being, you can also the jitpack hosted fallback repository: https://jitpack.io/#Shopkeepers/Shopkeepers/v2.19.0

**Comment by blablubbabc** [comment]
The repository is online again.

As a side note, I also experimented a bit with the jitpack fallback, but it seems like this is currently broken: I have fixed the build timeout issue, so the build completes now when run by jitpack and also produces the expected results locally. But for some reason, the jar artifact served by jitpack is empty.
