### ISSUE TITLE
1.20.6 support

### ISSUE THREAD

**Issue by CaptainSnickerz** [Shopkeepers/Shopkeepers#880]
## Preliminaries:

* **Shopkeepers version:** `<2.19.0>`
* **Spigot version:** `<This server is running Paper version git-Paper-52 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: eee55d0)
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able >`** to reproduce my issue on a freshly set up and up-to-date Spigot server with the latest version of Shopkeepers (currently **`<2.19.0>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
type /shopkeeper
https://pastebin.com/KZaVAYuy

**Comment by blablubbabc** [comment]
Shopkeepers v2.20.0 is available now and provides support for MC 1.20.6.
