### ISSUE TITLE
Lightning spawn eggs are turned into turtle spawn eggs on restart

### ISSUE THREAD

**Issue by prototype464** [Shopkeepers/Shopkeepers#882]
## Preliminaries:
* **Shopkeepers version:** `2.19`
* **Spigot version:** `git-Paper-459 (MC: 1.20.4)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`git-Paper-459 (MC: 1.20.4)`**) with the latest version of Shopkeepers (currently **`2.19`**), with no other plugins and with no kinds of other server or client mods.

## The issue:
Provide a detailed description of the issue and information on how to reproduce it.

Include:
* Description:
Lightning spawn egg is turned into a Turtle spawn egg upon restarting the server.
* Step-by-step instructions on how to reproduce the issue:
1. /give @p minecraft:vex_spawn_egg{EntityTag:{id:"minecraft:lightning_bolt"}}, placing it spawns lightning
2. Put it in the shop, close the menu
3. Turn the server off, restart it, etc.
4. The spawnegg will be a turtle spawn egg and spawns turtles, instead of whatever egg it was before and lightning
* Server logs:
There's no errors, warnings, or anything.
* If modified from default: Nothing.
* ... Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
Spigot doesn't properly support spawn eggs with "EntityTag". See https://github.com/Shopkeepers/Shopkeepers/issues/718

**Comment by prototype464** [comment]
Yeah I just saw https://hub.spigotmc.org/jira/browse/SPIGOT-5485

That sucks, man.
