### ISSUE TITLE
Right clicking shopkeepers isn't opening trade menu when only 1 price is set for an item

### ISSUE THREAD

**Issue by LotusxxEater** [Shopkeepers/Shopkeepers#885]
## Preliminaries:

* **Shopkeepers version:** 2.20.0
* **Spigot version:** Paper 1.20.6
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

When creating admin shopkeepers we ran into an issue when setting up only a single price in row 3. If I do this though the trade menu/gui wont pop up at all when right clicking the npc. It will only work if we put a price in BOTH row 2 and row 3. We don't want to have 2 prices for 1 item and have not been able to figure out why this is happening.

**Comment by blablubbabc** [comment]
Information on the exact server version and type, as well as potential server logs would be useful.

However, there was an issue fixed for Paper servers in Shopkeepers 1.20.1 that broke trades that contained an empty item. My guess is that this matches this issue. If not, please provide information on how to reproduce the issue.
