### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by m4kii420** [Shopkeepers/Shopkeepers#891]
Hi, I suggest adding an option to add a console or player command that will run when the player closes a **specific** Shopkeeper.

With this, we could make a GUI with a plugin like DeluxeMenus where they would be able to open shopkeeper menus, and when they exit it, they will autorun for example `/shop` command which will get them back to shop menu.

I don't know if is this doable but if it is it would be very helpful.

__Also sorry for using the "issues" section, idk where else to send this.__

**Comment by blablubbabc** [comment]
This can already be achieved via the plugin API. I don't currently intend to additionally provided a command api for this event.

**Comment by FaultyFunctions** [comment]
Just commenting here stating that I am also looking for this feature. Just in case you change your mind as I think it would be a really nice feature to use.
