### ISSUE TITLE
I have issues on loading my save.yml file on minecraft multiserver

### ISSUE THREAD

**Issue by yeedj320** [Shopkeepers/Shopkeepers#895]
* **Shopkeepers version:** `<2.22.1>`
* **Spigot version:** `<This server is running CraftBukkit version 4226-Spigot-146439e-2889b3a (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)>`
---
## The issue:

I cannot load my save.yml on 1.21 version  multiserver
(the Error Message)
[Shopkeepr Error.txt](https://github.com/user-attachments/files/16118710/Shopkeepr.Error.txt)
(My Save.yml)
[save.txt](https://github.com/user-attachments/files/16118713/save.txt)

**Comment by blablubbabc** [comment]
THis was fixed in Spigot ~1 week ago: https://hub.spigotmc.org/jira/browse/SPIGOT-7804
