### ISSUE TITLE
THERES FIRE MY SHOPKEEPERS ARE ALL ON FIRE

### ISSUE THREAD

**Issue by Patatatta** [Shopkeepers/Shopkeepers#900]
## Preliminaries:

* **Shopkeepers version:** `2.22.1`
* **Spigot version:** `This server is running Paper version git-Paper-22 (MC: 1.20.5) (Implementing API version 1.20.5-R0.1-SNAPSHOT) (Git: 8f7ac62)
You are running the latest version
Previous version: git-Paper-318 (MC: 1.20.2)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`< not able>`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`<This server is running Paper version git-Paper-22 (MC: 1.20.5) (Implementing API version 1.20.5-R0.1-SNAPSHOT) (Git: 8f7ac62)
You are running the latest version
Previous version: git-Paper-318 (MC: 1.20.2)>`**) with the latest version of Shopkeepers (currently **`<2.22.1>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of the issue and information on how to reproduce it.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* ... Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
MC 1.20.5 is not supported by the plugin. Try updating to 1.20.6.

Also, there are some item serialization issues affecting the 1.20.5/6 Spigot server, which might also affect Paper. My current recommendation is to stay on 1.20.4 until those have been fixed.
