### ISSUE TITLE
Bootstrap Method Initialization Exception on Startup for Shopkeepers Plugin

### ISSUE THREAD

**Issue by JhonCastella** [Shopkeepers/Shopkeepers#904]
## Preliminaries:

* **Shopkeepers version:** `V2.22.2`
* **Spigot version:** `Current: git-Plazma-"964880b" (MC: 1.19.4)*
Previous: git-Paper-241 (MC: 1.20.2)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`not able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (**`currently git-Plazma-"964880b" (MC: 1.19.4)*
Previous: git-Paper-241 (MC: 1.20.2)`**) with the latest version of Shopkeepers (currently **`v2.22.2`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

When trying to enable the Shopkeepers plugin on my Minecraft server running version 1.19.4, a bootstrap method initialization exception occurs. The full error log is attached below.  https://mclo.gs/WZ0U6PC

Additional Information:
This issue started after accidentally running the server on version 1.20.2 and then downgrading back to 1.19.4. Any help resolving this issue would be greatly appreciated.

**Comment by blablubbabc** [comment]
> then downgrading back to 1.19.4

Downgrading is not supported. The save file saved in one version cannot be loaded in older versions.
You need to restore the save file from back up, manually "downgrade" it (revert all item version numbers + any item data changes that might have taken place during the migration to 1.20.2), or delete the save file and start frsh, or update the server back to 1.20.2
