### ISSUE TITLE
Restrict shop type for players

### ISSUE THREAD

**Issue by MightyX3N** [Shopkeepers/Shopkeepers#905]
How do i restrict the shop type a player can use, i only want trade type

**Comment by blablubbabc** [comment]
Each shop type has a dedicated permission. See https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Permissions

Use a permission plugin (or the built-in Bukkit [permissions.yml](https://bukkit.fandom.com/wiki/Permissions.yml)) to disable the default `shopkeeper.player` permission, and then assign the individual player shop permissions that you want to allow.
