### ISSUE TITLE
shopkeepers not working on 1.20.1

### ISSUE THREAD

**Issue by Talememe123** [Shopkeepers/Shopkeepers#906]
## Preliminaries:

* **Shopkeepers version:** `2.22.2`
* **Spigot version:** `1.20.1`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

I Tried running the plugin on my skymine server on the version 1.20.1  and it didnt worked for me

**Comment by blablubbabc** [comment]
* Can you please attach the output of `/version` on your server.
* If you are using a server fork, can you please try to reproduce the issue on a normal Spigot server.
* Can you attach a log of your server startup.

**Comment by Talememe123** [comment]
i cant do /version but the version is 1.20.1 paper server

**Comment by blablubbabc** [comment]
Closed as no further information was provided to help reproduce this.
