### ISSUE TITLE
Paper 1.20.4 Shopkeepers not working

### ISSUE THREAD

**Issue by recondra** [Shopkeepers/Shopkeepers#911]
Shopkeepers is not running on my server with Paper 1.20.4 installed. When you upgrade to version 1.20.6, it works, but some plugins remain inactive. So I have to stay on 1.20.4. 

Console: 
[14:31:50 ERROR]: [Shopkeepers] Server assumption test failed: Bukkit ItemStack#isSimilar(Deserialized ItemStack)
[14:31:50 ERROR]: [Shopkeepers] Server incompatibility detected! Disabling the plugin!

**Comment by blablubbabc** [comment]
Is your system by chance using the turkish locale? If yes, then see this ticket: https://github.com/Shopkeepers/Shopkeepers/issues/886

Spigot fixed this in 1.20.6. For 1.20.4 you will need to use the workaround mentioned on the ticket.

**Comment by recondra** [comment]
I tried the solutions in the ticket you mentioned, but the result was unsuccessful again. I don't think I'm doing anything wrong, but it would be better if you could tell me exactly what I should do.

**Comment by recondra** [comment]
I didn't see the error because I typed the input incorrectly. Fix.

**Comment by blablubbabc** [comment]
> I didn't see the error because I typed the input incorrectly. Fix.

Issue resolved?
