### ISSUE TITLE
I HAVE A PROBLEM WITH 1.21 PAPER

### ISSUE THREAD

**Issue by r3velk** [Shopkeepers/Shopkeepers#912]
Preliminaries:
Shopkeepers version: 2.23.0
Spigot version: Paper version 1.21-126-master@7e44684 (2024-08-05T19:10:11Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
I have checked that my issue/question does not get answered by:
The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.
Reproduction on a fresh and up-to-date Spigot server:
I was able to reproduce my issue on a freshly set up and up-to-date Spigot server (currently Paper version 1.21-126-master@7e44684 (2024-08-05T19:10:11Z) (Implementing API version 1.21-R0.1-SNAPSHOT)) with the latest version of Shopkeepers (currently 2.23.0), with no other plugins and with no kinds of other server or client mods.

The issue:
Description of the issue:
Every time I restart the server to implement a new plugin or datapack, Shopkeepers becomes completely unusable. It shows up in red (disabled) on the plugins list, and all NPCs and commands related to the plugin are disabled. I can't even reload the plugin. The only workaround I've found is to delete the Shopkeepers folder entirely and reinstall the plugin, which is quite inconvenient.

Step-by-step instructions on how to reproduce the issue:

Set up a fresh Paper server with the same version as stated above.
Install Shopkeepers version 2.23.0.
Restart the server after implementing a new plugin or datapack.
Observe the Shopkeepers plugin status.
Observed behavior:
Shopkeepers shows up as disabled in the plugin list, and all related functionalities, including NPCs and commands, become inaccessible.

Expected behavior:
Shopkeepers should remain enabled and fully functional after a server restart, without requiring manual deletion and reinstallation of the plugin.

If modified from default: Plugin configurations:
[config.txt](https://github.com/user-attachments/files/16621704/config.txt)

... Anything else that might be useful to reproduce and identify the issue:
No additional modifications or plugins were involved in this issue. The server environment was kept as clean and default as possible to ensure this issue is related specifically to Shopkeepers.

**Comment by blablubbabc** [comment]
* Please attach the server log of when the plugin fails to enable.
* Also try if you can reproduce the issue on a fresh and up-to-date Spigot server, just to rule out Paper being inolved in the cause of the issue.
