### ISSUE TITLE
ShopKeepers not working (minehut)

### ISSUE THREAD

**Issue by QndreiYT69aalltt** [Shopkeepers/Shopkeepers#915]
I wanna make a BoxPvP server but my shopkeepers plugin is not working. The version is 2.23.0. I checked everything, plugins, dependencies, reinstalled the plugin, everything, but nothing, someone help?
![Screenshot 2024-08-26 113239](https://github.com/user-attachments/assets/839d64a7-6a79-43fd-b447-65a5ea8c2393)

**Comment by blablubbabc** [comment]
Please attach your server's startup log.
