### ISSUE TITLE
How to make for 1.20.4?

### ISSUE THREAD

**Issue by Cutecutebethoven** [Shopkeepers/Shopkeepers#916]
How to make for 1.20.4? cus 1.21 doesnt work

**Comment by blablubbabc** [comment]
Pick the correct plugin version for your server version. v2.22.3 should work fine for MC 1.20.4 https://dev.bukkit.org/projects/shopkeepers/files/5569421

If youstill have issues, please fill out the issue template: Specify the exact server version and attach a server log of your server startup.
