### ISSUE TITLE
DOESNT WORK FOR 1.21.1 (MINEHUTTTT) PLS HELP

### ISSUE THREAD

**Issue by Cutecutebethoven** [Shopkeepers/Shopkeepers#917]
It doesnt work for 1.21.1

**Comment by blablubbabc** [comment]
If you have further information, attach it to the ticket you already created: https://github.com/Shopkeepers/Shopkeepers/issues/916

**Comment by Cutecutebethoven** [comment]
nvm the tutorial was old the command is /shopkeeper
