### ISSUE TITLE
Shopkeepers is not working with Itemsadder

### ISSUE THREAD

**Issue by pjindras** [Shopkeepers/Shopkeepers#920]
## Preliminaries:

* **Shopkeepers version:** `2.23.0`
* **Spigot version:** `Always latest Paper version for 1.21.1`
---

## Reproduction on a fresh and up-to-date Spigot server:

It is not working with itemsadder textures and items. IA version 4.0.2-beta-release-11

https://mclo.gs/6YnrHoQ

Itemsadder integration / compatibility is not working properly.

**Comment by blablubbabc** [comment]
This seems to be the same error as in this ticket: https://github.com/Shopkeepers/Shopkeepers/issues/918 This is something for ItemsAdder to fix.

Regarding trades not working (different issue): Other users have also reported issues in combination with ItemsAdder in the past, but it is not completely clear what is causing thos issues. See here: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues
The Shopkeepers plugin does not implement adaptations / "integrations" with other item plugins. If some trade is not working, you need to compare the item data of the item required by the trade and the item offered by the trading player and then check if you can avoid those item data differences.
