### ISSUE TITLE
Player shops destroyed by wind charges when container protection is disabled

### ISSUE THREAD

**Issue by lerokko** [Shopkeepers/Shopkeepers#921]
## Preliminaries:

* **Shopkeepers version:** `2.23.0`
* **Spigot version:** `This server is running CraftBukkit version 4333-Spigot-a759b62-fc5b2d7 (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`This server is running CraftBukkit version 4333-Spigot-a759b62-fc5b2d7 (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
`**) with the latest version of Shopkeepers (currently **`2.23.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Create a sign shop. It has to be a wall sing attached to a full block (like a grass block). Throw a wind charge at the sing (or near it). Sign is gone. This does not happen when the sing is attached to a chest or standing freely.
Throwing a wind charge at a block should not delete the block.

Tested also on latest paper (116).

**Comment by blablubbabc** [comment]
I cannot reproduce this on my local 1.21.1 Spiot dev version (28 builds behind). Will try to reproduce this on the latest Spigot version later (there was some wind charge related change in the latest commit, maybe it broke something).

**Comment by asdanjer** [comment]
this seems to only effect Player shops. The one in the screenshot appears to be an admin shop.

**Comment by lerokko** [comment]
Seems like its less consistent than I thought and not only on full blocks. I do not know what the quirks are. I have also tested this with a vanilla CLIENT before (video shows mods) and it is not a client side issue. It still happens in vanilla, and persists after relogs and restarts

[YouTube video demonstration the issue](https://youtu.be/EtzuOa6GKqk)

**Comment by asdanjer** [comment]
It seems to think that the container is being broken. this does not happen with 
delete-shopkeeper-on-break-container: false

**Comment by blablubbabc** [comment]
I still cannot reproduce the issue even with player shops and with `delete-shopkeeper-on-break-container` enabled and the chest being targeted by the wind charge.

Can you please tro to reproduce the issue without any other plugins? Maybe some plugin is implementing some kind of "wind charge destroys blocks" mechanic?

Also, can you attach your Shopkeepers config.yml file, so I can try to reproduce it with your settings?
