### ISSUE TITLE
PLEASE HELP ME FIX IT

### ISSUE THREAD

**Issue by MeoNguOfficial** [Shopkeepers/Shopkeepers#924]
I use Shopkeeper, although i turn on show-name-template and always-show-name-template, but shopkeeper name is auto hidden sometime

Config Shopkeeper:
https://pastecode.dev/s/g1t0611v
Version Shopkeeper: 2.23.0

Version server: This server is running Leaf version 1.21.1-DEV-ver/1.21.1@1f7276d (2024-10-13T06:16:26Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

Screenshot:
![image](https://github.com/user-attachments/assets/c4590f72-e11b-4ae4-91f8-a799b997f1b7)
![image](https://github.com/user-attachments/assets/7e4cc54a-e986-4e68-acee-93723d429aff)
![image](https://github.com/user-attachments/assets/ca7b0b1b-cfc8-42c0-a878-d537e8bcc615)

**Comment by blablubbabc** [comment]
I cannot reproduce this on the latest Spigot 1.21.1.

But either way: The `always-show-nameplate` setting controls whether to set Minecraft's `CustomNameVisible` flag. On certain Minecraft versions, this flag is known to not have worked as expected, so it is up to Minecraft to "implement" the behavior of this entity flag (if the flag were to stop working, I do not intend to manually fake entity nameplates e.g. by manually implementing them via holograms or similar). But at least for 1.21.1, it appears to work fine for me.

![grafik](https://github.com/user-attachments/assets/c65d2e20-549d-465c-b730-bc15a6f415a6)
