### ISSUE TITLE
Wiki problem

### ISSUE THREAD

**Issue by SnowCutieOwO** [Shopkeepers/Shopkeepers#926]
## Preliminaries:

* **Shopkeepers version:** `N/A`
* **Spigot version:** `N/A`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

N/A since it's a wiki documentation problem :3

## The issue:

Documents are still using outdated *gamepedia* link since it had been moved to *minecraft.wiki*

So just fix it please :3

**Comment by SnowCutieOwO** [comment]
Oh sorry i found the place i should go, i should close this :)

**Comment by blablubbabc** [comment]
The only remaining references I found were in https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration and https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Placeholder-Items, which I have updated. If you spot any other references to outdated links (also to fandom), please let me know.

**Comment by SnowCutieOwO** [comment]
> The only remaining references I found were in https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration and https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Placeholder-Items, which I have updated. If you spot any other references to outdated links (also to fandom), please let me know.

Yes.
https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions
The "Villager Level" part contained a link from fandom, please fix it :3

**Comment by blablubbabc** [comment]
> > The only remaining references I found were in https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration and https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Placeholder-Items, which I have updated. If you spot any other references to outdated links (also to fandom), please let me know.
> 
> Yes. https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions The "Villager Level" part contained a link from fandom, please fix it :3

Updated.

Also found some broken Bukkit wiki link which was fixed from gamepedia -> fandom: https://bukkit.fandom.com/wiki/Permissions.yml

**Comment by SnowCutieOwO** [comment]
> > > The only remaining references I found were in https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration and https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Placeholder-Items, which I have updated. If you spot any other references to outdated links (also to fandom), please let me know.
> > 
> > Yes. https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions The "Villager Level" part contained a link from fandom, please fix it :3
> 
> Updated.
> 
> Also found some broken Bukkit wiki link which was fixed from gamepedia -> fandom: https://bukkit.fandom.com/wiki/Permissions.yml

Where is this link? Please let me know since I should also apply them to my Chinese translation :3

**Comment by blablubbabc** [comment]
> > > > The only remaining references I found were in https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Configuration and https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Placeholder-Items, which I have updated. If you spot any other references to outdated links (also to fandom), please let me know.
> > > 
> > > 
> > > Yes. https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions The "Villager Level" part contained a link from fandom, please fix it :3
> > 
> > 
> > Updated.
> > Also found some broken Bukkit wiki link which was fixed from gamepedia -> fandom: https://bukkit.fandom.com/wiki/Permissions.yml
> 
> Where is this link? Please let me know since I should also apply them to my Chinese translation :3

If you want to keep your wiki updated with my changes, the easiest is probably to monitor the wiki's Git history, either by cloning the wiki repository (see https://stackoverflow.com/questions/15080848/how-do-i-clone-a-github-wiki), or here: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/_history
