### ISSUE TITLE
Wiki problem #2

### ISSUE THREAD

**Issue by SnowCutieOwO** [Shopkeepers/Shopkeepers#930]
## Preliminaries:

* **Shopkeepers version:** N/A
* **Spigot version:** N/A
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

N/A since it's a wiki problem :3

## The issue:

ShopkeeperNavAddon now could be replaced with [Shopkeepers Addon](https://www.spigotmc.org/resources/shopkeepers-addon-1-16-1-21-%C2%BB-navigation-economy.98400/), this plugin also added vault economy support.

:3

**Comment by blablubbabc** [comment]
The link is actually the same plugin. I updated the name in the wiki and removed the "abandoned" note.

**Comment by SnowCutieOwO** [comment]
> The link is actually the same plugin. I updated the name in the wiki and removed the "abandoned" note.

Got it. And I noticed that these two plugins are using bukkit.org redirect link instead of original spigotmc. Is this intended?

**Comment by blablubbabc** [comment]
> > The link is actually the same plugin. I updated the name in the wiki and removed the "abandoned" note.
> 
> Got it. And I noticed that these two plugins are using bukkit.org redirect link instead of original spigotmc. Is this intended?

Not intended and updated
