### ISSUE TITLE
Feature Request: limit on size of Slime/Magma Cube

### ISSUE THREAD

**Issue by BobShoe212** [Shopkeepers/Shopkeepers#931]
Hey Blab,

Feature request, not an issue, so I'll get straight to it:
Can we please get a config option to reduce the max size of the Magma/Slime mobs?

Currently they can go up to size 10, which is quite large. 
Personally I would limit them to size 4. Possibly size 5 for the Magma, so separate value options would be good.

Thanks,
BobShoe212

**Comment by blablubbabc** [comment]
There will be two new settings `slime-max-size` (default: `5`) and `magma-cube-max-size` (default: `5`) in the next plugin version
