### ISSUE TITLE
player_head not trading 

### ISSUE THREAD

**Issue by Mutlz** [Shopkeepers/Shopkeepers#932]
![resim_2024-11-16_012048015](https://github.com/user-attachments/assets/f4248763-c8c0-407d-9814-84983814654a)
Shopkeepers version: 2.23.1
Spigot version: Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)**`

After creating Shopkeeper, I add the player_head item there. This player_head has 20 Protection Enchants.
I make many player_heads like this, but when I put the player_head in Shopkeeper, it cannot be traded or the box is empty.

For example:
player_head - Coin = [Not Trading]
player_head - Coin = [Empty Slot but I Click this and give me the player_head]
These 2 rates occur randomly. Sometimes the slot is empty, sometimes it is not traded

**Comment by blablubbabc** [comment]
> This player_head has 20 Protection Enchants.

Can you try to reproduce your issue with a simpler item, maybe a head item with only one enchant?
And then please provide a give command to create this item, so I can try to reproduce the issue.

> player_head - Coin = [Empty Slot but I Click this and give me the player_head]

If you are using ViaVersion, please try without it. Also try without any protocol plugins (e.g. ProtocolLib).

**Comment by Mutlz** [comment]
I also tried a server where protocollib was deleted! but there are many plugins containing "protocollib" on my main server, what should I do?

**Comment by Mutlz** [comment]
Hello I Try delete protocollib but this is not work
The player_heads already 1 Enchant BUT unbreakble in minecraft attribute

**Comment by blablubbabc** [comment]
> Hello I Try delete protocollib but this is not work The player_heads already 1 Enchant BUT unbreakble in minecraft attribute

Please provide me with a Minecraft give command with which I can create this particular item in order to try to reproduce the issue

**Comment by blablubbabc** [comment]
> /itemedit enchant protectin 20 /itemedit unbreakable

Which plugin are you using for the `/itemedit` command?

**Comment by Mutlz** [comment]
Yep

**Comment by blablubbabc** [comment]
I cannot reproduce the issue on a Spigot server with the latest plugin version: I created the item as you described, but the trade worked and the result item showed up fine,even after reconnects and restarting the server.

![grafik](https://github.com/user-attachments/assets/e77f4075-be9d-4f32-bd2d-b674beb85be0)

**Comment by blablubbabc** [comment]
Closed as I cannot reproduce the issue with the information provided. My current guess is that some other component of the server (maybe ViaVersion, or some other plugin) is conflicting.
