### ISSUE TITLE
I can't trade in shopkeeper

### ISSUE THREAD

**Issue by huynhphap100** [Shopkeepers/Shopkeepers#936]
## Preliminaries:

* **Shopkeepers version: 2.23.3**
* **Spigot version: 1.18.5** 
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

when I add lore and remove this lore, the lore of the new item and old item have the same value, but the display nbt value is different value and i can't trade
 in the shopkeeper. Does you have a solution?

![image2](https://github.com/user-attachments/assets/ea6ff46f-c8b8-4925-9e62-5e26f13e028c)

**Comment by blablubbabc** [comment]
I have no solution. Items are only considered equal if their internal data is equal. This internal text representation can depend on:
- How you edit the lore.
- The plugin and plugin version you are using to edit the lore.
- The server version you are using.

So if there are differences from one server or plugin version to the next, you will have to ask the server authors or authors of the plugin you are using to edit this data.

For shopkeepers to accept your knew item in trades you need to replace the item inside the shopkeeper.
