### ISSUE TITLE
Russian lang

### ISSUE THREAD

**Issue by VORHAL** [Shopkeepers/Shopkeepers#937]
Hello. I have translated into Russian. I don't know how to contact you to send the file.
[language-ru-default.zip](https://github.com/user-attachments/files/18202334/language-ru-default.zip)

**Comment by blablubbabc** [comment]
Hi, thank you. Attaching it as zip to a github ticket is fine. We have a dedicated Github repository for the language files here: https://github.com/Shopkeepers/Language-Files

However, it seems like your language file is for version 2.22.2, for which we already have a language file here: https://github.com/Shopkeepers/Language-Files/blob/v2.22.2/lang/language-ru.yml

So maybe consider updating this or your language file, then I can add it for the latest plugin version.
