### ISSUE TITLE
(Feature Request) Timed Shopkeeper

### ISSUE THREAD

**Issue by Abood8001** [Shopkeepers/Shopkeepers#939]
Add an option where you could make a shop that has a limited time offer, where the listed items to sell are available for a specific time

where you are able to make lists, list1, list2 and so on...

List 1 will be available for example 3 hours

after 3 hours it will hide list 1 and display list 2 for a specific time

and after list 2 time ends it will go back to list 1 or other lists

this could be used for events and many things

**Comment by blablubbabc** [comment]
This can already be achieved with the snapshot feature (see the snapshot commands) + some third-party command to run commands in specific intervals: You can create shopkeeper snapshots for your different trade configurations and switch between them via command.
